### ISSUE TITLE
Automate generating changelogs

### ISSUE THREAD

**Issue by pktiuk** [AntiMicroX/antimicrox#10]
Automated generation of changelogs would save a lot of time it would be good to integrate it with repository.
All would be based on [semantic commit messages](https://www.conventionalcommits.org/en/v1.0.0/).

Things to do:
- [ ] Write scripts generating changelogs (markdown would be the best format), old changelogs should be preserved.
- [ ] integrate script generation with github actions (on merge to master + on publishing new release)
- [ ] (if possible) create scripts generating changelogs in Fedora [link](https://docs.fedoraproject.org/en-US/packaging-guidelines/#changelogs) and Debian-based [link](https://www.debian.org/doc/debian-policy/ch-source.html#s-dpkgchangelog) format
- [ ] Write some simple guidelines for recommended naming of merge commits

**Comment by pktiuk** [comment]
Are there any ways of filtering commits to be mentioned in changelogs (by tags or by scope of checged files)?  
I don't want to fill our changelogs with README updates etc.

**Comment by gombosg** [comment]
I'll look into this, but first, Flathub and Fedora submission has priority.

**Comment by pktiuk** [comment]
Requirements for our changelogs:
- describe changes visible for end-users (changing readme, or any similar files doesn't count)
- don't include issues irrelevant for users (for example issues tagged as questions shouldn't be mentioned), I am not sure if issues should be mentioned in changelog at all :thinking: 
- avoid duplicates (for example if we have bug mentioned by issue and single Pull request fixing it, we should mention only one of them) 
- It would be good to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) to have multiple categories


I am not sure about mentioning changes in code, which doesn't affect functionality (I mean cleanups, chores etc).

But in Release descriptions (visible on [release site](https://github.com/AntiMicroX/antimicrox/releases)) we should show all the changes on repo since previous release Issues, Merges etc.

**Comment by gombosg** [comment]
https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples
Here you can see which labels we can use.
Doing complex config is not possible here, if you want complex changelog, then we'll have to write it manually.

**Comment by pktiuk** [comment]
We could generate basic log, and later we could cut it using Python script (I can write this script).

**Comment by gombosg** [comment]
A simple git commit log command with sed or whatever?

**Comment by pktiuk** [comment]
I mean, we could generate regular changelog using this generator and later remove all of unwanted commits.

**Comment by pktiuk** [comment]
Or we could just generate these changelogs using your config and manually remove unwanted pieces (I think it will be the simplest solution, because removing some lines is pretty quick task).

**Comment by gombosg** [comment]
Okay, let's stick with that for now! :)

**Comment by gombosg** [comment]
For now I just changed labels for sections so that we can manually remove stuff.
We can also play around with section and PR labels: https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples#section-options

So we'll only include e.g. enchantments and bugs, but not docs and packaging, or whatever.

**Comment by gombosg** [comment]
I'd close this issue for now, auto changelog generation works fine. We can reopen if more stuff comes up later. :slightly_smiling_face:
