### ISSUE TITLE
Issue with float value for "Auto Reset Cycle After"

### ISSUE THREAD

**Issue by pepper-jelly** [AntiMicroX/antimicrox#1002]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

If I set Auto Reset Cycle After to 2,6 it becomes 3,2. To set to 2,6 I need to put 2,3 for some reason. After changing value I hit insert to update the block.

### Expected Behavior

It saves value I've set.

### Steps To Reproduce

Advanced.

### Environment

```markdown
*latest git build

Program Version 3.4.0
Program Compiled on Jun 30 2024 at 15:08:52
Built Against SDL 2.30.4
Running With SDL 2.30.4
Using Qt 5.15.14
Using Event Handler: XTest
Compositor type: x11
Host OS: artix Version: unknown Architecture: x86_64
```

### Anything else?

current and couple of old releases extracted from deb packages give me the same issue as git build
for now I just edited profile manually

![Scr 106](https://github.com/AntiMicroX/antimicrox/assets/45047877/cf3b79d8-17a5-4a8f-8706-94fd3604052f)

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1002">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1002/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1002/pledge.svg">
</picture>
</a>

**Comment by pepper-jelly** [comment]
https://github.com/AntiMicroX/antimicrox/blob/59296df97dd8949b1d6155558508df9d513b4f12/src/gui/advancebuttondialog.cpp#L1287

Why not use just:
```C
int milliseconds = value * 1000;
```

**Comment by pktiuk** [comment]
> https://github.com/AntiMicroX/antimicrox/blob/59296df97dd8949b1d6155558508df9d513b4f12/src/gui/advancebuttondialog.cpp#L1287
> 
> Why not use just:
> 
> ```c
> int milliseconds = value * 1000;
> ```


It was introduced in https://github.com/AntiMicroX/antimicrox/commit/20dbe3ad222715595c136ddaa643f286f06aa109 and TBH I have no ide why such a strange code was written

**Comment by pktiuk** [comment]
I know now, it was bug introduced by previous maintainer. Originally it was added in https://github.com/AntiMicroX/antimicrox/commit/0ceb35f24c05d5c423d1c5e865088f81d6721038 

```cpp
unsigned int milliseconds = ((int)value * 1000) + (fmod(value, 1.0) * 1000);
```

And it worked
