### ISSUE TITLE
Deadzones for sensors are too low

### ISSUE THREAD

**Issue by pepper-jelly** [AntiMicroX/antimicrox#1003]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

I've set accel. to switch weapons in RE2. It changes unintentionally in wrong moment.

### Expected Behavior

To be able to change deadzone for sensors up to 80.

### Steps To Reproduce

1. Click on accel or gyro.
2. You can't increase past 30 degrees.

### Environment

```markdown
*latest git build

Program Version 3.4.0
Program Compiled on Jul 2 2024 at 12:08:52
Built Against SDL 2.30.4
Running With SDL 2.30.4
Using Qt 5.15.14
Using Event Handler: XTest
Compositor type: x11
Host OS: artix Version: unknown Architecture: x86_64
```

### Anything else?

I think those two should be changed to 80.

https://github.com/AntiMicroX/antimicrox/blob/59296df97dd8949b1d6155558508df9d513b4f12/src/gui/joysensoreditdialog.ui#L374-L375

https://github.com/AntiMicroX/antimicrox/blob/59296df97dd8949b1d6155558508df9d513b4f12/src/gui/joysensoreditdialog.ui#L402-L403

**Comment by pktiuk** [comment]
Thank you for report and direct suggestion.   
This change seems to be a reasonable one.
