### ISSUE TITLE
.deb version does not have dark theme

### ISSUE THREAD

**Issue by rexendevar** [AntiMicroX/antimicrox#1009]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

the Flatpak version correctly inherits system dark theme, but the .deb version does not. Neither has any option anywhere for theming. This is on Gnome.

### Environment

```markdown
Flatpak version:

Program Version 3.4.0
Compiled from packaging: flatpak
Built Against SDL 2.28.5
Running With SDL 2.28.5
Using Qt 5.15.10
Using Event Handler: XTest
Compositor type: x11
Host OS: org.kde.Platform Version: 5.15-23.08 Architecture: x86_64

.deb version:

Program Version 3.4.0
Compiled from packaging: GitHub Release
Built Against SDL 2.0.20
Running With SDL 2.0.20
Using Qt 5.15.3
Using Event Handler: XTest
Compositor type: x11
Host OS: pop Version: 22.04 Architecture: x86_64
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1009">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1009/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1009/pledge.svg">
</picture>
</a>

**Comment by rexendevar** [comment]
On further review, I've discovered that even manually adding a theme setting to the config file does nothing. I attempted to check the config file for the flatpak version, but there is none, as far as I can see.

**Comment by pktiuk** [comment]
Could you [collect some logs](https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs) when this issue happens?

AntimicroX logs detected theme and informs about things like loaded icons.

**Comment by rexendevar** [comment]
[log for the .deb version](https://github.com/user-attachments/files/16319858/antix.log)
[log for the flatpak version](https://github.com/user-attachments/files/16319859/antimicrox.log)

**Comment by pktiuk** [comment]
In both cases package detects properly system theme (at least for icons).   
But in this case this seems to be an issue with host system and environment in general. (in your case POP OS)    
Some enviroments are configured properly (like flatpak sandboxes).

There was already similar issue in Pop OS repo: https://github.com/pop-os/iso/issues/30

Workaround can be found there: https://www.linuxuprising.com/2018/05/get-qt5-apps-to-use-native-gtk-style-in.html
