### ISSUE TITLE
Cmakefile fixes

### ISSUE THREAD

**Issue by gombosg** [AntiMicroX/antimicrox#102]
For #87 

- [x] Remove `list(APPEND CMAKE_PREFIX_PATH "/usr/lib/arm-linux-gnueabihf")` from cmakefile
- [x] Remove `LD_LIBRARY_PATH` hardcoding from cmakefile (probably after #99)

**Comment by pktiuk** [comment]
LD_LIBRARY_PATH - will be removed as a part of https://github.com/AntiMicroX/antimicrox/pull/107

**Comment by AriaMoradi** [comment]
> For #87
> 
> * [x]  Remove `list(APPEND CMAKE_PREFIX_PATH "/usr/lib/arm-linux-gnueabihf")` from cmakefile
> * [x]  Remove `LD_LIBRARY_PATH` hardcoding from cmakefile (probably after #99)

**Comment by AriaMoradi** [comment]
I missclicked.
Anyways the prefix is not needed, simlinks do exist to the correct cc, so calling by regular names is fine.
