### ISSUE TITLE
Horizontal mouse wheel is so fast when set on stick

### ISSUE THREAD

**Issue by CongTiankong** [AntiMicroX/antimicrox#1024]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

I tried to set 'wheel left' and 'wheel right' on stick left and right direction, it works but scroll speed is out of control. Tried to tweak 'wheel hori. speed' from 'mouse settings' but it has no effect.

Vertical wheel performs well on sticks and 'wheel vert. speed' has effect.
On d-pad both wheel performs well, 'wheel hori. speed' and 'wheel vert. speed' both has effect.

By the way, it seems 'wheel left' and 'wheel right' is inverted, is it a bug?

### Environment

```markdown
Program Version 3.4.0
Compiled from packaging: 3.4.0
Built Against SDL 2.30.3
Running With SDL 2.30.6
Using Qt 5.15.14
Using Event Handler: uinput
Compositor type: wayland
Host OS: arch Version: unknown Architecture: x86_64
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1024">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1024/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1024/pledge.svg">
</picture>
</a>

**Comment by sk2449** [comment]
I have observed this unexpected high horizontal scroll speed as well (v3.1.4 from Debian Sid repos on X11) when trying to translate gamepad inputs (Xbox One Controller) in a meaningful way to control video playback in mpv.
From mpv's verbose logs it looked like AntiMicroX is sending 10 WHEEL_RIGHT/WHEEL_LEFT events vs. 1 WHEEL_UP/WHEEL_DOWN event for the same horizontal/vertical stick movement, but i didn't find the time yet to analyze this further.
Anyone knows a convenient method to track the simulated input events? "--log-level debug" is very verbose and i struggled to isolate the relevant parts, when it comes to stick input, which is mapped to scroll events, while common tools like "xev" don't appear to capture the activities from AntiMicroX at all.
