### ISSUE TITLE
Remove HISTORY.md

### ISSUE THREAD

**Issue by gombosg** [AntiMicroX/antimicrox#103]
Git won't forget anyway.

**Comment by mirabilos** [comment]
Over 80% of the text (according to `git diff -C --find-copies-harder` anyway) are also present in `CHANGELOG.md`, so perhaps just merge the rest over there?

**Comment by gombosg** [comment]
Yes. HISTORY.md was the old changelog and the contents were migrated over to CHANGELOG.md when we started using an automated changelog generator. :)
