### ISSUE TITLE
AntiMicroX not detecting Z axis of Thrustmaster T.16000 stick

### ISSUE THREAD

**Issue by D4n2021** [AntiMicroX/antimicrox#1039]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

moving Z axis on the T.16000 (turning the stick left right) does not make anything light up in the GUI.

### Expected Behavior

There should be an entry "Z Axis" in the GUI when it detects the T.16000

### Steps To Reproduce

connect Thrustmaster T.16000, launch AntiMicroX, make sure the stick is properly recognized, then move the Z Axis.

### Environment

```markdown
Program Version 3.4.1
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.30.6
Running With SDL 2.30.6
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1039">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1039/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1039/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
Do you see this axis in the `Options->Properties` ?

![obraz](https://github.com/user-attachments/assets/10e47c13-246b-4c60-9548-8e1ff1ca5c56)

If not, then this is clearly an SDL issue out of scope of this repository.

**Comment by trimikix20** [comment]
hello i have the same issue and this is what i got option Properties
![issue1](https://github.com/user-attachments/assets/8f9a5ce0-44b4-4a4e-bc9d-4ebdf815aa05)

**Comment by trimikix20** [comment]
and that is the interface it show for my thrustmaster t.16000m 
![image](https://github.com/user-attachments/assets/0d0c4d45-97ce-4257-89f6-a4cd88482303)

**Comment by trimikix20** [comment]
How can I know wish one

**Comment by trimikix20** [comment]
this one 
![image](https://github.com/user-attachments/assets/c7d4c220-b34b-4fac-8453-361c8037615d)

**Comment by trimikix20** [comment]
and for the same controler i have a issue that the sofware doesn't detect the 5,8, 13,14,15  and the 4,6,9,7 they are considerate like trigger


![post-119325-0-34432800-1493505738](https://github.com/user-attachments/assets/20850813-86d4-4a2b-a886-6bbd28b8b8aa)

**Comment by pktiuk** [comment]
> hello i have the same issue and this is what i got option Properties ![issue1](https://private-user-images.githubusercontent.com/64111002/371889654-8f9a5ce0-44b4-4a4e-bc9d-4ebdf815aa05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MDM5OTcsIm5iZiI6MTcyNzcwMzY5NywicGF0aCI6Ii82NDExMTAwMi8zNzE4ODk2NTQtOGY5YTVjZTAtNDRiNC00YTRlLWJjOWQtNGViZGY4MTVhYTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEzNDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNWZkNDAxNDEwNDUzMTJlMTlhMzkzZDU3OGIzZmY0MjA2NzE1ODIzMTg3ZDgzYzhhZGJiNmUyMzc4N2UxZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TCKcE_f6a_F7OvcBq5Lx4RiuEULBRjMPoq7QPS5gtkI)

@trimikix20   

on the right you can see 6 Axes bars. They show raw linear inputs from your device (x,y,z,throttle etc). Does any of these bars seems to react strongly when you move in the Z axis?

**Comment by trimikix20** [comment]
No nothing just the x and y

**Comment by pktiuk** [comment]
Then it is a clearly an SDL issue. I think you should report it to SDL devs https://github.com/libsdl-org/SDL/ and link this issue in the description

**Comment by pktiuk** [comment]
Let me know when SDL will release a version with fix for this problem.

**Comment by Kieltux** [comment]
Seems to be a Windows only problem with SDL. 
AntiMicroX: 3.5.0
SDL 2.30.8
Qt 5.15.12
Host OS: opensuse-leap Version: 15.6 Architecture: x86_64

I get with Thrustmaster T.16000M 4 axes but all are working like expected.

![grafik](https://github.com/user-attachments/assets/aa0728a6-619e-4e7d-96d6-28cea85a76ac)

**Comment by trimikix20** [comment]
What do we have to do?

**Comment by pktiuk** [comment]
@trimikix20   
> What do we have to do?

Here? Nothing. Just let me know when SDL will fix this issue.     
Real work will be done on SDL side, so if you want to help you can ask in an SDL's issue: https://github.com/libsdl-org/SDL/issues/11008

Any new findings like the one from @Kieltux should also be posted there, not here. Because I am not an SDL developer.

**Comment by pktiuk** [comment]
I tgink it will be included in the next release of SDL.
