### ISSUE TITLE
Sort the configuration file so that small changes do not introduce a large diff

### ISSUE THREAD

**Issue by fuzzy7k** [AntiMicroX/antimicrox#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I would like to store my controller profile in git to introduce and track changes. The current save procedure introduces a large and not pertinent diff.

### Describe the solution you'd like

I'd like for a static file, where the only resulting diff is what has changed since last save. I would guess that the easiest way to do that would be to sort it before saving.

**Comment by fuzzy7k** [comment]
I apologize. I did not realize that this was your personal todo list. I thought this was more of a community project than than that. I put this here mostly for my todo list. 

But, this has zero to do with memory savings. It is about being able to use git to manage profiles. 
I consider that a valuable enhancement, and one that others might appreciate. If for nothing more than making the profile easier to navigate if it is being edited by hand. 

Would you accept a merge request if I fix this on my end?

**Comment by pktiuk** [comment]
If this merge request would be subtle and not break compatibility I would accept this

**Comment by pktiuk** [comment]
You can just start with simple Draft pull request showing how you sre going to achieve this
