### ISSUE TITLE
Profile reverts often to default

### ISSUE THREAD

**Issue by Jopp-gh** [AntiMicroX/antimicrox#1059]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Problem
I've a dozen of different gamepad profiles and switching profiles is rather difficult, because AntiMicroX often resets my selected game profile to default ("new"). 

This reset happens when I mouse click away / Ctrl+tab / change workspace (to my gaming workspace). It seems, no matter how do it, my selected game profiles  is reset multiple times. Only with luck, my game profile sticks to the selected game profile.

This bug affects both the tray menu and AntiMicroX's configuration window 

### Suggestion:
prevent keyboards (modifier keys like Ctrl, opt, super, shift, etc) and all controller buttons, especially controller axes to modify AntiMicroX's profile configuration (pop-up and checkbox buttons). 

Basically, only a mouse should be able to set controller profiles. 

### Steps To Reproduce

Steps:
1. select a custom profile from AntiMicroX's tray menu or select one from AntiMicroX's configuration window
2. Switch to the right game, related the selected profile
3. In game, the controller won't do anything (because AntiMicroX will reset your profile back to default, "new")
4. To fix this bug, I've to go back and forth multiple times to set my game profile. 

### Environment

```markdown
Program version 3.4.1
Compiled from packaging: 3.4.1-x86_64 GitHub AppImage Release
Using SDL 2.30.6
running with SDL 2.30.6
Uses Qt 5.12.8
using event handler: XTest
Compositor type: x11
Host OS: linuxmint Version: 21.3 Architecture: x86_64
```

### Anything else?

Meanwhile I learned how to setup auto-profiles, an awesome feature.
Still, this alternative doesn't resolve this bug report. 

My report seems to be a duplicate of #936, but I think, my description is more detailed so better to work with. 😉

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1059">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1059/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1059/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
Could you [collect some logs](https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs) when this issue happens?

I need to check what triggers this change in your case. Maybe this may be linked with misbehaving autoprofile.

**Comment by pktiuk** [comment]
From your logs you seem to have enabled auto-profiles which are used to switching profiles when selected window is changed. For auto profile this is expected behavior

**Comment by pktiuk** [comment]
If you report me a bug with profiles switching when auto-profiles are disabled, then provide me logs, when auto-profiles are disabled.
