### ISSUE TITLE
Remove qglobalshortcuts

### ISSUE THREAD

**Issue by gombosg** [AntiMicroX/antimicrox#106]
...and global quit shortcut selection in UI plus related code.

- only 1 small functionality tied to it (quit app shortcut - not really useful)
- unlicensed, see https://github.com/mitei/qglobalshortcut/issues/1
- allows doing #99 which is important for Debian packaging

**Comment by AriaMoradi** [comment]
Also i tested it and it didn't work, maybe i was doing it worng, but i never saw the debug message tied to it.

**Comment by AriaMoradi** [comment]
@pktiuk @gombosg
we are stuck in a dilemma, either
1- add the extra xcb dependency "explicitly" to our solution and ignore that `qglobalshortcut` is unlicensed. 
2- or, do a re-implementation of the "global quit shortcut" feature on our on
3- or, opt the code out until we get explicit permission from the original dev.

Just to mention, the feature was added by juliagoda not too long ago.

**Comment by AriaMoradi** [comment]
> @pktiuk @gombosg
> we are stuck in a dilemma, either
> 1- add the extra xcb dependency "explicitly" to our solution and ignore that `qglobalshortcut` is unlicensed.
> 2- or, do a re-implementation of the "global quit shortcut" feature on our on
> 3- or, opt the code out until we get explicit permission from the original dev.
> 
> Just to mention, the feature was added by juliagoda not too long ago.

I would choose the third option, adding a flag(macro) in cmake and minimal edition of `main` and `qglobalshortcut` will do the trick, and anyone that needs/uses the feature can turn it on on their build, still I don't know if it's lawful to ship the code but not incorporate it in the executable because the copyright low is nonexistent in my country :disappointed:

**Comment by AriaMoradi** [comment]
> Also i tested it and it didn't work, maybe i was doing it worng, but i never saw the debug message tied to it.

Someone should test building and running on a system that doesn't have `libxcb` installed, I'm sure things will breaking...

**Comment by gombosg** [comment]
Because #102 solves `antilib` issue, we can wait 1-2 days (I also sent an email to `qglobalshortcut` maintainer). But if there is no license, we should remove the feature. 

Using this kind of unlicensed stuff is not lawful at all as you say. Not because the Interpol will kick the door on us or the `qglobalshortcut` maintainer will sue us, but because distributions like Fedora, Debian, Flatpak store are picky about what they are distributing and it's not nice with them to leave unlicensed stuff inside packages.

The feature is even too small to have a compile flag to remember for it, but can be reintroduced later if we find a proper substitute for that library.

**Comment by gombosg** [comment]
> Also i tested it and it didn't work, maybe i was doing it worng, but i never saw the debug message tied to it.

There are multiple files to change here (`main.cpp`), options UI files etc.

**Comment by gombosg** [comment]
I'll do this on Friday if we don't get `qglobalshortcut` response till then.

**Comment by AriaMoradi** [comment]
> I'll do this on Friday if we don't get `qglobalshortcut` response till then.

Let's wait for 2 weeks, before we completely git rid of it, that's the standard grace time before a package is considered orphaned.

**Comment by gombosg** [comment]
Unfortunately we don't have that much time, because it's a prerequisite for Debian packaging, and [Debian stable freeze](https://release.debian.org/bullseye/freeze_policy.html) is in a month only.
So in the worst case, we remove it and simply revert the commit in case the maintainer responds later.

**Comment by pktiuk** [comment]
Proper removal of this functionality may be a bit tricky.  
Just look at this commit: https://github.com/AntiMicroX/antimicrox/commit/63fdb1f0f40169c4a2e246aed0326d13e14eaf43

**Comment by AriaMoradi** [comment]
> [63fdb1f](https://github.com/AntiMicroX/antimicrox/commit/63fdb1f0f40169c4a2e246aed0326d13e14eaf43)

wow! that must have taken a lot of time to make!

**Comment by pktiuk** [comment]
This function is hidden very deeply, I can't find a way to enable it.

**Comment by AriaMoradi** [comment]
> This function is hidden very deeply, I can't find a way to enable it.

enable what exacty?

**Comment by AriaMoradi** [comment]
how about making a WIP pull request together?

**Comment by pktiuk** [comment]
> > This function is hidden very deeply, I can't find a way to enable it.
> 
> enable what exacty?

I tried to enable shortcut quitting from app

> how about making a WIP pull request together?

I think it is a good idea, but I will have time on Friday to properly look at this.

**Comment by AriaMoradi** [comment]
> I tried to enable shortcut quitting from app

It's right there in Settings > General

**Comment by gombosg** [comment]
BTW we should try to remove as much dead code as possible (dead code is baaaaad :)), possibly `git revert`ing 63fdb1f.

**Comment by AriaMoradi** [comment]
> BTW we should try to remove as much dead code as possible (dead code is baaaaad :)), possibly `git revert`ing [63fdb1f](https://github.com/AntiMicroX/antimicrox/commit/63fdb1f0f40169c4a2e246aed0326d13e14eaf43).

I'm not too keen on that! Try adding your commits to the PR.

**Comment by pktiuk** [comment]
> > I tried to enable shortcut quitting from app
> 
> It's right there in Settings > General

It explains everything, I was looking for this option in `Settings -> mouse`, where it was placed firstly.

**Comment by gombosg** [comment]
First I tried to switch to a different library like https://github.com/Legotckoi/QGlobalShortcut/, but it didn't know everything needed. So I just ended up removing the feature altogether. I think this is not a useful feature - shortcuts for quitting the app? We have `Ctrl+Q` already.

BTW did you know that there are some key repeat settings in there, but it's [hidden](https://github.com/AntiMicroX/antimicroX/blob/302771c22623644fdbbfce114ac7a987c8ee85b3/src/mainsettingsdialog.cpp#L130-L130)? Created #115.

**Comment by pktiuk** [comment]
But `Ctrl+Q` doesn't seem to work, when AntiMicroX window is not active.

In this case I think it would be good to think about adding CLI command for closing antimicrox (https://github.com/juliagoda/antimicroX/issues/95), moreover parts of this mechanism (contracting with the previous instance of AntiMicroX from the newly opened one) will be useful here:  https://github.com/AntiMicroX/antimicrox/issues/91

**Comment by AriaMoradi** [comment]
> But `Ctrl+Q` doesn't seem to work, when AntiMicroX window is not active.
> 
> In this case I think it would be good to think about adding CLI command for closing antimicrox ([juliagoda/antimicroX#95](https://github.com/juliagoda/antimicroX/issues/95)), moreover parts of this mechanism (contracting with the previous instance of AntiMicroX from the newly opened one) will be useful here: #91

we could implement this with signals
