### ISSUE TITLE
Enable/Disable using gamepad

### ISSUE THREAD

**Issue by Ali229** [AntiMicroX/antimicrox#1073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Would like a way to toggle the program as enabled or disabled using the gamepad keys.

### Describe the solution you'd like

Select and start keys pressed together could be a toggle. or any user defined combination of buttons. So that when a fullscreen app or game is launched the program can be disabled using those keys.

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1073">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1073/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1073/pledge.svg">
</picture>
</a>

**Comment by Ali229** [comment]
![image](https://github.com/user-attachments/assets/8d4e648d-1f2d-4391-a619-2c39f8a518a7)
I'm trying what do these options mean? and how do I make the switch using a combo (Select+Start) to switch the set back and forth.

**Comment by pktiuk** [comment]
@Ali229     
There are no combos in AntiMicroX, you just map a single button to switching set.

1W - one way    
2W - two ways    
2WH - while holding

Just experiment with these options
