### ISSUE TITLE
improve menu

### ISSUE THREAD

**Issue by Fr-Dae** [AntiMicroX/antimicrox#1083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

hello, 
antimicroX 3.5.0
windows 10
Hotas saitek X52 Pro
![Capture](https://github.com/user-attachments/assets/5d1a918f-4793-4335-8839-bc94d8a85798)

### Describe the solution you'd like
the hotas have many axis ans button, 
would it be possible to : 
- display button/axis like on "X" 
- organise button, what are on Throttle , what are on base Throttle  (lcd screen / button) and what are on stick.

**Comment by Fr-Dae** [comment]
https://resource.logitech.com/content/dam/gaming/en/products/x52-pro-hotas/x52pro-gallery-1.png

**Comment by pktiuk** [comment]
You did not fill this part of the request:

> ## Describe the solution you'd like
> No response

**Comment by Fr-Dae** [comment]
in addition, a exemple 
![Capture](https://github.com/user-attachments/assets/204e1dc1-feb1-4982-a992-36db88f9181d)

**Comment by Fr-Dae** [comment]
here other exemple from old antimicro version readme
https://github.com/juliagoda/antimicroX/blob/master/other/appdata/screenshots/controller_main_window_dark_theme_1.png

the button are grouped in "bloc" to have a better view

**Comment by Fr-Dae** [comment]
https://youtu.be/qvwyFHX94Js
[antimicrox.log](https://github.com/user-attachments/files/17947715/antimicrox.log)
![Capture](https://github.com/user-attachments/assets/3a9600f3-4fe0-44b3-908e-11076bf2aee1)


Image for key relation
video to show what key i have tested.
because the log is very, very long

**Comment by pktiuk** [comment]
Apart from adding some kind of special button for one-dimensional axis I don't see any room for improvement which would be universal and require reimplementation of entire main window

**Comment by Fr-Dae** [comment]
would it be complicated to be able to move the buttons ui  yourself (user) to make groups, as proposed by joyviv and its fork?

**Comment by pktiuk** [comment]
Unluckily yes.    
It would require reimplementing the main window of the app and creating several new movable widgets and a way of saving these layouts.

**Comment by pktiuk** [comment]
Closing, because this would require too much effort.      
But the idea of separate widget for axes will be tracked here: https://github.com/AntiMicroX/antimicrox/issues/1108
