### ISSUE TITLE
azerty not supported ?

### ISSUE THREAD

**Issue by Fr-Dae** [AntiMicroX/antimicrox#1084]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

antimicrox 3.5.0
windows 10

at top, antimicro
at bottom, my keyboard.
![Capture](https://github.com/user-attachments/assets/40fab904-b94c-447e-a86b-b7da05354051)

### Environment

```markdown
Version 3.5.0
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.30.6
Fonctionne avec SDL 2.30.6
Utilise Qt 6.7.3
Utilise SendInput comme gestionnaire d'événement
Host OS: windows Version: 10 Architecture: x86_64
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1084">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1084/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1084/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
Nope, only QWERTY keyboard layout is showed in the assignment menu. But I find it just a minor inconvenience

**Comment by Fr-Dae** [comment]
"minor" qwerty keyboard have less key usable than azerty :/ 
why close the issue if it's not resolve ?
it's complicate to use `DIK Code` for auto assign layout ( azerty -fr azerty be, DE, and all other keyboard)

**Comment by Fr-Dae** [comment]
@pktiuk

**Comment by Fr-Dae** [comment]
hypotetique idea for use DIK code with QTKeyEvents
```properties
#include <QtCore/QCoreApplication>
#include <QtCore/QTimer>
#include <QtCore/QObject>
#include <QDebug>
#include <QKeyEvent>
#include <QWidget>

class KeyEventHandler : public QObject {
    Q_OBJECT

public:
    explicit KeyEventHandler(QObject* parent = nullptr)
        : QObject(parent) {}

signals:
    void keyPressed(int key);  // Signal émis lorsque une touche est pressée

public slots:
    void handleKeyEvent(QKeyEvent* event) {
        if (event->type() == QEvent::KeyPress) {
            emit keyPressed(event->key());  // Émettre le signal avec le code de la touche pressée
        }
    }
};

class MainWindow : public QWidget {
    Q_OBJECT

public:
    MainWindow(QWidget* parent = nullptr)
        : QWidget(parent), keyEventHandler(new KeyEventHandler(this)) {

        // Connecter le signal keyPressed à un slot dans MainWindow
        connect(keyEventHandler, &KeyEventHandler::keyPressed, this, &MainWindow::onKeyPressed);

        // Connecter l'événement clavier à la méthode handleKeyEvent
        installEventFilter(keyEventHandler);
    }

    ~MainWindow() {
        delete keyEventHandler;
    }

private slots:
    void onKeyPressed(int key) {
        // Traiter la touche pressée en fonction de son code
        qDebug() << "Touche pressée, code:" << key;

        // Exemple de traitement des touches
        switch (key) {
            case Qt::Key_A:
                qDebug() << "La touche A a été pressée";
                break;
            case Qt::Key_B:
                qDebug() << "La touche B a été pressée";
                break;
            default:
                qDebug() << "Autre touche pressée: " << key;
                break;
        }
    }

protected:
    bool event(QEvent* event) override {
        // Passer l'événement au filtre d'événements
        return QWidget::event(event);
    }

private:
    KeyEventHandler* keyEventHandler;
};

int main(int argc, char *argv[]) {
    QCoreApplication a(argc, argv);

    MainWindow window;
    window.show();

    return a.exec();
}

#include "main.moc"
```

**Comment by pktiuk** [comment]
> "minor" qwerty keyboard have less key usable than azerty :/

Then you can tell which buttons are missing and they can be placed in the list on the right side of assignment window.
