### ISSUE TITLE
[Linux] theming one GTK3  not supported

### ISSUE THREAD

**Issue by Fr-Dae** [AntiMicroX/antimicrox#1086]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

on LXDE desktop, i don't have "theme" like windows do (or lxqt ?)
could you support GTK theme and maybe have a button on setting "GTK/QT" like audacious do

### Environment

```markdown
- Lubuntu 22.04 LXDE
- Linux version 5.15.0-125-generic (buildd@lcy02-amd64-040) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU 2.38) #135-Ubuntu SMP 
- Antimicro 3.5.0
- QT 5.15.3
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1086">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1086/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1086/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
Theming of an app's GUI (button colors, background, text color) depends on environment in which an app runs.    
 To see properly themed AntiMicroX you can use either flatpak package or investigate how your system changes look of QT apps.

Linked issue tackling problem with icons theming https://github.com/AntiMicroX/antimicrox/issues/970

**Comment by Fr-Dae** [comment]
> Theming of an app's GUI (button colors, background, text color) depends on environment in which an app runs. To see properly themed AntiMicroX you can use either flatpak package or investigate how your system changes look of QT apps.
> 
> Linked issue tackling problem with icons theming #970

i don't use QT, it's LXDE (GTK3) here, i have disable QT everywhere because it's globally a piece of shit on ubuntu :/ (less shurtcut, some interface don't work, less settings, more ressources consumes)

**Comment by pktiuk** [comment]
You don't understand. You mix GUI frameworks (QT, GTK, Electron etc.) with Desktop Environments (which can be made using these frameworks KDE-QT, Gnome-GTK). GTK based DS can communicate and theme QT-based apps (and other way around).      
You use QT, because AntiMicroX is made using QT framework. 

If you don't like your system theming for QT apps you should start here:  
https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications

**Comment by Fr-Dae** [comment]
on lubuntu jsu jusqu'a la 18.10 etais fournis par defaut avec gtk2 et 3, (avec un abandon massif de gtk2 au profit de gtk3, 
Then all of a sudden, they imposed the use of QT by default, whether for the desktop and all application interfaces that had become ‘incompatible’, all people who are used to LXDE (and gtk) had to manually reinstall GTK and remove QT,

audacious has a QT and GTK mode, both of which are now trouble-free, ensuring full compatibility between shortcuts, the desktop, windows and the theme. 

That's what I'm asking for here, a button to use GTK natively on antimicrox WITHOUT using QT. 
So you can have the interface in a dark theme, harmonised with the rest of the system theme.

**Comment by pktiuk** [comment]
Nobody's going to rewrite entire app to use another framework just to tackle a nonexistent issue.    
In case of this app this is juat like asking about rewriting everything to C# because you don't like C++
