### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by Fr-Dae** [AntiMicroX/antimicrox#1087]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Expected Behavior

link to issue https://github.com/Fr-Dae/antimicrox/issues/1

### Environment

```markdown
.
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1087">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1087/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1087/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
This is not a bug and you did not even bother to describe your reasoning

**Comment by Fr-Dae** [comment]
@pktiuk

**Comment by Fr-Dae** [comment]
coudl you merge my pr before close this issue please ?, it's only to link for release update

**Comment by pktiuk** [comment]
No, I am not going to merge your PR

**Comment by Fr-Dae** [comment]
why ? i just improve the readme

**Comment by pktiuk** [comment]
Issues on GitHub are meant to categorize and discuss bugs and new features. Minor changes like updates to README or `.desktop` files can be submitted without any linked issue. This (almost empty) issue does not bring much value and doesn't contain any useful information for maintenance of this project.

**Comment by Fr-Dae** [comment]
I was taught to always link a pr to an exit to make it easier to follow, and I apply this rule, but okay.

**Comment by pktiuk** [comment]
> I was taught to always link a pr to an exit to make it easier to follow, and I apply this rule, but okay.

This is a good practise, but in case of implementing features or fixing bugs with existing reports. In situations like: minor fixes in docs, minor refactors or cleanups creating issue is not necessary.
