### ISSUE TITLE
Foot pedals are each recognized as 3 joysticks.

### ISSUE THREAD

**Issue by Ponhoka** [AntiMicroX/antimicrox#1101]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Footpedals models are PCsensor's FS-23P_v4.7 and FS2020U1IR_v4.7, both are 3-pedal USB devices. Set with footSwitch-7.4.3 software to behave as 3-button controllers.
![image](https://github.com/user-attachments/assets/3041cc31-0e04-4b0a-92d0-e52de8cc48b8)
 On AntiMicroX, they are each recognized as three separate Joysticks, but only one of these Joysticks contains the three buttons of the pedals. As an example, in the image below, FootSwitch (Joystick 6-8) seem to be all FS2020U1IR, but only Joystick 8 has the buttons. The numbers vary, but it is always three consecutive numbers/Joysticks for each pedal.
![image](https://github.com/user-attachments/assets/c28f8b6c-b656-48c4-989c-2fb8c65c2b9e)
Here are the contents of each Joystick. These three Joysticks are the same for both models, the order is always the same 1->2/3->4. 1 is the first Joystick, always empty. 2 and 3 are the same Joystick, which has 256 buttons, with some of these buttons being constantly pressed(3), sometimes not. 4 is the last Joystick, it has the three buttons for each pedal and can be configured as a regular controller. Setting "Auto Load Last Opened Profile" crashes AntiMicroX, as it loads a profile on 1, the first Joystick, which is empty. This occurs by loading a profile on 1 manually as well.
![image](https://github.com/user-attachments/assets/1be63b21-2842-44b7-937d-9f863d30fa2b)

### Expected Behavior

Expected behavior is a single Joystick for each pedal, only the third Joystick(4). Autoload profile is expected to not crash, by loading into this singular Joystick that can set the buttons just like a regular controller, instead of loading into 1.

### Steps To Reproduce

1. Connect the pedals to USB ports.
2. Configure them as controllers in the footSwitch-7.4.3 software, by choosing the correct model on the left and setting each pedal as a button with the "Game" tab on the right. Save to key.
3. Open up AntiMicroX.
4. Check that each pedal corresponds to three Joysticks, in order.
5. Check the Joysticks, if the first one is empty, the second has lots of buttons, and if the last one can be configured normally.
6. Test the last one, should function properly.
7. Try adding a profile, or let Autoload do it, to the first Joystick of a pedal. It should crash.

### Environment

```markdown
Program Version 3.4.1
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.30.6
Running With SDL 2.30.6
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

### Anything else?

https://pcsensor.cn/Foot-Switch?product_category=157, this is the site of the pedal manufacturer.
https://pcsensor.cn/software-details?article_id=139 this is the page with FootSwitch software.
[partoflog_footswitch_antimicrox.txt](https://github.com/user-attachments/files/17921589/partoflog_footswitch_antimicrox.txt) is a part of the log that might be relevant, I restarted AntimicroX with only one footpedal.
I have used AntiMicroX with multiple controllers and versions of AntiMicroX, but this problem of multiple Joysticks per device seems to be just with these pedals, excluding emulating already identified controllers as Xinput (WiiUPro to Xbox with WiinUSoft), which is actually expected behavior.
Tested the same steps on 3.5.0 and the issue persists.
Cheers!

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1101">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1101/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1101/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
This seems to be an issue caused by the [SDL](https://github.com/libsdl-org/SDL/) (underlying library used as an interface with controllers).

You can try to directly check your controller using other apps using SLD like `sdl-jstest`, [SDL2 Gamepad Tool](https://www.generalarcade.com/gamepadtool/) to check whether it reports the same number of devices as AntiMicroX. If also that app has the same problems as AntiMicroX then you should just report problem with your device to the SDL's developers

**Comment by pktiuk** [comment]
@Ponhoka 

I think that this part of your log would be interesting for SDL developers.

```
[12:05:50.479] 🟢INFO	Created new Joystick:
			Index:            1
			  UniqueID:         0300f5a6861a000026e0000000000000679057382
			  GUID:             0300f5a6861a000026e0000000000000
			  VendorID:         6790
			  ProductID:        57382
			  Serial:           
			  Product Version:  0
			  Name:             FootSwitch
			  Game Controller: No
			  # of Axes:       0
			  # of Buttons:    0
			  # of Hats:       0
			  Accelerometer:   0
			  Gyroscope:       0
			 (file /src/joystick.cpp:44)


--

[12:05:53.687] 🟢INFO	Created new Joystick:
			Index:            2
			  UniqueID:         0300f5a6861a000026e0000000000000679057382
			  GUID:             0300f5a6861a000026e0000000000000
			  VendorID:         6790
			  ProductID:        57382
			  Serial:           
			  Product Version:  0
			  Name:             FootSwitch
			  Game Controller: No
			  # of Axes:       0
			  # of Buttons:    256
			  # of Hats:       0
			  Accelerometer:   0
			  Gyroscope:       0
			 (file /src/joystick.cpp:44)


--

[12:05:53.809] 🟢INFO	Created new Joystick:
			Index:            3
			  UniqueID:         0300f5a6861a000026e0000000000000679057382
			  GUID:             0300f5a6861a000026e0000000000000
			  VendorID:         6790
			  ProductID:        57382
			  Serial:           
			  Product Version:  0
			  Name:             FootSwitch
			  Game Controller: No
			  # of Axes:       2
			  # of Buttons:    8
			  # of Hats:       0
			  Accelerometer:   0
			  Gyroscope:       0
			 (file /src/joystick.cpp:44)
```
