### ISSUE TITLE
L-Tek Dance Pad PRO - "Up" not detected

### ISSUE THREAD

**Issue by GrahamBlanshard** [AntiMicroX/antimicrox#1103]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Pressing the "Up" direction on the dancepad is not detected within the AntiMicroX UI and cannot be assigned a key. 

The DEBUG log however does detect the input, visible with lines that look similar to this:

```
[20:30:41.835] \U0001f41eDEBUG	Processing event: SDL_CONTROLLERBUTTONUP From joystick with instance id: 0 Got button with id: 2 is one of the GameControllers: true is one of the joysticks:false (file /src/inputdaemon.cpp:703)
[20:30:41.835] \U0001f41eDEBUG	Processing event: SDL_JOYBUTTONUP From joystick with instance id: 0 Got button with id: 3 is one of the GameControllers: true is one of the joysticks:false (file /src/inputdaemon.cpp:703)
[20:30:41.835] \U0001f41eDEBUG	Processing JoyButton::joyEvent for: X: [NO KEY] SDL index: 2 className: JoyButton (file /src/joybuttontypes/joybutton.cpp:179)
```

### Expected Behavior

Pressing "Up" on the dancepad registers Button "4"

### Steps To Reproduce

1. Connect DancePad
2. Launch AntiMicroX from Terminal
3. View "Properties" on UI
4. Press "Up" key and observe the UI does not detect input (but terminal behind does)

### Environment

```markdown
Program Version 3.5.0
Program Compiled on Nov 30 2024 at 20:16:24
Built Against SDL 2.30.0
Running With SDL 2.30.0
Using Qt 6.4.2
Using Event Handler: XTest
Compositor type: x11
Host OS: linuxmint Version: 22 Architecture: x86_64
```

### Anything else?

- jstest detects the inputs just fine
- Project OutFox detects the inputs fine as well
- Not sure if its relevant, but `/dev/input/by-id/` lists two entries for the dancepad:
`
lrwxrwxrwx 1 root root   9 Nov 30 20:06 usb-www.l-tek.pl_L-TEK_Dance_Pad_PRO_00...01-event-joystick -> ../event3
lrwxrwxrwx 1 root root   6 Nov 30 20:06 usb-www.l-tek.pl_L-TEK_Dance_Pad_PRO_00...01-joystick -> ../js0
`
...If i try to `chmod 000` the event3 entry AntiMicroX fails to detect anything on launch. But jstest is run against js0 so I'm guessing there's a conflict somehow?

I'm willing to provide further information if required.

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1103">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1103/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1103/pledge.svg">
</picture>
</a>

**Comment by GrahamBlanshard** [comment]
Well shoot. Why do I spend an hour and a half on something, then find the fix immediately after submitting the bug.

Resolution was to open the _Controller Mapping_ and remap the controller buttons there, then repeat the Properties test.

I imagine my thrashing about in the original Debian 3.1.4 install a few days ago caused a stale config that should've been wiped clean before trying this fresh.

**Comment by pktiuk** [comment]
> Well shoot. Why do I spend an hour and a half on something, then find the fix immediately after submitting the bug.

You are not alone. ;)
