### ISSUE TITLE
Wrong install dependencies on a Debian build with QT6 (works with QT5)

### ISSUE THREAD

**Issue by oe4dns** [AntiMicroX/antimicrox#1104]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Building antimicrox on Debian works as expected when following the official build instructions.

Installing the .deb after building with QT6 fails. The reason is, apt wants to install "libqt6widgets6t64" as a dependency. This is a rather uncommon package and only available in Debian Unstable for the m68k architecture! Removing this dependency from the .deb results in an installable and working programm.

Building with QT5 works and installs as expected. It depends on libqt5widgets which is common and not unexpected at all.

My suspicion is, the libqt6widgets6t64 dependency should in fact be changed to libqt6widgets.

### Environment

```markdown
Program Version 3.5.0

Raspberry Pi OS "bookworm" (Debian Stable) on a Raspberry Pi 4
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1104">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1104/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1104/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
> My suspicion is, the libqt6widgets6t64 dependency should in fact be changed to libqt6widgets.

This may be a good idea. I will check it out

**Comment by pktiuk** [comment]
According to package registries in Ubuntu repos there is a package [`libqt6widgets6t64`](https://ubuntu.pkgs.org/24.04/ubuntu-universe-amd64/libqt6widgets6t64_6.4.2+dfsg-21.1build5_amd64.deb.html) which replaces package [`libqt6widgets6`](https://debian.pkgs.org/12/debian-main-amd64/libqt6widgets6_6.4.2+dfsg-10_amd64.deb.html) which exists in Debian repos.

**Comment by qyot27** [comment]
> According to package registries in Ubuntu repos there is a package [libqt6widgets6t64](https://ubuntu.pkgs.org/24.04/ubuntu-universe-amd64/libqt6widgets6t64_6.4.2+dfsg-21.1build5_amd64.deb.html) which replaces package [libqt6widgets6](https://debian.pkgs.org/12/debian-main-amd64/libqt6widgets6_6.4.2+dfsg-10_amd64.deb.html) which exists in Debian repos.

https://packages.ubuntu.com/search?keywords=libqt6widgets&searchon=names&suite=all&section=all

It only exists with that name in 24.04; presumably the ones in 24.10 and Plucky use 64-bit time but simply reverted back to the old package name.

The topic page on the Debian Wiki is here:
https://wiki.debian.org/ReleaseGoals/64bit-time

It remains to be seen how Debian is going to handle this (or *did* handle this, considering Ubuntu is branched off of sid, so the different naming in 24.04 could well have come from Debian temporarily altering the name of the package during the transition) when it comes to package naming in the next stable version.
