### ISSUE TITLE
Joystick not supported (Padix Co. Ltd. PSX/USB converter)

### ISSUE THREAD

**Issue by Robository** [AntiMicroX/antimicrox#113]
Hello! I using my old psx1 controler with a psx usb converter.

onepad: Joystick (Padix Co. Ltd. PSX/USB converter ,GUID:03000000830500005f20000010010000) isn't yet supported by the SDL2 game controller API
Fortunately you can use AntiMicro (https://github.com/AntiMicro/antimicro) or Steam to configure your joystick
The mapping can be stored in OnePAD2.ini as 'SDL2 = <...mapping description...>'
Please report it to us (https://github.com/PCSX2/pcsx2/issues) so we can add your joystick to our internal database.

**Comment by gombosg** [comment]
Hi!
Can you clarify please? I can't exactly see context here.

- What is the issue?
- What would you like to report to us?
- How can we possibly fix it?

**Comment by AriaMoradi** [comment]
As said in the message you should report this to https://github.com/PCSX2/pcsx2/issues
here's a similar issue: https://github.com/PCSX2/pcsx2/issues/3329

**Comment by offalynne** [comment]
@Robository can you author a mapping with the tool linked here, please ? https://github.com/gabomdq/SDL_GameControllerDB
