### ISSUE TITLE
Integrate additional quality checks/linters/etc to repository.

### ISSUE THREAD

**Issue by pktiuk** [AntiMicroX/antimicrox#114]
I think it would make ensuring proper quality of our code easier.

It would be great if we would find also something what would help with tracking unused variables, libraries, unused elements of UI etc. (It would greatly help to hunt down unused code).

LIst of tools to check:
- Cmake
  - [ ] https://cmake-format.readthedocs.io/en/latest/cmake-lint.html
  - [ ] https://pypi.org/project/polysquare-cmake-linter/
  - [ ] https://pypi.org/project/cmakelint/
- C++
  - [ ] clang-tidy, scan-build
  - [ ] clazy
  - [ ] Cppcheck
  - [ ] https://www.sonarqube.org/
  - [ ] https://sonarcloud.io/
  - [x] #287
  - [x] #289

**Comment by AriaMoradi** [comment]
> It would be great if we would find also something what would help with tracking unused variables, libraries, unused elements of UI etc. (It would greatly help to hunt down unused code).

Probably some kind of tools exists that marks which parts of the code was executed and generates some kind of coverage report.  I think visual studio has one...

**Comment by pktiuk** [comment]
We have time.

**Comment by pktiuk** [comment]
I tried sonarcloud with fork of this repo https://sonarcloud.io/dashboard?id=testorgAntimictox_antimicrox

I think it could be an interesting lecture, but unluckily a big one.

![obraz](https://user-images.githubusercontent.com/45544416/127041966-a7472534-2fba-4efa-9b08-f78ffc8f114a.png)

**Comment by avinal** [comment]
I have looked into the options and I think we only need only a few types of code inspection/analysis tools. 
- A static code analyzer
- A code format check
- DCO check(we should add it as a good open-source practice)
- Code Coverage check

**Comment by pktiuk** [comment]
>     * A static code analyzer

I think this one would be very useful

>     * A code format check

We have already implemented code formatting check.

>     * DCO check(we should add it as a good open-source practice)
>
>     * Code Coverage check

We don't have any tests, so code coverage would be pointless

**Comment by avinal** [comment]
What about a DCO check?

**Comment by pktiuk** [comment]
> What about a DCO check?

TBH

I don't think we need it.

**Comment by avinal** [comment]
I am going for CodeQl and infer. They seem simple yet effective and not very hard on CI either.

**Comment by pktiuk** [comment]
I think current tools are enough for now.
