### ISSUE TITLE
Clear shortcut not working

### ISSUE THREAD

**Issue by gombosg** [AntiMicroX/antimicrox#116]
**Describe the bug**
You can set a key to NONE in the setting dialog, but right-click - clear is not working.

**Configuration**
Present in master and 3.1.3

**Comment by AriaMoradi** [comment]
more context please?

**Comment by gombosg** [comment]
![image](https://user-images.githubusercontent.com/23086060/101161417-f57ef380-3630-11eb-8c19-0f2e01034ddd.png)
