### ISSUE TITLE
Update AUR Github Repo

### ISSUE THREAD

**Issue by trymeouteh** [AntiMicroX/antimicrox#12]
I do not have Arch installed right now but I looked on the AUR and it shows the two packages for AntimicroX still use the old github repo and not the new repo. One or both of these should be updated for Arch Users.

https://aur.archlinux.org/packages/?O=0&K=antimicrox

**Comment by pktiuk** [comment]
This is strange, that there are two packages for antimircoX.

We don't work directly with package maintainers, they do deal with maintaining on their own, we don't contact directly (but we would gladly accept them in our team).

Both of these packages are 3.0.1, it is the latest one from legacy repo, it means, these maintainers are up to date, and they will probably update link to repository with new release shipped here, so don't worry about it.

**Comment by OlegPopow** [comment]
> This is strange, that there are two packages for antimircoX.

What's strange about it that there are two packages? One PKGBUILD uses a tagged version, the other builds the latest possible commit.  



> Both of these packages are 3.0.1, it is the latest one from legacy repo

No. One of them uses version 3.0-1 which does not mean that he builds version 3.0.1, because then there would be version number 3.0.1-1. 



> it means, these maintainers are up to date, and they will probably update link to repository with new release shipped here, so don't worry about it.

Doubtful, because the parcels were reported for removal due to abandonment of the project. Apparently nobody realized that you are continuing the project. So it will probably be removed if you don't notify the maintainers that AntimicroX will be further developed.

**Comment by pktiuk** [comment]
> One PKGBUILD uses a tagged version, the other builds the latest possible commit.

I was not aware about such practices (I am not familiar with arch).

> Apparently nobody realized that you are continuing the project.

They are notified in comments below package descriptions.
Moreover, I know, that at least one of them knows about this fork.

**Comment by OlegPopow** [comment]
> I was not aware about such practices (I am not familiar with arch).

So you spoke on a topic where you have no idea :) ? Of course, you had the right to make a mistake, nobody blames you for it.



> Moreover, I know, that at least one of them knows about this fork.

In that case, I am surprised that he did not update the sources. Perhaps we need to be patient.

**Comment by trymeouteh** [comment]
I hope these package maintainers on the AUR update to the new github repo.

**Comment by OlegPopow** [comment]
> I hope these package maintainers on the AUR update to the new github repo.

As I said before, these packages will probably be removed, as the relevant applications have been submitted to the AUR mailing list. It seems that in one case such a request was sent by the maintainer himself, but in my free time I have to check it.

**Comment by pktiuk** [comment]
I have noticed, that arch packages listed [here](https://aur.archlinux.org/packages/?O=0&K=antimicrox) have updated links now.

I think this issue can be closed now.

**Comment by emericg** [comment]
I've been using this AUR package for some time, it works well and is updated in a timely manner. They both have the new url now.

**Comment by pktiuk** [comment]
Both of them have updated links, moreover one of them has already published the latest release.
