### ISSUE TITLE
Unable to install deb package built on Raspberry Pi

### ISSUE THREAD

**Issue by pktiuk** [AntiMicroX/antimicrox#121]
**Describe the bug**
Unable to install deb package built on Raspberry Pi
```
CPack: Create package
CPack: - package: /home/pi/antimicrox/build/antimicrox-3.1.3-armv7l.deb generated.
pi@raspberrypi:~/antimicrox/build $ sudo apt install ./antimicrox-3.1.3-armv7l.deb 
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /home/pi/antimicrox/build/antimicrox-3.1.3-armv7l.deb
E: The package lists or status file could not be parsed or opened.
```

**To Reproduce**
Build deb packages on Raspberry Pi using instructions from BUILING.md

**Configuration**
Raspberry Pi 4  
Raspberry OS 32bit

**Comment by AriaMoradi** [comment]
And also I couldn't `make uninstall` either...

**Comment by AriaMoradi** [comment]
Does `master` work?

**Comment by gombosg** [comment]
Looks like some packaging issue, not compilation error.

**Comment by mirabilos** [comment]
These `.deb` binary packages do not conform _at all_ to the standards required by Debian; it’s no surprise they fail.

Since there are proper Debian packages now, it might be wise to consider abandoning them.

**Comment by pktiuk** [comment]
Do you mean packages built using [CPackDeb](https://cmake.org/cmake/help/v3.10/module/CPackDeb.html) are not compatible with Debian or you think we did something wrong with configuring it?

**Comment by mirabilos** [comment]
It begins at the filename, continues with the architecture names, and apparently ends at the metadata.

Not worth bothering IMHO.

**Comment by mirabilos** [comment]
On https://packages.debian.org/buster-backports/antimicro you can get the Debian package for `buster` for `armel` (RPi 1), `armhf` (RPi 2 1.0; Raspbian) and `arm64` (RPi 2 1.2, RPi 3 and 4), or just install using `apt-get -t buster-backports install antimicro` if you’ve set up the Debian repository.

The package is also available in `bullseye`.
