### ISSUE TITLE
[Linux] Load save dialogue window won't show saved configs = can't open saves

### ISSUE THREAD

**Issue by pipoliviero** [AntiMicroX/antimicrox#123]
**Describe the bug**
The open saved config dialogue window will not show any of the config files, and therefore I cannot save any controls.
I assume it's forcing the dialogue window to only look for some other config file format and not the acual one used for AntiMicroX.

**To Reproduce**
Save a configuration to disk, restart, configuration no longer shows up in selection window.
**Expected behavior**
Config files show in the config file selection dialogue window

**Screenshots**
![image](https://user-images.githubusercontent.com/10493036/102356051-a1ff9480-3fa4-11eb-8577-e45ae9b65fe0.png)

Dialogue window filtering for config files
![image](https://user-images.githubusercontent.com/10493036/102356538-3f5ac880-3fa5-11eb-8f66-4cc950b07231.png)

And it's not because hidden files are hidden either. 
![image](https://user-images.githubusercontent.com/10493036/102355888-61a01680-3fa4-11eb-8695-815fe7cfa8c6.png)

**Configuration**
Version of antimicrox: 3.1.3
Used package: Flatpak
System version: Pop_OS! 20.10
Controller: Xbox One third gen

**Comment by pktiuk** [comment]
For reporting bugs please use proper issue template.

**Comment by pktiuk** [comment]
@pipoliviero 
In my case for flatpak after clicking load
![image](https://user-images.githubusercontent.com/45544416/102391005-6c26d400-3fd5-11eb-813a-7c32255286fa.png)

I am still able to see and open files not only in `amgp` format
![image](https://user-images.githubusercontent.com/45544416/102391153-9bd5dc00-3fd5-11eb-929a-6e31a9bd5a77.png)

Maybe it can be caused by flatpak  permissions.

**Comment by pipoliviero** [comment]
Sorry, when I hit submit it seemingly skipped the format page so I assumed there was no format.

So the left file is what is generated by AntiMicroX on save, which I'm sure is not a correct file as the string of letters after ".amgp-" is always random and nothing proceeds it.
![image](https://user-images.githubusercontent.com/10493036/102391825-231f5180-3fce-11eb-8b7f-47f83a173b2f.png)

To be clear I don't actually know what file format is correct here so I tried deleting everything after ".gamecontroller." (right side file) and that didn't work either.

To be clear I never had flatpaks or installed flatpak, a recent Pop_OS! update added it so I never touched it.

**Comment by pipoliviero** [comment]
example 
![image](https://user-images.githubusercontent.com/10493036/102392570-2535e000-3fcf-11eb-85dc-417ca5c9fc0b.png)

**Comment by pktiuk** [comment]
There are two correct formats of files amgp and xml

Are these default saved files or you saved them using "Save as"?

**Comment by pipoliviero** [comment]
Either or give the same result. Named.
![image](https://user-images.githubusercontent.com/10493036/102393404-392e1180-3fd0-11eb-9405-a31530d394ed.png)

**Comment by pipoliviero** [comment]
It seems that removing the "-XXXXXX" after ".amgp" lets you load the file but every time I make a new file it just does the random string of letters thing again.

**Comment by pktiuk** [comment]
Very interesting, I am not able to reproduce it on my Ubuntu 20.04, later I will try to install Pop_os on VM and check it once more.  
For now, you can just remove this part after `amgp`  and everything should just work fine.   (you figured it out when I was typing :D )

@AntiMicroX/members  
BTW Maybe we should think about saving config files in default location (for example next to settings file) to make configuration easier and more predictable.

**Comment by Actuatedgear** [comment]
I'd like to ring in on this. I had a run-in with the flatpak version and had similar problems. AntiMicroX as I found it in Software Manager would not under any circumstances save and when I attempted to set the Profile location it opened to my home folder... which was empty. I couldn't make heads or tails of it. I also couldn't get the man page to load, nor could I run the program via terminal and thus nor could I run --help. Antimicro, by contrast which is also listed, works fine, though the interface is ever so slightly less polished. It's basically the same program, but everything works. I have no idea what's going on.

**Comment by pktiuk** [comment]
> I attempted to set the Profile location it opened to my home folder... which was empty.

This seems to be caused not by AntiMicroX, but by flatpak packaging. In case of traditional packages this issue doesn't exist.

> I also couldn't get the man page to load, nor could I run the program via terminal and thus nor could I run --help

This is also caused by flatpak, because flatpak packages are launched by other command: `flatpak run  antimicrox --help`

**Comment by Mytruepower2** [comment]
I was able to work around this issue by saving a controller configuration, then navigating to it using (in my case,) the Pop_OS GUI and renaming the extension manually to remove the numbers at the end, so that the file ended with ".amgp".  Then AntiMicroX allowed me to load the configuration I'd created with the "load" button.  
Not the most efficient solution, perhaps, but at least now, I don't need to keep creating a new configuration every time I want to play.

**Comment by pktiuk** [comment]
I think https://github.com/flathub/io.github.antimicrox.antimicrox/pull/7 should fix this.

@Mytruepower2 @pipoliviero @Actuatedgear 

Is this issue fixed?

**Comment by pktiuk** [comment]
Closing due to lack of feedback
