### ISSUE TITLE
Hi, my profile antimicro is set to new everytime im clicking on google page or any application

### ISSUE THREAD

**Issue by AsKaiiiSeR** [AntiMicroX/antimicrox#131]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Configuration**
Version of antimicrox: 
Used package: 
System version:

**Additional context**

**Comment by gombosg** [comment]
Hi, please fill the bug report template properly with a proper, reproducible issue description.

**Comment by AsKaiiiSeR** [comment]
Hi, i have resolved the problem i had antimicro for 32 bits and i needed for the x86.
