### ISSUE TITLE
Windows installer coming?

### ISSUE THREAD

**Issue by Zacharybinx34** [AntiMicroX/antimicrox#150]
Would love to get this on windows! Any progress being done towards that? 

Thanks!

**Comment by gombosg** [comment]
Hi, [I started working on it](https://github.com/AntiMicroX/antimicrox/tree/windows_build), but at the moment I have nearly zero free time for this.

**Comment by pktiuk** [comment]
Restoring windows support can be tracked here: https://github.com/AntiMicroX/antimicrox/issues/4
