### ISSUE TITLE
Add a configuration for Azeron Gamepad

### ISSUE THREAD

**Issue by FolderHyph** [AntiMicroX/antimicrox#160]
Hello,

It would be nice to add special configuration setting for the Azeron GamePad.

**Comment by pktiuk** [comment]
HI @FolderHyph ,
Unluckily I don't have access to this controller, so I am not able to investigate this device.
Moreover, this seems to be not a very popular gamepad, so we don't think it would be worth investing time into this device.

**Comment by FolderHyph** [comment]
Hi @pktiuk ,
That device is going to became very popular and there's a lot of people migrating from windows to Linux for gaming. Also, you should know that people from Azeron directly suggested antimicrox over Discord. Well, I have the device, if you think that I can help you out and we can develop that interface it will be huge and antimicrox will be the only one to have this feature on Linux. Also because the same Azeron software only runs on Windows and doesn't work with Wine. If you change your mind let me know, I'll be glad to collaborate on this.
