### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by stemy2** [AntiMicroX/antimicrox#161]
**Describe the bug**
The software crashes immediately after being started.

**To Reproduce**

1. Try to launch the software.

**Screenshots**

**Configuration**
Version of antimicrox: 3.1.5
Used package: deb
System version: debian stable

**Additional context**
Console output
```
antimicrox: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by antimicrox)
antimicrox: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by antimicrox)
```
None of them are present in my repositories.

**Comment by pktiuk** [comment]
Have you installed it using apt, or you have downloaded deb from release site?

**Comment by pktiuk** [comment]
This is probably caused by Ubuntu version used for building packages.   
- Ubuntu 16.04 - 5.5.1
- Ubuntu 18.04  - 5.9.5
- Ubuntu 20.04 - 5.12.8

What is qt5 version available on your system?

**Comment by stemy2** [comment]
> What is qt5 version available on your system?

I don't know, where do i find a such information ?

**Comment by pktiuk** [comment]
`apt show qt5-default`

**Comment by stemy2** [comment]
5.11.3

**Comment by pktiuk** [comment]
Could you check how this version works for you?  
https://github.com/pktiuk/antimicrox/releases/tag/3.1.5-ubuntu18

**Comment by stemy2** [comment]
I just installed the flatpak version, and it works, so i can consider my problem as resolved.
