### ISSUE TITLE
[Request] Ability for controller 1 to change the button setup for controller 2

### ISSUE THREAD

**Issue by NintendoManiac64** [AntiMicroX/antimicrox#164]
First off, I'm aware that adding of any new functionality isn't quite on the table just yet, so this is more of documenting something for the future.

Sometime within the last 15 years I've been using JoyToKey, it seems that it added the ability to set a controller button to change a profile.  But unlike AntiMicroX which uses per-controller profiles, JoyToKey uses profiles that include all of the active controllers, meaning controller 1 can effectively be used to change the mapping on controller 2 (or controller 2 to change the mapping of controller 3, controller 3 to change the mapping of controller 4, etc etc).

Initially I thought that this was something that AntiMicroX supported via its "change set" function as well as the "change profile" function, but unfortunately it seems that AntiMicroX's sets as well as profiles are all per-controller.  This means that, if you use the function to change a set or a profile when you press a given button, it only ever changes the configuration for your current controller and nothing else.

The main reason I want this function is because I've realized that this function could be used to turn some single-player game modes into a back-and-forth co-op multiplayer (or cycling of turns with more than 2 people).

Though as I typed this, I also realized that such a function could be incredibly useful for basically letting you use a second controller as an easy way to change your primary controller's configuration for whatever reason in a "hot key" kind of way, like maybe for different parts of a given game or even different games altogether.

**Comment by pktiuk** [comment]
Allowing interactions between controllers would make code too messy, but I think you may find https://github.com/AntiMicroX/antimicrox/issues/304 interesting, because (when finished) you will be able to run command changing set of gamepad using another device
