### ISSUE TITLE
Is there a way to change walking speed with joystick but with more than 2 speeds? 

### ISSUE THREAD

**Issue by Simao-Santos** [AntiMicroX/antimicrox#165]
**Question**
I was having trouble with the precious edition of antimicro because I have the game in Windows. But I was thinking that maybe here someone could know how to do what I mean. 

The game is Splinter Cell: Chaos Theory, and the character has various speed it can walk. 

If it was only walk and run, it could be achieved with the "distance" tag, but since they are 4 different speeds I don't know how, since it isn't possible to have multiple "distance" tags.

**Comment by vguttmann** [comment]
I'm not completely sure if you're aware of this, but you commented on the issues page of AntiMicroX, a fork of antimicro. Antimicro is no longer maintained, and AntiMicroX aims to replace it, however, AntiMicroX does not yet have a working windows build. 

I'm not sure it is possible to do what you want to do currently in AntiMicroX, and I'm not sure how easy it would be to implement this. And, even when we get it to work, we do still need to figure out a way to build AntiMicroX for windows, so unfortunately, I don't think that this will be possible in the near future.

**Comment by Simao-Santos** [comment]
> I'm not completely sure if you're aware of this, but you commented on the issues page of AntiMicroX, a fork of antimicro. Antimicro is no longer maintained, and AntiMicroX aims to replace it, however, AntiMicroX does not yet have a working windows build.

Yeah I know I know. I was asking in case that function was available but I just didn't know how to work it. I didn't ask in the original repo because it's no longer maintained.

> I'm not sure it is possible to do what you want to do currently in AntiMicroX, and I'm not sure how easy it would be to implement this. And, even when we get it to work, we do still need to figure out a way to build AntiMicroX for windows, so unfortunately, I don't think that this will be possible in the near future.

Yeah I'm aware of the windows build situation. Oh well worth asking, thanks for the answer :)

**Comment by Simao-Santos** [comment]
Now that I've been answered, maybe I should change to a feature request, in case there isn't already this feature requested.

**Comment by vguttmann** [comment]
I don't think that this is a current feature, and you are obviously free and welcome to change this to a feature request. However, since this is a relatively new project, and the maintainers do have actual jobs, this may take some time to implement.

**Comment by Simao-Santos** [comment]
Related #169
