### ISSUE TITLE
Can't save profiles; UI becomes unresponsive

### ISSUE THREAD

**Issue by partyp770** [AntiMicroX/antimicrox#166]
**Describe the bug**
AntiMicroX bugs out and prevents me from pressing buttons in its GUI whenever I try to open the file explorer from inside it.
(For example, saving a new profile, or trying to set up verbose logging.)

**To Reproduce**

1. Create a new profile
2. Click "save as"
3. UI becomes unresponsive and cannot be closed or interacted with.

**Expected behavior**

I've never used AntiMicroX successfully before, but I believe a window is supposed to open in the Desktop Environment's native file browser.

**Screenshots**

**Configuration**
Version of AntiMicroX: 3.1.5
Used package: FlatPak
System version: Ubuntu 20.04 Focal Fossa

**Additional context**

I'm running linux on a Nintendo Switch. The device behaves like a somewhat quirky arm64 touchscreen Ubuntu device.
I also just recently learned that you're not supposed to run graphical applications as superuser, and if I messed up permissions, I have no idea how to fix it.

**Comment by pktiuk** [comment]
If you want speed then don't use flatpak.  
Flatpak packages consume more memory. It may be important in case of low-power devices like switch.

**Comment by pktiuk** [comment]
I will check it on my Raspberry Pi (and I will try to underclock it a little)  
If this problem won't reproduce then it may be caused by your atypical setup.

**Comment by pktiuk** [comment]
I have tested flatpak version on raspberry pi, I did not notice any problems with performance.  
This is a platform-related issue.
