### ISSUE TITLE
Multiple distance tags in joystick modifier for various walking speeds

### ISSUE THREAD

**Issue by Simao-Santos** [AntiMicroX/antimicrox#169]
**Is your feature request related to a problem? Please describe.**
It's always awkward to assign buttons with multiple walking speeds. Since the distance tag is only allowed once, in my case to improvise, I made a cycle when pressing the R3 button for example, to cycle between the speeds.

**Describe the solution you'd like**
A solution would be to add various "distance" tags (I don't know if that's the correct name) to the joystick modifier.

**Comment by pktiuk** [comment]
Linked with: https://github.com/AntiMicroX/antimicrox/issues/310
