### ISSUE TITLE
Cannot run this program through the terminal

### ISSUE THREAD

**Issue by deoxal** [AntiMicroX/antimicrox#171]
**Describe the bug**
I can't run `antimicrox --help` just to give an example with the flatpak version

My shell suggests I install `antimicro (2.23-2build1)`

**Configuration**
Version of antimicrox: 3.1.5
Used package: flatpak

**Additional context**
I want to launch AntiMicroX minimized with specific profiles through scripts.

**Comment by pktiuk** [comment]
Hi @deoxal ,
Flatpak package is launched with command `flatpak run io.github.antimicrox.antimicrox` (All of flatpak apps are launched in this way).

You can add `alias antimicrox='flatpak run io.github.antimicrox.antimicrox'` to your `.bashrc` file to run it in classical way.

**Comment by deoxal** [comment]
Hey thanks for the help. Do you think this could be added the readme or wiki to help new users like me?

**Comment by pktiuk** [comment]
@deoxal  
You have a point
