### ISSUE TITLE
Is there a "privacy policy" file for this app?

### ISSUE THREAD

**Issue by mayrinck** [AntiMicroX/antimicrox#175]
Not that this is so important for this type of app but, I was wondering if there is a Privacy Policy page for this app. Would be useful for redistribution on stores (like Microsoft Store)... I would love to support Antimicro on [this project](https://github.com/mayrinck/FOSSonMicrosoftStore).

**Comment by pktiuk** [comment]
Hi @mayrinck, 

I am not sure whether any privacy policy should be needed from an offline app, which doesn't collect any data.   
What should be in such a document in this case?

**Comment by mayrinck** [comment]
> Hi @mayrinck,
> 
> I am not sure whether any privacy policy should be needed from an offline app, which doesn't collect any data.
> What should be in such a document in this case?

I think the document should state exactly that... It's an offline app that doesn't collect and upload any data... This can help me add Antimicro and AntimicroX (maybe) to the store in the future...

**Comment by Tropix126** [comment]
for some context mayrinck/FOSSonMicrosoftStore#6

**Comment by pktiuk** [comment]
I assume the license you added for AntiMicro passed.  
The same should be good for AntiMicroX.

Can I find this issue as resolved?

**Comment by mayrinck** [comment]
I think it's okay to set that. Thanks!

**Comment by pktiuk** [comment]
I am working now on restoring windows support, and I am thinking how do you build installer for Windows.  https://github.com/AntiMicroX/antimicrox/issues/237

Do you use some generator for building packages?  
Do you build it manually or using CI?
