### ISSUE TITLE
Adding support for Wii Mote.

### ISSUE THREAD

**Issue by Ilovemyhous** [AntiMicroX/antimicrox#199]
**Is your feature request related to a problem? Please describe.**

To be honest, I don't know if this is a problem on my side, or if it is lack of the controller support.

**Describe the solution you'd like**

Adding support for the Nintendo Wii Mote (along with Motion Plus and accessories like Nunchunk if possible).

**Describe alternatives you've considered**

The only games that support the Wii Mote is the Dolphin Emulator.

**Additional context**

The [Wii emulator Dolphin](https://dolphin-emu.org/) has support for Wii Motes, and is [Open-Source](https://github.com/dolphin-emu/dolphin), so you could maybe find how they manage the connections.

**Comment by pktiuk** [comment]
What do you mean by Wiimote support?  
Every gamepad can be mapped with AntiMicroX.

**Comment by Ilovemyhous** [comment]
I connected it, and it doesn’t show up, even though I update the Joysticks.
But if you don’t wanna it, I won’t bother you anymore.

**Comment by pktiuk** [comment]
It is not AntiMicroX issue, it is rather caused by wrong drivers or something like this.

**Comment by Ilovemyhous** [comment]
I tried with Linux Mint 20.2, and Garuda Linux, and on both systems, it didn't show up.
The Bluetooth/Wi-Fi Card: `Device-4: 3-3:5 info: Intel type: Bluetooth driver: btusb rev: 2.0 chip ID: 8087:0029 `

**Comment by pktiuk** [comment]
You should also try with app `jstest-gtk` if that one also doesn't see your wiimote, then something is wrong with your drivers.

**Comment by Ilovemyhous** [comment]
Doesn't see it too. :/
As you said, it's either an driver, or OS issue.
![image](https://user-images.githubusercontent.com/50217071/132255506-19feb664-b4db-49d5-850a-81a2ba3590e7.png)

**Comment by pktiuk** [comment]
Neither of these applications recognizes it as a joystick.  
Then problem is somewhere in your system.

Maybe `dmesg` would tell you more.
You have to investigate it by yourself.

**Comment by mak448a** [comment]
Having the same issue. Could you please reopen this issue?

**Comment by pktiuk** [comment]
@mak448a   
No, I won't reopen this issue.

> It is not AntiMicroX issue, it is rather caused by wrong drivers or something like this.
> Every device recognized as a gamepad/joystick should be visible in AntiMicroX.

This is not AntiMicroX issue. This is missing driver in your system (if any other app doesn't see this controller) or bug in SDL2.

**Comment by mak448a** [comment]
Steam sees the wiimote.

**Comment by pktiuk** [comment]
> Steam sees the wiimote.

Then this is not a driver issue.

Could you test it with app `sdl-jstest`? It is also based on SDL and if that app works (with the same SDL version as AntiMicroX - 2.26.5), then it will show that there is a bug in the AntiMicroX.

**Comment by mak448a** [comment]
Since it looked like I had to compile sdl-jstest, I just used jstest-gtk (hopefully similar)
![image](https://github.com/AntiMicroX/antimicrox/assets/94062293/4d3bf241-c3a7-4af8-92f9-4a55bd5c98a1)
It detects all buttons except the dpad
![image](https://github.com/AntiMicroX/antimicrox/assets/94062293/db1e946b-56d9-4a07-8094-904b4791f22d)

**Comment by pktiuk** [comment]
@mak448a   
Unluckily not. This app does not use SDL for detecting gamepads.

**Comment by klausmcm** [comment]
In case this is of interest to anyone, I have a wiimote (Nintendo Wii MotionPlus) working in AntiMicroX (AntiMicroX-x86_64.AppImage - v3.3.4). I'm on Debian (Trixie) with KDE. Other than having a bluetooth adapter, I didn't need to do anything else to get the wiimote connected. All buttons are recognized. I don't think AntiMicroX supports the gyro though unfortunately.

![image](https://github.com/AntiMicroX/antimicrox/assets/14914359/57c1e267-56f8-49ae-8c37-9a1cece68670)
