### ISSUE TITLE
Implement features from the app called 'rewasd' 

### ISSUE THREAD

**Issue by Sultech** [AntiMicroX/antimicrox#202]
On windows there is an app called rewasd which lets you bind controller buttons to a keyboard or mouse, this makes the game think you are using a controller, it creates a virtual controller. Rewasd also lets you have groups, by this I mean rewasd can let u have one profile for a keyboard and a real controller, so if you change some of the keyboard binds to controller binds, then you start rewasd the real controller and the keyboard will be 1 input as a virtual controller. The game will only see 1 controller. This can be useful in many cases. I have asked rewasd to port the app over to linux but they don't have any experience with linux. Here is what rewasd said: 

' Thanks for the explanation and sorry for my late answer. The problem is that reWASD is a driver-based software with pretty big functionality. It won't be an easy task to bring it all to Linux. so we can't promise anything so far.'

So I am now asking you to try to implement some of these features if it is possible. I would find this very useful and so would other people

(If I did not explain what rewasd does well enough for you to understand you can try the app for free, 14 day trial)

**Comment by pktiuk** [comment]
No, we are not going to implement any features from reWASD.  
They are out of scope of AntiMicroX
