### ISSUE TITLE
Flatpak version doesn't work on Wayland

### ISSUE THREAD

**Issue by fin-ger** [AntiMicroX/antimicrox#221]
**Describe the bug**
I installed the flatpak version from flathub with `flatpak install flathub io.github.antimicrox.antimicrox` and tried to launch the application via the Gnome launch menu but nothing happened. Then I launched the application via terminal with `flatpak run io.github.antimicrox.antimicrox` and got this message:

```
$ flatpak run io.github.antimicrox.antimicrox 
Gtk-Message: 13:30:19.451: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:30:19.451: Failed to load module "pk-gtk-module"
Gtk-Message: 13:30:19.452: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:30:19.452: Failed to load module "pk-gtk-module"
Selecting uinput as a default event generator.Could not open uinput device file
Please check that you have permission to write to the device: /dev/uinput
Failed to open event generator. Exiting.
```

Unfortunately, I do not know how to change any permission for `/dev/uinput/` in flatpak.

**To Reproduce**

1. Install flathub version
2. Run it in terminal
3. See error

**Expected behavior**

Application should just launch after clean installation.

**Configuration**
Version of antimicrox: 3.1.7
Used package: flathub
System version: Fedora 33

**Comment by pktiuk** [comment]
Don't use flatpak package on Wayland.  
Use RPM instead

**Comment by fin-ger** [comment]
Yes, the RPM package works, thanks for your quick response! Would you mind documenting in the Readme and the flathub description that Wayland is unsupported and the RPM package must be used?

**Comment by pktiuk** [comment]
I think this is a good idea.  

Maybe we should also mention it in app information visible in flathub.

**Comment by pktiuk** [comment]
There is a workaround for flatpak fixing this issue.

Manually adding our udev rule.

```bash 
cd /etc/udev/rules.d/
sudo wget https://raw.githubusercontent.com/AntiMicroX/antimicrox/master/other/60-antimicrox-uinput.rules
```
After reboot, this rule should be applied and udev should work properly.

@gombosg  
What do you think about this workaround?  
Should we put it into our readme or just recommend using classical packages?

**Comment by pktiuk** [comment]
Using classical packages has some drawbacks.  
Versions in repositories are not the latest, and they don't apply udev rules, but packages downloaded from github will not be updated automatically.

**Comment by fin-ger** [comment]
Regarding this I am currently investigating a problem regarding the udev rule (possibly unrelated to this issue and may need a separate issue?):

I tried using the package from the Fedora 33 repository. It started perfectly fine, found my controllers (usb and Bluetooth working) but moving the mouse with a controller stick works only half-way on wayland, while it's working perfectly on X11 (nevertheless I need to get it to work on wayland as I don't want to miss touchpad gestures). On Wayland the visible cursor icon is not moving but I can see highlighted buttons and text boxes while I "move" the cursor with the analog stick. I tried writing a small C programm issuing uinput commands and ran it as root. The mouse cursor Icon moves as expected and no weird "buttons get highlighted only without the cursor moving" issue appeared. Next I tried compiling antimicrox on my own and uninstalled the repository version. My self-compiled antimicrox (with the udev-rule from the git repo manually applied) works flawlessly. Maybe there is also something wrong with the Fedora package (again, I think this would require filing a bug in the Fedora issue tracker, not here?) or there were some code changes in master which are not in the latest release fixing the issue?

Thanks for your time and help and this awesome project!

**Comment by pktiuk** [comment]
Package in Fedora repository contains version `3.1.4`, current version (where I introduced switching from x11 to uinput and added udev rule) is `3.1.7`

**Comment by gombosg** [comment]
I'm working on updating the package with the new udev rules.

>  Should we put it into our readme or just recommend using classical packages?

We can put into readme, I guess we'll never be able to pull off such a thing inside a Flatpak.

**Comment by gombosg** [comment]
@fin-ger you can test 3.1.7 from updates-testing here: https://bodhi.fedoraproject.org/updates/?search=antimicrox

**Comment by fin-ger** [comment]
@gombosg yes sure, I just tried and everything works flawlessly. Great job!
