### ISSUE TITLE
QObject: Cannot create children for a parent that is in a different thread.

### ISSUE THREAD

**Issue by L00170299** [AntiMicroX/antimicrox#238]
**Describe the bug**
Nintendo Switch pro controller in Fedora 33 connected by usb works fine.
Same controller connected by Bluetooth shows error in terminal:
"Warning: QObject: Cannot create children for a parent that is in a different thread.
(Parent is GameControllerSet(0x55c732d1fcd0), parent's thread is QThread(0x55c733107230), current thread is QThread(0x55c732ba1920) ((null):0, (null))"

**To Reproduce**
1- Pair controller by bluetooth
2- launch antimicrox from console
3- Press any button in Nintendo switch controller to see errors in terminal (The antimicrox GUI wont crash but wont do anything else. )

**Expected behavior**
it will execute the action configured for button in controller

**Screenshots**
![image](https://user-images.githubusercontent.com/90723079/134727229-368a48c0-cfa7-45fc-933d-7bdd37f078dc.png)

**Configuration**
Version of antimicrox: 3.1.4
Used package: Fedora Repo: dnf
System version: Fedora 33

**Additional context**

**Comment by pktiuk** [comment]
Could you update your AntiMicroX version to 3.1.7 (this version is not available yet, but I think you could download it from there https://bodhi.fedoraproject.org/updates/?search=antimicrox)  

There were many fixes since then

**Comment by L00170299** [comment]
Hey Pawel,

Thanks for the info, I didn't know we could get the test pkgs.

Sadly it is still giving me same error.
If I connect controller by usb it works fine. Its just when I try to use bluetooth.
Let me know if I can help anyhow to fix/find the issue. ( please reply to ***@***.*** )

[cid:a891be3a-dc22-42d0-ac67-4b013cd4e551]

________________________________

**Comment by pktiuk** [comment]
Does this pad work properly (by bluetooth) with any application on Linux?  
AFAIK, Nintendo Switch controllers are not fully supported on Linux yet.

They are waiting for merging into Linux kernel. Link to mailing list https://patchwork.kernel.org/project/linux-input/patch/20200317032928.546172-2-djogorchock@gmail.com/

**Comment by pktiuk** [comment]
Closing due to lack of feedback

**Comment by cork** [comment]
Om seeing the same problem as reported in #274. Not sure if this helps but this is a stacktrace from the problem.
(running a antimicrox with some warnings commented out and QT_FATAL_WARNINGS=1)
```
[20:05:55.499] ❗WARN	QObject: Cannot create children for a parent that is in a different thread.
			(Parent is GameControllerSet(0x555555b644e0), parent's thread is QThread(0x555555f8c0b0), current thread is QThread(0x5555559d2d90)

Thread 1 "antimicrox" received signal SIGABRT, Aborted.
0x00007ffff641334c in __pthread_kill_implementation () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff641334c in __pthread_kill_implementation () from /usr/lib/libc.so.6
#1  0x00007ffff63c64b8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff63b0534 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff6959126 in QMessageLogger::warning(char const*, ...) const () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff6b6d297 in QObject::QObject(QObjectPrivate&, QObject*) () from /usr/lib/libQt5Core.so.5
#5  0x00005555557c15f0 in JoyAxis::JoyAxis (this=0x555555d1c6a0, index=0, originset=0, parentSet=0x555555b644e0, parent=0x555555b644e0) at /tmp/antimicrox/src/joyaxis.cpp:39
#6  0x00005555556afa05 in GameControllerSet::refreshAxes (this=0x555555b644e0) at /tmp/antimicrox/src/gamecontroller/gamecontrollerset.cpp:330
#7  0x0000555555838454 in SetJoystick::reset (this=0x555555b644e0) at /tmp/antimicrox/src/setjoystick.cpp:216
#8  0x00005555556ad830 in GameControllerSet::resetSticks (this=0x555555b644e0) at /tmp/antimicrox/src/gamecontroller/gamecontrollerset.cpp:43
#9  0x00005555556ad814 in GameControllerSet::reset (this=0x555555b644e0) at /tmp/antimicrox/src/gamecontroller/gamecontrollerset.cpp:39
#10 0x00005555557b3e61 in InputDevice::reset (this=0x555555b9a120) at /tmp/antimicrox/src/inputdevice.cpp:72
#11 0x00005555557b400f in InputDevice::transferReset (this=0x555555b9a120) at /tmp/antimicrox/src/inputdevice.cpp:102
#12 0x0000555555847b8d in InputDeviceXml::readConfig (this=0x5555568df050, xml=0x55555676ca20) at /tmp/antimicrox/src/xml/inputdevicexml.cpp:41
#13 0x000055555585f084 in XMLConfigReader::read (this=0x5555568df270) at /tmp/antimicrox/src/xmlconfigreader.cpp:142
#14 0x000055555585eaf4 in XMLConfigReader::configJoystick (this=0x5555568df270, joystick=0x555555b9a120) at /tmp/antimicrox/src/xmlconfigreader.cpp:87
#15 0x0000555555845ffa in JoyTabWidgetHelper::readConfigFile (this=0x5555560e2960, filepath=...) at /tmp/antimicrox/src/uihelpers/joytabwidgethelper.cpp:88
#16 0x00005555557475f6 in JoyTabWidget::changeJoyConfig (this=0x5555560e2740, index=1) at /tmp/antimicrox/src/gui/joytabwidget.cpp:913
```

I got to https://github.com/AntiMicroX/antimicrox/blob/master/src/joyaxis.cpp#L39 but not sure where to go from there.

**Comment by cork** [comment]
What seams to happen is that the timers aren't started so turbo has no effect what so ever (not sure if toggle uses timers)
