### ISSUE TITLE
VisualBoyAdvance-m Keys Not Forwarding

### ISSUE THREAD

**Issue by kykorman** [AntiMicroX/antimicrox#239]
**Describe the bug**
AntiMicroX recognizes gamepad and shows keys being pressed. After completing mapping to desired keys, does not forward these keys into VisualBoyAdvance-m application. Input can be seen in background highlighting buttons in AntiMicroX but these seemingly do not make it to the other application. Seemingly doesn't forward it to things like Firefox either, though I am not sure on whether this is intended.

**To Reproduce**
Ubuntu 21.10 Impish Indri, VisualBoyAdvance-m, AntiMicroX 3.1.4. Configure AntiMicroX to desired keys for use in other application, select other window, does not forward these keys.

**Expected behavior**
Keys should be forwarded and allow movement and interaction inside of VisualBoyAdvance-m.

**Screenshots**
Video of issue occurring: https://www.dropbox.com/s/xaxm8dhpk4c535g/failure.webm?dl=0

**Configuration**
Version of antimicrox: 3.1.4
Used package: Newest from apt
System version: Ubuntu 21.10

**Additional context**
I have tried installing various gamepad drivers for the controller trying to get it to work with VisualBoyAdvance-m before seeing the controller working with jstest-gtk and finally trying AntiMicroX.

**Comment by pktiuk** [comment]
Could you update to 3.1.7? https://github.com/AntiMicroX/antimicrox/releases  

Does it work properly with other apps?

**Comment by kykorman** [comment]
> Could you update to 3.1.7? https://github.com/AntiMicroX/antimicrox/releases
> 
> Does it work properly with other apps?

It now works flawlessly with the newer version. My apologies for opening an issue. I should've checked versions sooner.

**Comment by pktiuk** [comment]
I assume it was caused by lack of proper Wayland support in older versions.

**Comment by pktiuk** [comment]
@mirabilos  
Is there any chance of updating antimicrox for Ubuntu 21.04 and newer?  
They use Wayland by default and because of this version from repositories (3.1.4) won't work at all.

**Comment by mirabilos** [comment]
Paweł Kotiuk dixit:

>Is there any chance of updating antimicrox for Ubuntu 21.04 and newer?  

Yes, but not right now but when I find the time.

Thanks for noticing,
//mirabilos
-- 
Gestern Nacht ist mein IRC-Netzwerk explodiert. Ich hatte nicht damit
gerechnet, darum bin ich blutverschmiert… wer konnte ahnen, daß SIE so
reagier’n… gestern Nacht ist mein IRC-Netzwerk explodiert~~~
	(as of 2021-06-15 The MirOS Project temporarily reconvenes on OFTC)
