### ISSUE TITLE
autostart antimicro from steam using SteamAppId?

### ISSUE THREAD

**Issue by frostworx** [AntiMicroX/antimicrox#24]
Hi,
_(I personally rarely play with joypad, so  sorry if this is a stupid idea)_

If a contributed antimicroX-profile could be found by the game's `SteamAppId`, it would be pretty easy to implement antimicroX support into my [steamtinkerlaunch (stl)](https://github.com/frostworx/steamtinkerlaunch) wrapper.
So if a game is started from steam stl would search for a antimicroX-profile (first offline, then optionally online in the repo) and automatically loaded it if found.
If no usable profile was found antimicroX could open in gui mode so one can be created _(here it would be nice if antimicroX would already default to the profilename which was passed via the --profile command line)_.

When the game exits, antimicroX would be stopped automatically as well.

**Comment by pktiuk** [comment]
There is autoprofile functionality which could deal with this issue.

![obraz](https://user-images.githubusercontent.com/45544416/107161660-71354d80-699e-11eb-9789-2ae0f0becb5f.png)

**Comment by frostworx** [comment]
Heh, totally forgot about this issue.
I don't see how the autoprofile function could help to automate anything though.
Passing the window class/title via stl automated to antimicro would be simple, but that doesn't generate a game-specific joypad config.

**Comment by pktiuk** [comment]
Currently AntiMicroX profiles are linked only with selected gamepads.  
Linking them with steam ID would be additional task for users.  
To make it work X gamepads and Y games we would need X*Y configs in our database (that's a lot).

Implementing this and creating database would require tons of work and result would be not great (missing configs for most of games).   
For now, every user of steam willing to use AntiMicroX with selected games can change game launch options. (in case of Lutris this even easier)
