### ISSUE TITLE
Bluetooth Macro Issue with DS4 Controller

### ISSUE THREAD

**Issue by mobedoor** [AntiMicroX/antimicrox#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Macros do not work with my DS4 controller when connected via Bluetooth while the same works fine in wired mode.

### Expected Behavior

For macros to work in Bluetooth mode.

### Steps To Reproduce

Press key mapped to macro
No response.

### Environment

```markdown
- OS: Manjaro Linux 21.2.0
- AntiMicroX version: 3.1.7
```

**Comment by pktiuk** [comment]
What kind of macros were assigned to this button?   
Could you send config? I could test it by myself with my DS4 pad.

**Comment by mobedoor** [comment]
Here.
[anki.gamecontroller.amgp.zip](https://github.com/AntiMicroX/antimicrox/files/7332067/anki.gamecontroller.amgp.zip)
The Macro's are mapped to triangle and the right trigger
Thank you.

**Comment by pktiuk** [comment]
In my case both ways of connecting DS4 works properly.  
Pressing triangle generates: return+wait some time+pressing return once more, just as expected.

**Comment by pktiuk** [comment]
Does your app see pressing gamepad button correctly in both cases? (button changes color)

**Comment by mobedoor** [comment]
Yes. The buttons do change color.

**Comment by Excelsiorrr** [comment]
Same issue here. My PS4 joystick works well with macros when wired (e.g., Press time 0.10s-> Press "C" -> Pause 0.20 second ), which can be set by refering to "Advanced -> Assignments). However, when connecting via bluetooth, macros won't work.

**Comment by Excelsiorrr** [comment]
> Same issue here. My PS4 joystick works well with macros when wired (e.g., Press time 0.10s-> Press "C" -> Pause 0.20 second ), which can be set by refering to "Advanced -> Assignments). However, when connecting via bluetooth, macros won't work.

FYI: 
1) the buttons do change color when pressed
2) only macros won't work (simple bidding with mouse/keyboard still works though).

**Comment by Excelsiorrr** [comment]
Any feedback on this? The latest version still don't work uwu

**Comment by mobedoor** [comment]
Hi @pktiuk. I just checked and don't seem to have the issue anymore.
