### ISSUE TITLE
AutoProfile is not saved when valid path is not specified in the Application field

### ISSUE THREAD

**Issue by mobedoor** [AntiMicroX/antimicrox#252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Application profiles are not saved when a valid path is not specified in the application field i.e whether if it is left empty or not.

### Expected Behavior

That profiles save regardless of anything specified in the application field.

### Steps To Reproduce

Add profile
Detect and select window class (brave-browser-beta Brave-browser-beta)
Select profile
Press save
Nothing is saved

### Environment

```markdown
- OS: Manjaro Linux 21.2.0
- AntiMicroX version: 3.1.7
```

### Anything else?

A workaround that works for me is to specify a valid path (of another application when antimicrox doesen't detect path of the app in question) and then when profile is successfully saved, remove the same.

**Comment by pktiuk** [comment]
Thank you, @mobedoor your findings helped me a lot with fixing this bug
