### ISSUE TITLE
The ability to assign buttons from other devices

### ISSUE THREAD

**Issue by addeps3** [AntiMicroX/antimicrox#255]
**Is your feature request related to a problem? Please describe.**

I have discrete Logitech pedals that are connected with the Leo Bodnar DB9-to-USB adabter, which detects and reads input correctly in antimicroX. But I cant use the device in-game because I would need to combine the pedal axis' (plural) to the gamepad I use to steer with. This is the setup Im using now, and Im not likely to change it. 

**Describe the solution you'd like**

When assigning keys: list the other devices that are detected by the app, and allow the ability to assign buttons or axis' from that, not just keyboard and mouse.

**Comment by pktiuk** [comment]
Sorry, but this feature is out of scope of this app.
