### ISSUE TITLE
Logitech X52 H.O.T.A.S issue: Antimicrox doesn't override controller's default actions

### ISSUE THREAD

**Issue by Chinchzilla** [AntiMicroX/antimicrox#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Logitech X52 settings in Antimicrox don't override default controllers behaviour. 

E.g. In Elite Dangerous when Saitek X52 preset is selected and I have the key assigned to do different action, then it performs both at the same time.

It means Antimicrox doesn't override the default action but instead just does both.

### Expected Behavior

It works fine on Windows with the Logitech X52 software, if you assign different action to a key, it overrides it, so even though in game that button is used for e.g. Flight Assist toggle, you assign it Headlook mode, it just toggles a Headlook mode and not Flight Assist and Headlook at the same time.

### Steps To Reproduce

1. There is a middle mouse on the throttle stick
2. By default it is assigned to flight assist toggle in the Elite: Dangerous as a Flight assist toggle
3. Go to Antimicrox and assign that Middle mouse button as a Middle mouse button, that one is assigned as a headlook mode by default
4. Go to the game and press the button, it should toggle Flight assist and Headlook mode at the same time

### Environment

```markdown
- OS: Manjaro Gnome
- AntiMicroX version: 3.1.7
```

### Anything else?

If it's intended behaviour, then I am sorry to report it as a bug, but for the game itself it's unusable, the default set of controls is fine in game, I just need to add actions through the pinky switch so I don't have to take hands of the HOTAS and program commands to have a smoother experience.

**Comment by pktiuk** [comment]
Have you checked Wiki? 

https://github.com/AntiMicroX/antimicrox/wiki/Methods-for-Disabling-Joystick-Reading-in-Linux

**Comment by pktiuk** [comment]
Closing due to lack of feedback
