### ISSUE TITLE
Consistent naming across app

### ISSUE THREAD

**Issue by pktiuk** [AntiMicroX/antimicrox#26]
Currently, this project uses 3 variations of its name: `antimicrox`, `antimicroX` and `AntiMicroX`
It may cause some problems, that's why we will use from now only 2 variants:

- [x] `antimicrox` - used across filenames, names of directories and packages (https://github.com/AntiMicroX/antimicroX/pull/23#pullrequestreview-483167484)
- [x] `AntiMicroX` - more visually appealing version, it will be name visible for our users (in docs, application description etc)

**Comment by pktiuk** [comment]
@gombosg 
I am not sure what should we do in case on docker images, these seem to be done entirely by prevoius maintainer and they are independent of us (they have been uploaded on hub.docker.com) and I am not sure if should we mess with them.

**Comment by gombosg** [comment]
What else than updating them and uploading the resulting new images? :slightly_smiling_face: 
It's another way of distributing an app, although more niche.

**Comment by OlegPopow** [comment]
> What else than updating them and uploading the resulting new images? 
> It's another way of distributing an app, although more niche.

Rather, you set up a new account and place new containers. How do you imagine an update on an account you do not have access to?

**Comment by gombosg** [comment]
I mean, updating the dockerfiles.
