### ISSUE TITLE
Missing .dll files after Windows installation

### ISSUE THREAD

**Issue by pktiuk** [AntiMicroX/antimicrox#268]
```
The code execution cannot proceed because Qt5Core.dll was not found. Reinstalling the program may fix this problem.
The code execution cannot proceed because Qt5Gui.dll was not found. Reinstalling the program may fix this problem.
The code execution cannot proceed because Qt5Concurrent.dll was not found. Reinstalling the program may fix this problem.
The code execution cannot proceed because Qt5Network.dll was not found. Reinstalling the program may fix this problem.
```

Helpful materials: https://github.com/giddie/qt-cmake-template/blob/master/win/CMakeLists.txt

**Comment by pktiuk** [comment]
Could you test [this file](https://github.com/pktiuk/antimicrox/releases/download/3.2.0-private/antimicrox-3.2.0-AMD64.exe)

**Comment by sgern** [comment]
> 
> 
> Could you test [this file](https://github.com/pktiuk/antimicrox/releases/download/3.2.0-private/antimicrox-3.2.0-AMD64.exe)

Didn't seem to work for me.

**Comment by pktiuk** [comment]
What kind of error do you get?

**Comment by sgern** [comment]
Same as above.

**Comment by Zacharybinx34** [comment]
> Could you test [this file](https://github.com/pktiuk/antimicrox/releases/download/3.2.0-private/antimicrox-3.2.0-AMD64.exe)

Same error

**Comment by Gameplayer9198** [comment]
I'm getting Qt5Widgets.dll, libgcc_s_seh-1.dll and libstdc++-6.dll was not found running 3.2.0

**Comment by pktiuk** [comment]
It depends on system configuration.  
I have installed QT toolkit, that's why everything worked in my case.  
I have to test it with clean installation.

**Comment by grandmoffgigi** [comment]
Same issue on windows 10

**Comment by Kanadeforever** [comment]
Same issue on WIN10

**Comment by rayman3003** [comment]
First I got this error:

![01](https://user-images.githubusercontent.com/17022701/139528339-7223cc81-906f-408d-a39b-c8e1b0542faa.jpg)

I download "Qt5Widgets.dll" online & put it in app's folder & then got this error:

![02](https://user-images.githubusercontent.com/17022701/139528360-a2824526-06bb-4d63-9bc2-62cbf113811e.jpg)

Then I download "libwinpthread-1.dll" & put it in the same folder & got this error at the end:

![03](https://user-images.githubusercontent.com/17022701/139528375-ddf166c3-1e37-4289-97cc-e331919e5d6b.jpg)

**Comment by pktiuk** [comment]
I uploaded new installed in [release site](https://github.com/AntiMicroX/antimicrox/releases/tag/3.2.0).  
It should work now. Works with my VM. Could anyone check?

**Comment by Gkjsdll** [comment]
Thanks for the fix!

**Comment by rayman3003** [comment]
It works. Thank u very much.

**Comment by grandmoffgigi** [comment]
Appears to have fixed it.
