### ISSUE TITLE
Auto Profile Wrongly Shows Languages

### ISSUE THREAD

**Issue by sgern** [AntiMicroX/antimicrox#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Auto Profile menu appears to be inaccessible, as going to it in Settings instead takes the user to a language selection menu.

### Expected Behavior

Going to the Auto Profile menu should take the user to a menu where they can set profiles to activate upon the launch of specified programs.

### Steps To Reproduce

1. Open AntiMicroX
2. Open Settings
3. Go to Auto Profile

### Environment

```markdown
- OS: Windows 10
- AntiMicroX version: 3.2
```

**Comment by pktiuk** [comment]
Thank you foy your report.  
Fix will be included into the next release.
