### ISSUE TITLE
Two kinds of crashes with PS4 controller

### ISSUE THREAD

**Issue by BasedOnPixels** [AntiMicroX/antimicrox#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The program crashes when I'm trying to assign/change buttons. This only happens with a PS4 controller (no issue on xbox 360 controller).

The first crash happens when you try to change any assigned button back to "None".

The second crash happens when you click the grey box in advanced key settings.

### Expected Behavior

It should not crash, run the function as intended.

### Steps To Reproduce

1st crash:
-Assign anything to a key
-Try to remove assigned key by using the "NONE" button
(The crash also happens when you don't have any key at all selected)

2nd crash:
-Open mapping for a key and select any key
-Click on advanced
-Click on the grey box next to the previously chosen key, which normally lets you put in another key

### Environment

```markdown
- OS: Windows 10
- AntiMicroX version: 3.2
```

### Anything else?

Button for crash 1
![NONE key](https://user-images.githubusercontent.com/13744383/139733921-9c2866db-2f55-499f-8d53-0d9e720bcc5e.png)
Alternatively a small clip for it
[https://puu.sh/Imm1h/82ea55b2cb.mp4](https://puu.sh/Imm1h/82ea55b2cb.mp4)

 Button for crash 2
![greybox](https://user-images.githubusercontent.com/13744383/139734078-2140acac-5516-45c1-b2b4-d6ba178b229b.png)
Alternatively small clip
[https://puu.sh/Immgc/63449632a2.mp4](https://puu.sh/Immgc/63449632a2.mp4)

**Comment by pktiuk** [comment]
Closing due to lack of feedback
