### ISSUE TITLE
Fedora resubmission

### ISSUE THREAD

**Issue by gombosg** [AntiMicroX/antimicrox#29]
This is to follow the Fedora resubmission process after the rename.

**Comment by gombosg** [comment]
Review bug for new package: https://bugzilla.redhat.com/show_bug.cgi?id=1878279

**Comment by gombosg** [comment]
Approved, so the package will be in the repos soon. Then I will retire `antimicroX`.

**Comment by pktiuk** [comment]
Remember to update installation instructions and list of packages, when package will be available.
