### ISSUE TITLE
Combining multiple devices into one virtual controller for proper HOTAS support

### ISSUE THREAD

**Issue by t9999clint** [AntiMicroX/antimicrox#293]
**Is your feature request related to a problem? Please describe.**
Several games like Space Engineers, Rouge Squadron 3D, Squadrons, No Man's Sky, Zone of the Enders, X3 etc... can only use one controller at a time. This means that for multi-controller setups like HOTAS or Dual Joystick, or even some racing wheel configs won't work properly at all. While you can get around most of this by assigning the buttons/hats to various keyboard presses, this leaves out any of the analog axis on the secondary controllers.

**Describe the solution you'd like**
On windows theres a few programs like T.A.R.G.E.T. that can combine the different usb controllers I have into one device that game will see as a single, "normal" controller.
I would like a option to combine two or more devices into a single profile so I can map it to a single virtual Xbox controller. With that I can assign the axis of my throtle, pedals and stick to the controller and just map the button's and switches to the keyboard.

**Describe alternatives you've considered**
There used to be a kernel module that would just combine different devices into one called unijoy, but it's old and doing this with a kernel module isn't really a good idea IMHO. https://github.com/iamtakingiteasy/unijoy

**Additional context**
This would also be handy for some emulators, as it would be kind of neat to play virtual-on with two joysticks (arcade style).

**Comment by pktiuk** [comment]
This feature is out of scope of antimicrox.

> AntiMicroX is a graphical program used to map gamepad keys to keyboard, mouse, scripts and macros.

Not for another gamepads or virtual devices (at least not for now).
