### ISSUE TITLE
No Auto Profile

### ISSUE THREAD

**Issue by Figuera** [AntiMicroX/antimicrox#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Auto Profile tab on the Setting Menu ask me to select my desired Language:

![2021-11-28_09-11-1638108502_partial](https://user-images.githubusercontent.com/703016/143771339-161025fe-b3a7-4798-821c-c026ca92dd8c.png)

### Expected Behavior

Auto Profile tab allow me to set which profile is loaded for each window.

### Steps To Reproduce

1 - Go to Options > Settings > Auto Profile.

### Environment

```markdown
- OS: Arch Linux
- Display: Wayland
- Environment: Sway
- AntiMicroX version: 3.2 (Both packages in AUR were tested)
```

### Anything else?

I wish I am being silly here and missing something obvious but I tried my best to get past that language selection screen to the actual Auto Profile Configuration and couldn't.

**Comment by pktiuk** [comment]
My first bet is lack of support for autoprofile feature in wayland.

I will have to check source code to be sure, but it seems to be the case

```cmake
if(UNIX)
    if(WITH_X11)
        LIST(APPEND antimicrox_SOURCES src/x11extras.cpp
                src/qtx11keymapper.cpp
                src/unixcapturewindowutility.cpp
                src/autoprofilewatcher.cpp
                src/gui/capturedwindowinfodialog.cpp
                )
        LIST(APPEND antimicrox_HEADERS src/x11extras.h
                src/qtx11keymapper.h
                src/unixcapturewindowutility.h
                src/autoprofilewatcher.h
                src/gui/capturedwindowinfodialog.h
                )

        if(WITH_XTEST)
```
Only builds with enabled X11 support have this feature compiled, that's why I guess this feature is not meant for non X11 environments.

**Comment by Figuera** [comment]
Maybe would be best to give a warning message then?

Also any advice on alternatives? Is there a command line option to change profiles?

**Comment by pktiuk** [comment]
> Also any advice on alternatives? Is there a command line option to change profiles?

Yes. Check `--help`

```
  --profile <location>                Launch program with the configuration
                                      file selected as the default for selected
                                      controllers. Defaults to all controllers
```

> Maybe would be best to give a warning message then?

Or implement for Wayland ;)

**Comment by clickonrefresh** [comment]
Maybe antimicro isnt picking up your locale. Check your locale. Im not sure
of commands for arch.

**Comment by Figuera** [comment]
> > Also any advice on alternatives? Is there a command line option to change profiles?
> 
> Yes. Check `--help`
> 
> ```
>   --profile <location>                Launch program with the configuration
>                                       file selected as the default for selected
>                                       controllers. Defaults to all controllers
> ```

Must confess that when I read this the first time I thought it would not work because it would try to launch antimicrox again, notice it was already running and fail. *maybe rewrite the help message*? No big deal, I should have tested but it might help others.

**Comment by pktiuk** [comment]
```cpp
    if (QApplication::platformName() == QStringLiteral("xcb")) //xcb is the X11 plugin used on regular desktop Linux platforms    {
        populateAutoProfiles();
        fillAllAutoProfilesTable();
        fillGUIDComboBox();
    } else
    {
        delete ui->categoriesListWidget->item(2);
        ui->stackedWidget->removeWidget(ui->page_2);
    }
 ```
 This is disabled for non-wayland sessions.

**Comment by pktiuk** [comment]
This is not a bug, but functionality not implemented.

New issue for tracking implementation is here: https://github.com/AntiMicroX/antimicrox/issues/301
