### ISSUE TITLE
"Before you open window with advanced settins, you have to choice a key"

### ISSUE THREAD

**Issue by blackwind** [AntiMicroX/antimicrox#306]
![error](https://user-images.githubusercontent.com/889881/144519872-f67a3393-a2af-4c3f-9b3c-fdb25f93d863.png)

This dialog prevents users from accessing advanced settings to bind set changes unless a key is also bound, which I don't want and wasn't required in the old AntiMicro. Please remove this artificial limitation.

**Comment by pktiuk** [comment]
This issue is part of https://github.com/AntiMicroX/antimicrox/issues/284

Currently, advanced assignment requires at least one button to show
