### ISSUE TITLE
Feature Request: Joystick modifier threshold (Walk/Run without a dedicated sprint button)

### ISSUE THREAD

**Issue by zpangwin** [AntiMicroX/antimicrox#310]
**Is your feature request related to a problem? Please describe.**

In games where a separate button is pressed to sprint/run, I would like to have Antimicrox to cover up the mechanics of this and allow me to play more organically, similar to many console games that have the character walk if you press the joystick slightly and run/sprint if you press it past some threshold.

**Describe the solution you'd like**

Antimicrox already detects joystick thresholds and allows setting a modifer key. But AFAIK, this modifier is *ALWAYS* enabled for the joystick. I'd like the ability to set a threshold where the modifier is *only* applied if I press the joystick to up to or past that amount.

For example, if the game defines the keyboard movement keys as WASD and the Sprint modifier key as Left Shift, I would like to be able to setup my joystick on an xbox 360 controller as follows:

* (existing range) Dead Zone: 10000
* (existing range) Max Range: 32000
* (proposed checkbox) [X] Enable Modifier Threshold
* (proposed range) Modifier Threshold: 22000
* (existing mapping) Modifier: Left Shift

Then if I press the joystick to where it is between 10000 (Dead Zone) and 21999 (just before Modifier Threshold), I will get WASD with no modifier applied. But if I press it between 22000 (Modifier Threshold) and 32000 (Max Range), I will get Left Shift + WASD **without** having to hold down another button.

This would also have the added benefit of freeing up a button in many profiles so it could be used for something else.

**Describe alternatives you've considered**

Only other alternatives I've found so far are:

* Hope that the game supports this directly and has a decent control scheme (not likely for most games it seems)
* Setup the game to toggle running on/off and just always leave it in Full Sprint mode
* Deal with having a dedicated key for Sprint in my layout that I have to hold down when I want to Sprint
 
**Additional context**

1. Ideally, there would be a checkbox to enable the option so that it is optional rather than mandatory.
2. A hover text explainer might also be good. 
3. IMO, it would also be a very nice additional to the Left stick preset options with text like "WASD Walk + LShift Run" etc.

Apologies in advance if this capability already exists... if so, then I wasn't able to figure out after spending 20 minutes between specifically looking for it in the app and googling. So in that event, possibly just consider this request to be asking for UI improvement to make it more obvious (see 1-3 above)?

The version I tested against was native version from central repos on Fedora 34:

    $ dnf list installed antimicrox
    antimicrox.x86_64                     3.2.0-1.fc34

It appears to be the latest version as of time of writing.

**Comment by pktiuk** [comment]
I like this idea. I may be quite useful.  
But firstly we will have to think how it should look and how it would be implemented.

**Comment by zpangwin** [comment]
> But firstly we will have to think how it should look and how it would be implemented.

Not sure on implementation but if it helps, here's a proposed layout (in dark mode)

![mockup-a](https://user-images.githubusercontent.com/29719631/145760312-f25f00ee-0eb9-49ef-8655-690cb6c8efd2.png)
