### ISSUE TITLE
Wayland support for keyboard emulation

### ISSUE THREAD

**Issue by gombosg** [AntiMicroX/antimicrox#32]
**Is your feature request related to a problem? Please describe.**
Should support KB emulation in wayland.

**Describe the solution you'd like**
Dunno yet.

**Additional context**
GUI works fine, tested in a Wayland Fedora VM.

Got this in a PM on reddit:
> It probably runs because of Qt but I don't think mouse and keyboard control would work. I would ask sway developers https://github.com/swaywm/wlroots about what protocols you need to use.
They are very helpful they have even opened MRs for some projects, to port them to wayland. You could just implement it for wlroots and let the community do the rest for you after. For example some wlroots focused tools will work in KDE Plasma soon because of the same protocols being implemented there.
"We hang out in #sway-devel, an IRC channel on irc.freenode.net. Come in and ask questions."

EDIT:
It can be done via switching from xtest to uinput, but uinput requires either root or aditional udev rule
TODO list:

- [x] switch from xtest to uinput when wayland session is detected https://github.com/AntiMicroX/antimicrox/pull/186
- [ ] integrate adding new udev rules into installation process
- [ ] update readme

**Comment by pktiuk** [comment]
Maybe in this case [XWayland](https://wiki.gnome.org/Initiatives/Wayland/XWaylandl) could be used. :thinking:

**Comment by gombosg** [comment]
XWayland is always running in these wayland sessions and it's used automatically.
Let's find where and how the KB/mouse events are being sent to the OS and ask on IRC. :slightly_smiling_face: 

As I see it uses these to simulate events:
```
[cmake] XTest support allowed for simulating events.
[cmake] uinput support allowed for simulating events.
```

So there are two questions that come to my mind:
- Is there a way to make this into a native [wayland QT app](https://doc.qt.io/qt-5/wayland-and-qt.html)? But as I see, this is about UI rendering and not passing KB/mouse input to the OS.
- Is there something wrong/wayland-incompatible about I/O?

As I see we have [`UInputEventHandler::sendKeyboardEvent()`](https://github.com/AntiMicroX/antimicroX/blob/9b383805b7967884a8b602c5a43be415c3427fe4/src/eventhandlers/uinputeventhandler.cpp#L195-L195) and its friends, plus [`XTestEventHandler::sendKeyboardEvent()`](https://github.com/AntiMicroX/antimicroX/blob/9b383805b7967884a8b602c5a43be415c3427fe4/src/eventhandlers/xtesteventhandler.cpp#L69-L69) and its friends.

My question was which one takes precedence. 
When I started: `Using Event Handler: XTest`, both in VM and local machine.

I tried `antimicrox --eventgen uinput`, that worked under X11 but not in Wayland (still I saw XTest, guess it fell back to XTest for some reason).

Enabling uinput would be the key here, guessing from [this SO](https://stackoverflow.com/questions/51406276/simulating-mouse-and-keyboard-input-on-wayland-and-x11).

**Comment by gombosg** [comment]
Oh, let's see this with debug log level. 
```
[gombosg@localhost-live Downloads]$ antimicrox --eventgen uinput --log-level debug
Warning: QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*) ((null):0, (null))
[01:42:31.481] - Could not open uinput device file
Please check that you have permission to write to the device
/dev/uinput
[01:42:31.481] - Attempting to use fallback option Xtest for event generation.
[01:42:31.481] - Using XTest as the event generator.
```

There we go! Maybe by running as a native wayland app this could work. Can you somehow compile with the [QTWayland module](https://wiki.qt.io/QtWayland)?

**Comment by gombosg** [comment]
With `sudo antimicrox --eventgen uinput` this is really working :rofl: ... let's go to IRC now to learn more about this permission issue.

**Comment by gombosg** [comment]
Unless they tell me some better solution in IRC, only a workaround works like [described here](https://www.codedbearder.com/posts/writing-keyboard-remapper-wayland/).

(`uinput` user group, udev rule, systemd service and all that to circumvent `sudo`)

**Comment by gombosg** [comment]
Just pasting the responses from IRC:

> Xtest isn't supported, and uinput should always require root I believe. There are protocols to explictly create virtual inputs though, and the libinput author also has something WIP called "libei", which would possibly be cross-Wayland/X11.

> the protocols in question are https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-virtual-pointer-unstable-v1.xml and https://github.com/swaywm/wlroots/blob/master/protocol/virtual-keyboard-unstable-v1.xml

> An annoying thing is that there's a split between GNOME and the rest of the community, with GNOME wanting to do everything over D-Bus because of their love for flatpak.
and thus, getting some of the protocols standardized is... Cumbersome. That's pretty much why the libei thing got started, as an "equally hated" solution :(

[libei](https://who-t.blogspot.com/2020/08/libei-library-to-support-emulated-input.html) is pretty much WIP though promising - not relevant now.

For now to address this, I'll create a section in the README describing some workarounds. (`--eventgen uinput` parameter, `sudo` or udev rules etc.)

Please if you can, look into compiling with QTWayland to make the app Wayland-compatible, and let's also look into whether making `uinput` the default (with XTest fallback) make sense.

**Comment by pktiuk** [comment]
> With `sudo antimicrox --eventgen uinput` this is really working rofl ... let's go to IRC now to learn more about this permission issue.

I think we will have to use [PolicyKit](https://wiki.debian.org/PolicyKit) to  somehow gain access to input group. In case if this will appear to be too messy I will check other solutions.

I will investigate it deeper soon.

**Comment by soredake** [comment]
@pktiuk maybe this will help? https://github.com/flatpak/flatpak/pull/4083

**Comment by pktiuk** [comment]
@soredake  
It could be useful, but it is not ready yet and it seems to be helpful only in case of flatpak package.
 

I think the best (and the simplest) solution would be creating a new dedicated group having access to uinput and  changing uid of executable.  

I think we should create postinstallation script dealing with it. We could also consider making this script optional and offer running it only when Wayland is detected.

Related topics:  
https://unix.stackexchange.com/questions/47880/how-debian-package-should-create-user-accounts   
https://stackoverflow.com/questions/11939255/writing-to-dev-uinput-on-ubuntu-12-04

**Comment by pktiuk** [comment]
It seems that for classic linux packages we could use [setuid](https://man7.org/linux/man-pages/man2/setuid.2.html), to make it work we should only [change bit](https://www.liquidweb.com/kb/how-do-i-set-up-setuid-setgid-and-sticky-bits-on-linux/) of executable, but I don't know how it would work with flatpak.

**Comment by jacopofar** [comment]
I just tried on Fedora 34 with flatpak, the program starts and detects the joypad, but then doesn't write any input.

Installing the antimicrox from the RPM repos and then running `sudo antimicrox --eventgen uinput` produces the same result

**Comment by pktiuk** [comment]
There is already prepared file adding new udev rule allowing users writing to uinput without sudo https://github.com/AntiMicroX/antimicrox/blob/master/other/40-uinput.rules

```
SUBSYSTEM=="misc", KERNEL=="uinput", MODE="0660", GROUP="uinput"
```

But this config file is not utilized anywhere.  

To work properly, this file should be placed at `/etc/udev/rules.d/` and user installing application should be added to uinput group.

**Comment by pktiuk** [comment]
I don't know whether this solution will work with flatpak https://github.com/flatpak/flatpak/issues/961

It would be good to check it to be sure.

**Comment by soredake** [comment]
Dunno how helpful it is https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/110
