### ISSUE TITLE
Remove daemon mode

### ISSUE THREAD

**Issue by pktiuk** [AntiMicroX/antimicrox#329]
Reported in comment https://github.com/AntiMicroX/antimicrox/issues/133#issuecomment-1001803836

**Comment by zpangwin** [comment]
Was testing the option (due to mention in #133 )

here is what I get on Fedora 34 Cinnamon:

    $ dnf list installed antimicrox
    Installed Packages
    antimicrox.x86_64                     3.2.0-1.fc34                      @updates
     
    $ antimicrox -d 
    ❗WARN	QCommandLineParser: option not defined: "next"
    ❗WARN	QCommandLineParser: option not defined: "map"
    ❗WARN	QCommandLineParser: option not defined: "display"
      
    $ pgrep --list-full --full --ignore-case antimicrox
    787305 antimicrox -d
     
    $ pkill --signal 9 --full --ignore-case antimicrox
     
    $ antimicrox --daemon 
    ❗WARN	QCommandLineParser: option not defined: "next"
    ❗WARN	QCommandLineParser: option not defined: "map"
    ❗WARN	QCommandLineParser: option not defined: "display"
     
    $ antimicrox --daemon --profile ~/Gaming/Antimicro/satisfactory/satisfactory_profile_01.gamecontroller.amgp 
    ❗WARN	QCommandLineParser: option not defined: "next"
    malloc_consolidate(): unaligned fastbin chunk detected
    Aborted (core dumped)

Having the controller on/off (wireless xbox 360 controller) does not appear to make any difference, nor does the flag used. Profile I was attempting to load is available [here](https://github.com/zpangwin/antimicro-profiles/tree/master/satisfactory).

Based on notes [here](https://github.com/AntiMicroX/antimicrox/issues/133#issuecomment-753082939), I see I have some core dump files that were just generated after trying to run with `-d` / `--daemon`

    $ ls -acl /var/lib/systemd/coredump|grep 'Dec 28 15:'
    drwxr-xr-x. 1 root root    5570 Dec 28 15:39 .
    -rw-r-----+ 1 root root 1786505 Dec 28 15:36 core.antimicrox.1000.ccfc9220a74e43408ff8d07322839de9.787403.1640723789000000.zst
    -rw-r-----+ 1 root root 1789555 Dec 28 15:39 core.antimicrox.1000.ccfc9220a74e43408ff8d07322839de9.787871.1640723965000000.zst

And running gdb, I get the following (attached zst file but including inline for convenience):

    $ cd /var/lib/systemd/coredump
    $ coredumpctl gdb $(which antimicrox) ./core.antimicrox.1000.ccfc9220a74e43408ff8d07322839de9.787871.1640723965000000.zst
               PID: 787871 (antimicrox)
               UID: 1000 (fd)
               GID: 1000 (fd)
            Signal: 6 (ABRT)
         Timestamp: Tue 2021-12-28 15:39:25 EST (12min ago)
      Command Line: antimicrox --daemon --profile /home/fd/Gaming/Antimicro/satisfactory/satisfactory_profile_01.gamecontroller.amgp
        Executable: /usr/bin/antimicrox
     Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-5bbbb287-1f0e-4915-b56b-60a642f33884.scope
              Unit: user@1000.service
         User Unit: vte-spawn-5bbbb287-1f0e-4915-b56b-60a642f33884.scope
             Slice: user-1000.slice
         Owner UID: 1000 (fd)
           Boot ID: ccfc9220a74e43408ff8d07322839de9
        Machine ID: a501bc0e702b417f893bb79e6a211ca7
          Hostname: tinyfedora.local
           Storage: /var/lib/systemd/coredump/core.antimicrox.1000.ccfc9220a74e43408ff8d07322839de9.787871.1640723965000000.zst (present)
         Disk Size: 1.7M
           Message: Process 787871 (antimicrox) of user 1000 dumped core.
                     
                    Stack trace of thread 787877:
                    #0  0x00007f03b8ca52a2 raise (libc.so.6 + 0x3d2a2)
                    #1  0x00007f03b8c8e8a4 abort (libc.so.6 + 0x268a4)
                    #2  0x00007f03b8ce7a97 __libc_message (libc.so.6 + 0x7fa97)
                    #3  0x00007f03b8cef70c malloc_printerr (libc.so.6 + 0x8770c)
                    #4  0x00007f03b8cf07ac malloc_consolidate (libc.so.6 + 0x887ac)
                    #5  0x00007f03b8cf266b _int_malloc (libc.so.6 + 0x8a66b)
                    #6  0x00007f03b8cf42c1 malloc (libc.so.6 + 0x8c2c1)
                    #7  0x00007f03b92b46d1 _ZN10QArrayData8allocateEmmm6QFlagsINS_16AllocationOptionEE (libQt5Core.so.5 + 0xf46d1)
                    #8  0x00007f03b9331074 _ZN7QString11reallocDataEjb (libQt5Core.so.5 + 0x171074)
                    #9  0x00007f03b933170f _ZN7QString6appendEPK5QChari (libQt5Core.so.5 + 0x17170f)
                    #10 0x00007f03b94e3954 _ZN18QTextStreamPrivate9putStringEPK5QCharib (libQt5Core.so.5 + 0x323954)
                    #11 0x00007f03b94e7299 _ZN11QTextStreamlsERK7QString (libQt5Core.so.5 + 0x327299)
                    #12 0x000055951c0ea1e0 _ZN6Logger10logMessageERK7QStringNS_8LogLevelEjS2_ (antimicrox + 0x1921e0)
                    #13 0x00007f03b9490f49 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2d0f49)
                    #14 0x00007f03ba44e443 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x1ae443)
                    #15 0x00007f03b94667d8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2a67d8)
                    #16 0x00007f03b9469d46 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2a9d46)
                    #17 0x00007f03b94b8117 _ZL23postEventSourceDispatchP8_GSourcePFiPvES1_ (libQt5Core.so.5 + 0x2f8117)
                    #18 0x00007f03b7f354cf g_main_context_dispatch (libglib-2.0.so.0 + 0x554cf)
                    #19 0x00007f03b7f894f8 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa94f8)
                    #20 0x00007f03b7f32c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
                    #21 0x00007f03b94b7bb8 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2f7bb8)
                    #22 0x00007f03b94651e2 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a51e2)
                    #23 0x00007f03b92a82ca _ZN7QThread4execEv (libQt5Core.so.5 + 0xe82ca)
                    #24 0x00007f03b92a94c6 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xe94c6)
                    #25 0x00007f03b9da9299 start_thread (libpthread.so.0 + 0x9299)
                    #26 0x00007f03b8d68353 __clone (libc.so.6 + 0x100353)
                     
                    Stack trace of thread 787875:
                    #0  0x00007f03b8d5d5bf __poll (libc.so.6 + 0xf55bf)
                    #1  0x00007f03b7f8948c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
                    #2  0x00007f03b7f34a93 g_main_loop_run (libglib-2.0.so.0 + 0x54a93)
                    #3  0x00007f03a6d90d9a gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x110d9a)
                    #4  0x00007f03b7f63c42 g_thread_proxy (libglib-2.0.so.0 + 0x83c42)
                    #5  0x00007f03b9da9299 start_thread (libpthread.so.0 + 0x9299)
                    #6  0x00007f03b8d68353 __clone (libc.so.6 + 0x100353)
                     
                    Stack trace of thread 787872:
                    #0  0x00007f03b8d5d5bf __poll (libc.so.6 + 0xf55bf)
                    #1  0x00007f03b8835f42 _xcb_conn_wait.part.0 (libxcb.so.1 + 0xdf42)
                    #2  0x00007f03b88378fc xcb_wait_for_event (libxcb.so.1 + 0xf8fc)
                    #3  0x00007f03a85f60d7 _ZN14QXcbEventQueue3runEv (libQt5XcbQpa.so.5 + 0x6e0d7)
                    #4  0x00007f03b92a94c6 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xe94c6)
                    #5  0x00007f03b9da9299 start_thread (libpthread.so.0 + 0x9299)
                    #6  0x00007f03b8d68353 __clone (libc.so.6 + 0x100353)
                     
                    Stack trace of thread 787876:
                    #0  0x00007f03b8d5d5bf __poll (libc.so.6 + 0xf55bf)
                    #1  0x00007f03b7f8948c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
                    #2  0x00007f03b7f32c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
                    #3  0x00007f03b94b7bb8 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2f7bb8)
                    #4  0x00007f03b94651e2 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2a51e2)
                    #5  0x00007f03b92a82ca _ZN7QThread4execEv (libQt5Core.so.5 + 0xe82ca)
                    #6  0x00007f03a84bbb6b _ZN22QDBusConnectionManager3runEv (libQt5DBus.so.5 + 0x1bb6b)
                    #7  0x00007f03b92a94c6 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5 + 0xe94c6)
                    #8  0x00007f03b9da9299 start_thread (libpthread.so.0 + 0x9299)
                    #9  0x00007f03b8d68353 __clone (libc.so.6 + 0x100353)
                     
                    Stack trace of thread 787873:
                    #0  0x00007f03b8d5d5bf __poll (libc.so.6 + 0xf55bf)
                    #1  0x00007f03b7f8948c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
                    #2  0x00007f03b7f32c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
                    #3  0x00007f03b7f32c51 glib_worker_main (libglib-2.0.so.0 + 0x52c51)
                    #4  0x00007f03b7f63c42 g_thread_proxy (libglib-2.0.so.0 + 0x83c42)
                    #5  0x00007f03b9da9299 start_thread (libpthread.so.0 + 0x9299)
                    #6  0x00007f03b8d68353 __clone (libc.so.6 + 0x100353)
                     
                    Stack trace of thread 787871:
                    #0  0x00007f03a4c4b96f _ZN7Adwaita11StylePluginD2Ev (adwaita.so + 0x2b96f)
                    #1  0x00007f03a4c4b98d _ZN7Adwaita11StylePluginD0Ev (adwaita.so + 0x2b98d)
                    #2  0x00007f03b945d8ec _ZN15QLibraryPrivate6unloadENS_10UnloadFlagE (libQt5Core.so.5 + 0x29d8ec)
                    #3  0x00007f03b9457aee _ZN21QFactoryLoaderPrivateD2Ev (libQt5Core.so.5 + 0x297aee)
                    #4  0x00007f03b9457bfd _ZN21QFactoryLoaderPrivateD0Ev (libQt5Core.so.5 + 0x297bfd)
                    #5  0x00007f03ba4c261d _ZZN12_GLOBAL__N_112Q_QGS_loader13innerFunctionEvEN6HolderD1Ev (libQt5Widgets.so.5 + 0x22261d)
                    #6  0x00007f03b8ca7af7 __run_exit_handlers (libc.so.6 + 0x3faf7)
                    #7  0x00007f03b8ca7ca0 exit (libc.so.6 + 0x3fca0)
                    #8  0x000055951bfbc6b2 main (antimicrox + 0x646b2)
                    #9  0x00007f03b8c8fb75 __libc_start_main (libc.so.6 + 0x27b75)
                    #10 0x000055951bfcabde _start (antimicrox + 0x72bde)
                     
                    Stack trace of thread 787874:
                    #0  0x00007f03b8d5d5bf __poll (libc.so.6 + 0xf55bf)
                    #1  0x00007f03b7f8948c g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa948c)
                    #2  0x00007f03b7f32c03 g_main_context_iteration (libglib-2.0.so.0 + 0x52c03)
                    #3  0x00007f03a86ef3ed dconf_gdbus_worker_thread (libdconfsettings.so + 0x73ed)
                    #4  0x00007f03b7f63c42 g_thread_proxy (libglib-2.0.so.0 + 0x83c42)
                    #5  0x00007f03b9da9299 start_thread (libpthread.so.0 + 0x9299)
                    #6  0x00007f03b8d68353 __clone (libc.so.6 + 0x100353)
     
    GNU gdb (GDB) Fedora 11.1-5.fc34
    Copyright (C) 2021 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    Type "show copying" and "show warranty" for details.
    This GDB was configured as "x86_64-redhat-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <https://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
        <http://www.gnu.org/software/gdb/documentation/>.
     
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from /usr/bin/antimicrox...
    Reading symbols from .gnu_debugdata for /usr/bin/antimicrox...
    (No debugging symbols found in .gnu_debugdata for /usr/bin/antimicrox)
    [New LWP 787877]
    [New LWP 787875]
    [New LWP 787872]
    [New LWP 787876]
    [New LWP 787873]
    [New LWP 787871]
    [New LWP 787874]
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    Core was generated by `antimicrox --daemon --profile /home/fd/Gaming/Antimicro/satisfactory/satisfacto'.
    Program terminated with signal SIGABRT, Aborted.
    #0  0x00007f03b8ca52a2 in raise () from /lib64/libc.so.6
    [Current thread is 1 (Thread 0x7f038ffff640 (LWP 787877))]
    Missing separate debuginfos, use: dnf debuginfo-install antimicrox-3.2.0-1.fc34.x86_64
    (gdb) quit

**Comment by zpangwin** [comment]
[antimicro-daemon-coredump.tar.gz](https://github.com/AntiMicroX/antimicrox/files/7786347/antimicro-daemon-coredump.tar.gz)

**Comment by pktiuk** [comment]
These warnings are linked with https://github.com/AntiMicroX/antimicrox/issues/189
