### ISSUE TITLE
Possibly allow for a mini keyboard to appear on screen?

### ISSUE THREAD

**Issue by qwertious** [AntiMicroX/antimicrox#335]
Having a controller is amazing, but when you need to type it can be annoying to have to go up to a keyboard probably around 2x the size of the controller. It would be cool if you could have a small keyboard appear on screen that appears whenever you keybind a button on the controller to it. This way, you can just move the mouse around with one axis and press the keys with the left/right click buttons.

**Comment by pktiuk** [comment]
This is way out of scope of this app and would require too much messing with multiple compositors etc.

**Comment by pktiuk** [comment]
Moreover you SHOULD use template for new functionalities.

**Comment by tristan-cottam** [comment]
#298 would allow inputting characters in different ways. I'm specifically thinking about the now-superseded *Daisy Wheel* keyboard input for the *Steam Controller*, combining one of eight joystick directions with *A*, *B*, *X*, or *Y*.
