### ISSUE TITLE
Request and contact for a new language (Finnish) / translation help (not yet on the support list)

### ISSUE THREAD

**Issue by heidiwenger** [AntiMicroX/antimicrox#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

So to help, making a contact is required on the info section https://github.com/AntiMicroX/antimicrox#participation-in-the-translation-of-antimicrox -but there is no specific contact person of email to which reach out to? There are just a list of current translators. 

I'm doing it this way then. What's the next step to get translating as soon as possible? Thank you.

### Describe the solution you'd like

To provide a contact person on how to get translating.

**Comment by pktiuk** [comment]
Hi @heidiwenger   
Firstly you should check this issue: https://github.com/AntiMicroX/antimicrox/issues/1

And wiki site about translation https://github.com/AntiMicroX/antimicrox/wiki/Translating-AntiMicroX

**Comment by pktiuk** [comment]
In case of problems with please write in this issue. It will help to avoid spam.  
Have you figured out how to open this file with linguist?

**Comment by heidiwenger** [comment]
> In case of problems with please write in this issue. It will help to avoid spam. Have you figured out how to open this file with linguist?

![Screenshot from 2022-01-09 02-26-53](https://user-images.githubusercontent.com/82445727/148664516-e1bdf0e5-a3cd-48b1-aafb-a0598abb4088.png)

Yes i gladly got it! =) Here's what i was supposed to do (and to help others in similar situation)  - QT Linguist is inside the package qt5-tools-devel (installed from Software Center in Solus).

**Comment by pktiuk** [comment]
I will add this note to wiki about translation

**Comment by pktiuk** [comment]
Hi @heidiwenger ,
I updated translation instruction https://github.com/AntiMicroX/antimicrox/wiki/Translating-AntiMicroX.

I have also discovered one thing.  
Qt Linguist works better, when translated file is placed in project.  
You should download repository (git pull or just download zip), place `antimicrox_fi.ts` in `share/antimicrox/translations` and open then open it with linguist. It will properly render GUI elements for you.

**Comment by pktiuk** [comment]
BTW as mentioned in new wiki you should start with translating text associated with GUI. It will be more intuitive to start with it.

**Comment by pktiuk** [comment]
@heidiwenger   
Any progress?

**Comment by heidiwenger** [comment]
> @heidiwenger Any progress?

Yes and it's on the to-do list, its just that i'm on separate machines all the time and this QT Linguist "hassle" was solved only on one.. Well If there would be a web based solution on translating AntiMicroX i think this would have been translated already 😊 thanks for reminding too

**Comment by heidiwenger** [comment]
200 / 1292 done now

**Comment by pktiuk** [comment]
Could you submit what you have translated for now?  
I think I found new, better online tool for translating. https://hosted.weblate.org/projects/antimicrox/

**Comment by heidiwenger** [comment]
> @heidiwenger
> 
> Could you submit what you have translated for now? I think I found new, better online tool for translating. https://hosted.weblate.org/projects/antimicrox/

Ok i'll try to find it. I had forgotten the whole project for time being. Glad that a humane way of translating has been found??

**Comment by heidiwenger** [comment]
[antimicrox_fi.ts.txt](https://github.com/AntiMicroX/antimicrox/files/8501281/antimicrox_fi.ts.txt)

Should be there :/ (the system didnt let me attach a .ts file)

**Comment by pktiuk** [comment]
Added Finnish.  
You can see it there: https://hosted.weblate.org/projects/antimicrox/gui/fi/

**Comment by pktiuk** [comment]
You should be able to log in with github there.  
This would mark your contributions in repo history.

**Comment by heidiwenger** [comment]
> Added Finnish. You can see it there: https://hosted.weblate.org/projects/antimicrox/gui/fi/

Thank you very much. I'll try it on right away.

**Comment by pktiuk** [comment]
Let me know how does it work for you.   
Is everything set up correctly?

**Comment by heidiwenger** [comment]
> Let me know how does it work for you. Is everything set up correctly?

Yes it seems to work thus far! I'll let you know later if something comes up. This is very good, easy and straightforward way to translate this important piece of software now! Thanks so much!

**Comment by pktiuk** [comment]
I will close this issue for now.  
Changes you made so far will be included into the next release.   
Translate in your own pace. :)   

In case of any problems, let me know
