### ISSUE TITLE
Failing build for compilation with musl

### ISSUE THREAD

**Issue by Crilum** [AntiMicroX/antimicrox#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I don't know if this is really a bug, if you guys think it isn't, I'll post this on Discussions.

This only happens on my Github Actions workflow. I can successfully build AntiMicroX on my computer (A Raspberry Pi).

This is the bug I have when trying to run a GitHub Actions workflow that builds an AntiMicroX deb:

```
[ 95%] Building CXX object CMakeFiles/antimicrox.dir/src/gui/capturedwindowinfodialog.cpp.o
[ 96%] Building CXX object CMakeFiles/antimicrox.dir/src/eventhandlers/xtesteventhandler.cpp.o
[ 97%] Building CXX object CMakeFiles/antimicrox.dir/src/qtuinputkeymapper.cpp.o
[ 97%] Building CXX object CMakeFiles/antimicrox.dir/src/uinputhelper.cpp.o
[ 98%] Building CXX object CMakeFiles/antimicrox.dir/src/eventhandlers/uinputeventhandler.cpp.o
[100%] Building CXX object CMakeFiles/antimicrox.dir/qrc_resources.cpp.o
[100%] Linking CXX executable bin/antimicrox
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: CMakeFiles/antimicrox.dir/src/main.cpp.o: in function `termSignalSegfaultHandler(int)':
main.cpp:(.text+0x6ea): undefined reference to `backtrace'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: main.cpp:(.text+0x70d): undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/antimicrox.dir/build.make:2200: bin/antimicrox] Error 1
make[1]: *** [CMakeFiles/Makefile2:190: CMakeFiles/antimicrox.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
Error: Process completed with exit code 2.
```
The above can be found in full [here](https://github.com/Crilum/Github-Actions-App-Builds/runs/4794266423?check_suite_focus=true).

The way the workflow works is by running an Alpine Linux Docker container, installing dependencies, and building AntiMicroX to be packaged into a deb. You can view it [here](https://github.com/Crilum/Github-Actions-App-Builds/blob/main/.github/workflows/continuous-build-linux.yml).

Alpine uses `musl` instead of `glibc`, I don't know if that has anything to do with it...

### Expected Behavior

I expected it to, well, finish building successfully.. 

### Steps To Reproduce

1. Fork Crilum/Github-Actions-App-Builds
2. Go to the Actions tab in Github-Actions-App-Builds, and run the Continuous Build Linux action

### Environment

```markdown
- OS:muslcc/x86_64 Docker container
- AntiMicroX version: latest
```

**Comment by pktiuk** [comment]
This seems to be caused by missing [backtrace_symbols](https://linux.die.net/man/3/backtrace_symbols_fd) function  in musl [see](https://github.com/AntiMicroX/antimicrox/commit/04df192626098388f3ee2cc5e14019f0773fd349).

**Comment by Crilum** [comment]
@pktiuk Wow, quick response!

Yes, it does look like `musl` has no `backtrace_symbols` function..

There is a library called libbacktrace, that could probably be compiled and added to my workflow, and that might fix it. I'll probably try that.

**Comment by Crilum** [comment]
Well, earlier there was actually an error about `execinfo.h` not being available, which I solved by installing Alpine's `libexecinfo` package, and the description for the package is this:
>A quick-n-dirty BSD licensed clone of the GNU libc backtrace facility.

I wonder if that package isn't doing it job correctly..

**Comment by pktiuk** [comment]
@Crilum  
Does everything compile correctly now?

If yes, then please close this issue.

**Comment by Crilum** [comment]
I was not able to compile libbacktrace, but I'm working on something else right now, and can't give my priority to this, so I'll close this for now. This isn't really an AntiMicroX bug anyway..
