### ISSUE TITLE
Update controller map image

### ISSUE THREAD

**Issue by pktiuk** [AntiMicroX/antimicrox#346]
This is how it looks now:

![obraz](https://user-images.githubusercontent.com/45544416/149956902-2285e258-c2a2-4d34-b8bd-54363a4f331c.png)

It would be good to use some SVG image (or maybe something with better defined edges), because this image doesn't look very good with dark themes. (and is a bit outdated -  missing share button)

![controllermapping](https://user-images.githubusercontent.com/45544416/149957604-262f59c1-d0b1-4006-bd96-6b3056d6ce03.png)

**Comment by pktiuk** [comment]
In this case we should Use a bit different picture this time.    
As @Igetin mentioned in https://github.com/AntiMicroX/antimicrox/issues/307#issuecomment-1261391402

> @pktiuk Can you reopen this issue? SDL **does**, in fact, support the share button of the controller. The "not recognized by SDL" error message was a red herring, which is caused by the Linux kernel driver translating the share button press into a (non-joypad) key press, resulting in SDL showing _both_ the button press _and_ the error for the unrecognized key press.
> 
> AntiMicroX's log output was also lacking because of the kernel driver not directly supporting the button.
> 
> As discovered [here](https://github.com/libsdl-org/SDL/issues/6296), AntiMicroX does not recognize the share button because it is not handling the [`SDL_CONTROLLER_BUTTON_MISC1` button type](https://wiki.libsdl.org/SDL_GameControllerButton).
> 
> The SDL mapping string looks like this when created with their mapping tool:
> 
> ```
> 050000005e040000130b000007050000,Xbox Series X Controller,platform:Linux,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,misc1:b15,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:+a4,
> ```
> 
> The `misc1:b15` part there is the mapping for `SDL_CONTROLLER_BUTTON_MISC1`.
> 
> Another closely related thing: I think the controller mapping dialog of AntiMicroX should be updated to support this additional button as well. The button should be shown in the mapping list and in the controller image.
> 
> Here is how SDL's official mapping tool displays it: <img alt="" width="340" src="https://user-images.githubusercontent.com/14016863/192866293-b8ec8941-5162-4f02-83c0-b474bed1447e.png">
> 
> Of course, I can make this into a separate issue, if needed.

**Comment by Igetin** [comment]
Feel free to use the following SVG, on which I spent 5 minutes. :P

![controller](https://user-images.githubusercontent.com/14016863/194081533-1a4360d8-74b8-4d93-8707-de4fe0747713.svg)

Based on [this original image](https://commons.wikimedia.org/wiki/File:Xbox_Controller.svg).

**Comment by pktiuk** [comment]
Thank you, this will come in handy for sure.
