### ISSUE TITLE
Nintendo Switch gamepad compatibility

### ISSUE THREAD

**Issue by Daebis** [AntiMicroX/antimicrox#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

hello devs, I have three controllers
an "official" nitendo switch pro
a Spirit of gamer and a "noname" from aliexpress "n-sl wireless controller".

they are all three recognized without worries on the pc in bluetooth
but the recognition in antimicroX is not optimal, some button are not on the mapping. 
I remain at your disposal if you need me to perform future tests. 

Dae.anthony@gmail.com
or Dae#5125 on discord

### Describe the solution you'd like

a menu askin it's a playstation/xbox/switch gamepad

### Additional context

have a nice day <3

**Comment by pktiuk** [comment]
Does your kernel version support Switch Controllers (I assume you use Linux)? AFAIK it was added recently, maybe in 5.16

**Comment by Daebis** [comment]
OS: Lubuntu 18.04.6 (with lxde)
Kernel: Linux version 4.15.0-163-generic (buildd@lcy01-amd64-021) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021

and yes  

yes the controller is managed, but the disign of the card
and the - key is not counted on the mapping.

a switch controller has

2 triggers.
2 bumper
2 stick
- / +
Home
printscreen
4 button function (xyab)
and a directional cross

the image displayed on antimicroX is that of an Xbox

**Comment by pktiuk** [comment]
Switch controller is not fully supported on this kernel, so it may not work correctly  https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.16-HID&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Phoronix+%28Phoronix%29

**Comment by pktiuk** [comment]
Displayed image is always showing Xbox 360controller, because this is default, reference controller for xinput.  
Every controller is mapped to an xbox 360 one.
