### ISSUE TITLE
Tray icon is invisible (due to white background) on Windows 7/8 when not showing on tray (hide in collapsed menu)

### ISSUE THREAD

**Issue by RadarNyan** [AntiMicroX/antimicrox#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/2091529/151756911-389d279a-3bff-4aa0-abdb-76c5260a6f07.png)
I don't have Windows 8/8.1 on hand but I think they would have the same problem.

### Expected Behavior

I think it's better to allow user to choose an icon instead of just [apply a darker icon for specific enviroment](https://github.com/AntiMicroX/antimicrox/pull/93).

I personally prefer the old AntiMicro icon, and it works just fine on any background, why not just include it as an option?

**Comment by pktiuk** [comment]
This fix will appear with the next release.
