### ISSUE TITLE
typo in english translation

### ISSUE THREAD

**Issue by ayunami2000** [AntiMicroX/antimicrox#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/24785136/152556617-e08d3344-4d7c-42c8-bc40-8d5f2a819296.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/24785136/152556745-6bd4bd93-54a0-4bef-86e1-900a9410f3a3.png)

### Steps To Reproduce

1. Click to assign button `X`
2. Click `Advanced`
3. See typo

### Environment

```markdown
- OS: Microsoft Windows 10 Education 10.0.19043 Build 19043
- AntiMicroX version: 3.2.1
```

### Anything else?

.

**Comment by pktiuk** [comment]
Thank you for your report

This issue is already fixed (will be in the next release)
PR: https://github.com/AntiMicroX/antimicrox/pull/339
