### ISSUE TITLE
[Feature Request]: Add support for motion sensors

### ISSUE THREAD

**Issue by mmmaisel** [AntiMicroX/antimicrox#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Please add support for mapping motion sensors in Playstation 4/5 and Switch Pro controllers. Since Linux 5.12 there is an official driver for the Playstation 5 controller. The switch Pro controller has a mainline driver since Linux 5.16. SDL2 supports accessing motion sensors since version 2.0.14 with the sensor API.

### Describe the solution you'd like

It would be nice if it is possible to map this inputs in the AntimicroX GUI in a new section after "Sticks" and "DPads". For example, gyro can be mapped as mouse like a stick for precise aiming and the accelerometer can be used to lean in game by tilting the controller.

### Describe alternatives you've considered

Mapping gyro is possible via command line and editing config files with the tool JoyShockMapper. But this tool has only second class Linux support and no GUI.

### Additional context

Sensor support of a controller can be checked with the attached example program:

Possible output:
```
Found 2 controllers
Nintendo Switch Pro Controller Gyro: 1 Accel: 1
Xbox One Wireless Controller Gyro: 0 Accel: 0
```
[sdlsens.txt](https://github.com/AntiMicroX/antimicrox/files/8034286/sdlsens.txt)

**Comment by pktiuk** [comment]
That's a great idea, but it would require tons of work, so this one will have to wait. :(
