### ISSUE TITLE
Github Release task for Windows can't find cmake

### ISSUE THREAD

**Issue by pktiuk** [AntiMicroX/antimicrox#378]
During stage `Configure Cmake` There is error:

```
Run cmake -DCMAKE_BUILD_TYPE=Release -DCHECK_FOR_UPDATES=ON -DANTIMICROX_PKG_VERSION="GitHub Windows Release" -B 'D:\a\antimicrox\antimicrox'/build
D:\a\_temp\5f82122d-569c-41ef-82a3-c9baedf3fdf5: line 1: cmake: command not found
Error: Process completed with exit code 127.
```

There is also another problem

```
CPack: Create package
CPack Error: Problem running NSIS command: "C:/msys64/mingw64/bin/makensis.exe" "D:/a/antimicrox/antimicrox/build/_CPack_Packages/win64/NSIS/project.nsi"
Please check D:/a/antimicrox/antimicrox/build/_CPack_Packages/win64/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: antimicrox
```

**Comment by pktiuk** [comment]
@avinal   
Could you investigate these problems?   
It would be handy to add log collecting in case of nsis fail.

**Comment by avinal** [comment]
Can you please link or paste the whole log where this is happening, I need to recreate this scenario before I can debug it.

**Comment by pktiuk** [comment]
It is on my GitHub fork  
https://github.com/pktiuk/antimicrox/runs/5175144222?check_suite_focus=true

I would recommend creating fork on github and creating release there.

**Comment by avinal** [comment]
I will pull your respective branch, since I already have the fork. Thanks

**Comment by pktiuk** [comment]
Do you know what caused this problem?  
I would like to create new release and this is blocker for Windows.

**Comment by avinal** [comment]
Hey @pktiuk, I am not sure why it can not find CMake but the NSIS issue seems to be originated due to `-` in component/file/folder names, this is a known bug and hasn't been solved yet. I am trying to find which change did this. For the safe side, while using CMake, we should stick to the C-style variable naming convention, aka `[a-z][A-Z][0-9]` and underscore. Since CMake is written in C and C++ itself, these issues may happen.

**Comment by avinal** [comment]
I can't find what breaks this thing, 😞 I tried a few things but the same problem.

**Comment by pktiuk** [comment]
Could you at least add uploading logs in case of this kind of error?

```
 Please check D:/a/antimicrox/antimicrox/build/_CPack_Packages/win64/NSIS/NSISOutput.log for errors
```

**Comment by avinal** [comment]
Sure I will collect the logs.

**Comment by pktiuk** [comment]
> Sure I will collect the logs.

Just to be clear. I am talking about automated collecting logs from NSIS in case of failure. :)

**Comment by avinal** [comment]
Yepp, I will add an upload artifact step in case of failure.

**Comment by avinal** [comment]
I think it would be nice to add a log collecting step in case of failure. I am already working on it, will open a PR soon.
