### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by mrk310310** [AntiMicroX/antimicrox#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Playing Stalker, AntiMicroX crashes during gameplay, the program simply quits. 

### Environment

```markdown
- OS:Win 10
- AntiMicroX version:latest
```

### Anything else?

Also this issue is still present in AntiMicroX: https://github.com/AntiMicro/antimicro/issues/160

**Comment by pktiuk** [comment]
Closing due to lack of response
