### ISSUE TITLE
"Empty Battery" indicator pops at 10 minute intervals for wired PS4 controller

### ISSUE THREAD

**Issue by batzradio** [AntiMicroX/antimicrox#381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a HORIPAD mini4 PS4 controller that I've used occasionally, and since reconnecting the controller I've gotten "Empty Battery" prompts repeatedly, in spite of my controller being a hardwired pad. 

### Expected Behavior

I'd expect that the software would see that my controller has a USB connection.

### Environment

```markdown
- OS: Windows 10 Pro Build 19044.1526
- AntiMicroX version: 3.2.1
```

### Anything else?

I did find something of a curious workaround for this issue, DS4Windows and HidHide essentially hides the PS4 pad from AntiMicroX (which was previously only being used for a second pre-Xinput controller providing hotkey functionality). Still, this seems like something to look at if there's a chance to.

**Comment by pktiuk** [comment]
This seems to be problem with this gamepad.  
It reports itself as device with empty battery instead of a wired one.

**Comment by pktiuk** [comment]
But you can disable Battery notifications by changing this in settings:
![obraz](https://user-images.githubusercontent.com/45544416/156891520-a7732573-ca1e-4e0a-882b-e375f7016166.png)
