### ISSUE TITLE
How can I save 2 config into 1 file & why auto profile is not working properly

### ISSUE THREAD

**Issue by ds47x** [AntiMicroX/antimicrox#385]
I cant save 2 config into 2 file and I don't  know why but I think is a bug but auto profile don't work actually any solution will help

**Comment by joaoasilva** [comment]
auto load last opened profile is not working for me also

**Comment by pktiuk** [comment]
Closing, because of way of reporting this bug.  
I won't accept any bug reports not using bug template.

![obraz](https://user-images.githubusercontent.com/45544416/155535105-3ccba737-b841-49ea-bbd6-7c550ccb5587.png)
