### ISSUE TITLE
missing licence for SDL_GameControllerDB

### ISSUE THREAD

**Issue by mirabilos** [AntiMicroX/antimicrox#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

3.2.2 adds two new files (relative to 3.1.4) in `share/` that originate from SDL_GameControllerDB without reproducing their licence

### Expected Behavior

The [licence](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/LICENSE) is also added to `share/` because it “may not be removed”

### Steps To Reproduce

Try to package new version for Debian, fail due to legal issues

### Environment

```markdown
- OS: Debian
- AntiMicroX version: 3.2.2
```

**Comment by pktiuk** [comment]
Thanks for informing about this.  
I hope this PR helped with proper packaging

**Comment by mirabilos** [comment]
Thanks, it will!

Missing licences for stuff in the upstream tarballs is one thing I cannot normally just patch in downstream: Debian distributes the sources as well, and the Debian patches are in a separate file, so people could just download the upstream tarball from Debian mirrors, so that needs to be complete-in-ipso, licence-wise.

So I’ll package the next release for Debian then.

**Comment by pktiuk** [comment]
ACK,  
I will ping you with the next release

**Comment by pktiuk** [comment]
@mirabilos   
New release with missing file: https://github.com/AntiMicroX/antimicrox/releases/tag/3.2.3  
You can now update this package :)

**Comment by mirabilos** [comment]
Paweł Kotiuk dixit:

***@***.***   
>Is there any chance for update?

Oh… yes, when I find time and headspace for it, it’s a heatwave right now.
I’ll try to remember.

**Comment by pktiuk** [comment]
@mirabilos   
Maybe it would be better to just archive or mark this package as unmaintained?
