### ISSUE TITLE
spurious .autosave file

### ISSUE THREAD

**Issue by mirabilos** [AntiMicroX/antimicrox#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`share/antimicrox/translations/antimicrox_br.ts.autosave` exists

### Expected Behavior

I’m pretty sure it shouldn’t?

### Steps To Reproduce

Look at the code

### Environment

```markdown
- OS: Debian
- AntiMicroX version: 3.2.2
```

**Comment by pktiuk** [comment]
You are right.  
I will soon remove it.
