### ISSUE TITLE
Dark Mode on Windows?

### ISSUE THREAD

**Issue by Jacob-Darka** [AntiMicroX/antimicrox#393]
### Use discussion module to ask question.

Can I enable the dark mode on windows?
There's a disclaimer on the main GitHub page that states: "Theme may depend on your system configuration."
Does that mean dark mode isn't available on windows?

**Comment by pktiuk** [comment]
![obraz](https://user-images.githubusercontent.com/45544416/156011446-9ebb63f6-3c38-44fe-860e-a9a5be42a2b5.png)
