### ISSUE TITLE
auto profile not working with sony navigation controller

### ISSUE THREAD

**Issue by kaboom36** [AntiMicroX/antimicrox#395]
hello! I have attached a video showing the issue in action, I am connecting the controller over USB as I am unable to connect it over bluetooth due to a dead battery 
![Peek 2022-03-01 11-53](https://user-images.githubusercontent.com/11545895/156217401-e9e969ba-c7c4-4920-8bec-1aa51c1131f4.gif)

OS: Ubuntu 20.04.4 LTS
Version: antimicrox 3.2.2

**Comment by pktiuk** [comment]
Closing due to lack of proper description of problem and not using proper bug issue template.
