### ISSUE TITLE
"None" button causes crash with PS5 gamepad

### ISSUE THREAD

**Issue by vpoko** [AntiMicroX/antimicrox#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In version 3.2.2 with a PS5 controller, AntiMicroX crashes (actually fails to respond) when I attempt to set any button to NONE.
![image](https://user-images.githubusercontent.com/39971752/156452849-0bd48210-73fa-4b8f-a1ea-3571518b6b37.png)

### Environment

```markdown
- OS: Windows 10
- AntiMicroX version: 3.2.2
```

**Comment by pktiuk** [comment]
Does it happen with other gamepads?  
How is connected this gamepad?

Please provide proper step-by step guide to reproduce.

**Comment by vpoko** [comment]
No, it only occurs with a PS5 controller and only when its plugged in through USB (it doesn't happen when it's connected wirelessly). To reproduce:
1. Click on any button in AntiMicroX to set its function.
2. Click None. The program immediately freezes.

**Comment by pktiuk** [comment]
I will borrow PS5 gamepad from a friend and try to reproduce this, but this issue doesn't seem to be AntiMicroX problem. I would bet something with Windows drivers or SDL2 is wrong.

**Comment by vpoko** [comment]
Understandable. Thanks for looking into it (and for AntiMicroX in general).

**Comment by instinctualjealousy** [comment]
I've had various sporadic hangs (the only way to get out is to terminate) on Windows 3.2.2, and the ones I remember most are with the NONE button. All of them happened during mapping of buttons, though. I use an Xbox 360 wireless controller with unofficial receiver (running official driver). I doubt it's a specific controller problem, but some controllers might be more likely to cause the issue for some reason.

**Comment by pktiuk** [comment]
@vpoko  eerrrrr
I once reproduced this bug on version `2.2.2`, but I am unable to reproduce it with the latest AntiMicroX (`2.2.4`)

Could you retest with the latest version?

**Comment by pktiuk** [comment]
Closing due to lack of response

**Comment by vpoko** [comment]
No, it only occurs with a PS5 controller and only when its plugged in
through USB (it doesn't happen when it's connected wirelessly). To
reproduce:
1. Click on any button in AntiMicroX to set its function.
2. Click None. The program immediately freezes.

**Comment by pktiuk** [comment]
Have you tested it with the latest version?

**Comment by vpoko** [comment]
Hi,

Sorry for not getting back to you sooner. The issue is no longer occurs
with 3.2.5.
