### ISSUE TITLE
I can not install from Fedora repositories !

### ISSUE THREAD

**Issue by Nokia808** [AntiMicroX/antimicrox#40]
Hi. I'm Fedora user & 1st know about your application when I saw it as a PR for FlatHub.

I read this repository & it give instruction to install it on Fedora as following:
`# dnf install antimicrox`

I run the above command but I got the following output:

```
sudo dnf install antimicrox
Last metadata expiration check: 1:21:19 ago on Tue 15 Sep 2020 11:07:18 AM GMT.
No match for argument: antimicrox
  * Maybe you meant: antimicroX
Error: Unable to find a match: antimicrox
```

But when I searched about "antimicroX" I found a package for a dead application - see bellow:

```
$ dnf info antimicroX
Last metadata expiration check: 0:19:43 ago on Tue 15 Sep 2020 12:10:33 PM GMT.
Available Packages
Name         : antimicroX
Version      : 3.0
Release      : 2.20200617gitc6d79.fc32
Architecture : x86_64
Size         : 175 k
Source       : antimicroX-3.0-2.20200617gitc6d79.fc32.src.rpm
Repository   : updates
Summary      : Graphical program used to map keyboard buttons and mouse controls
             : to a gamepad
URL          : https://github.com/juliagoda/antimicroX
License      : GPLv3+
Description  : antimicroX is a graphical program used to map keyboard keys and
             : mouse controls to a gamepad. This program is useful for playing
             : PC games using a gamepad that do not have any form of built-in
             : gamepad support. antimicroX is a fork of AntiMicro which was
             : inspired by QJoyPad but has additional features.
```

I searched used the following site  https://koji.fedoraproject.org/koji/packages
I saw antimicroX & antimicrox & last one packaged by you !! - see the following:
https://koji.fedoraproject.org/koji/packageinfo?packageID=31474
https://koji.fedoraproject.org/koji/packageinfo?packageID=32302

What is wrong ??

I'm on Fedora 32 X64 bit Cinnamon Edition.

**Comment by gombosg** [comment]
Hi, the `antimicrox` update is still in Bodhi, so it's not yet available in the stable repos.
https://bodhi.fedoraproject.org/updates/FEDORA-2020-23845d9c7c

I just submitted it today.
Sorry for the confusion. Feel free to test and kive some karma. :slightly_smiling_face:

**Comment by Nokia808** [comment]
@gombosg 
Dear developer, only one concern: which you recommend for long term installation, flatpak package or .rpm package for such Fedora user like me ? I did not confronted by such case when the packager for both type is the same person & above that is the developer himself ..... Which is more secure & better performance ?

**Comment by gombosg** [comment]
Hi, for this simple app, they are nearly equal. I like native RPMs because they take up very little disk space and often have better font rendering, but this flatpak will also be small.
Flatpak in general is a good system.

**Comment by Nokia808** [comment]
@gombosg 
I see. Thank you for clarification.
