### ISSUE TITLE
Mouse movement not working

### ISSUE THREAD

**Issue by TTVHaroldTheCartoon** [AntiMicroX/antimicrox#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i am setting the right joystick to mouse up/down/left/right and nothing happens my cursor doesn't move and my game character doesn't either. This is the only thing that isn't working

### Expected Behavior

it would work, my character would turn

### Steps To Reproduce

click "R Stick" and set it to mouse (normal) in presets

### Environment

```markdown
- OS: windows 10
- AntiMicroX version: https://github.com/AntiMicroX/antimicrox/releases/download/3.2.2/antimicrox-3.2.2-AMD64.exe
```

**Comment by pktiuk** [comment]
Could you collect some logs from this bug? https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs  

Maybe something is not initialized properly.

**Comment by TTVHaroldTheCartoon** [comment]
so i realized the problem wasn't the program it was the game i was trying
to play. For some reason Valorant blocks a secondary mouse and it sees the
app as another mouse

**Comment by pktiuk** [comment]
Good to know
