### ISSUE TITLE
Joystick calibration is broken

### ISSUE THREAD

**Issue by TooterTutor** [AntiMicroX/antimicrox#407]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I have a Nintendo Switch JoyCon controller attached. When the joystick was set to mouse position and the joystick was angled down, it would move the mouse cursor down until the joystick was angled down again. Another thing that doesn't work is when you are mapping the joystick X and Y axis, it will only accept one direction for either direction in the X or Y axis.

### Expected Behavior

I expected that you would be able to calibrate the controller Joysticks when mapping the buttons. I also expected that you could edit the SDL Game Controller Mapping String.

### Steps To Reproduce

1. Go to Game Controller Mapping (Joy-Con (R))
2. Map Right Stick X (Move Joy-Con Stick to the left or right)
3. Does not allow Left & Right for X axis. Only one way.

### Environment

```markdown
- OS:Raspberry Pi (Bullseye)
- AntiMicroX version: 3.1.4
```

**Comment by pktiuk** [comment]
Have you tried with the newer AntiMicroX version?  
`3.1.4` is pretty old

**Comment by mmmaisel** [comment]
I came across this during implementation of #375 and can confirm that something in the calibration does not behave as expected.
In my case, I was unable to progress to the third step where the stick is moved to right down position. It was only possible to confirm the calibration but with obviously wrong values.

**Comment by pktiuk** [comment]
@mmmaisel   
Could you share your setup? (System and used gamepad)  
Is that issue specific to JoyCons or does it also happen with other gamepads?

**Comment by mmmaisel** [comment]
@pktiuk
I use Nintendo Switch Pro and xBox 360 controllers on Arch Linux. These controllers both work perfectly in multiple games. Just the calibration in Antimicrox behaves strange while the raw values in the calibration window look good. Mapping the sticks to mouse movement with Antimicrox works as well but spring mode does nothing at all.

I think the original issue is a different one than my observations. I can fix the calibration issue I found during code reading later when I polish my sensor patch set and merge the separate sensor calibration dialog with the main one.

@TooterTutor
What mouse settings have you used exactly? Cursor or spring mode?

**Comment by mmmaisel** [comment]
I looked at the calibrations code and it seems to do almost nothing. My expectation would be that calibration compensates hardware inaccuracies by determining and correcting offset and gain of the axes. Instead, it sets unused (according to git grep) member variables "axis_max_cal", "axis_min_cal" and "axis_center_cal", saves a text calibration report and sets dead and max zones of the stick.

Is real calibration a desirable feature for AntimicroX?

**Comment by pktiuk** [comment]
That's interesting.   

> Is real calibration a desirable feature for AntimicroX?  

I think it would be useful to have proper calibration. :)

> Instead, it sets unused (according to git grep) member variables "axis_max_cal", "axis_min_cal" and "axis_center_cal", saves a text calibration report and sets dead and max zones of the stick.

At first glance they seem to be used.  
Values like `axis_max_cal`  are obtained via methods like `JoyAxis::getAxisMaxCal()`, which are used in many places in code.

**Comment by mmmaisel** [comment]
You're right, I overlooked the getters. But nevertheless center seems still unused to me and min/max is only used to clamp the values between min and max.

I think I could easily fix this with my existing work from #416, but I'm not sure what's the best approach. Should I get the sensors change done first with a different calibration dialog just for sensors or should I fix the existing calibration first and integrate the sensors in it. What's your opinion about this @pktiuk?

**Comment by pktiuk** [comment]
> Should I get the sensors change done first with a different calibration dialog just for sensors or should I fix the existing calibration first and integrate the sensors in it.     

Do you think adding a dedicated calibration dialog would add any value for users?    
What would be the difference between regular calibration dialog and sensor calibration dialog?

**Comment by mmmaisel** [comment]
> Do you think adding a dedicated calibration dialog would add any value for users? What would be the difference between regular calibration dialog and sensor calibration dialog?

You're right, having two calibration dialogs would be confusing for users.
I temporarily added the new one for the sensor calibration workflow to avoid the issues described earlier here. Adding a fixed version of the existing stick calibration to the new dialog and dropping the old one would be easy after the sensor PR is merged. But this causes temporarily two calibration dialogs because it would depend on the sensors change.

I guess the better way is fixing the existing one first as this also decreases the size of the sensors PR.

**Comment by pktiuk** [comment]
Could you also add some doxygen descriptions for some of the classes you have worked with? (the ones which you got familiar with and are too big to understand at first glance)    
It would make understanding code much easier for future developers. (and it would improve [online docs](https://antimicrox.github.io/doxygen/) )  

Anyway. You don't have to do it if, you don't want to or don't have time.

**Comment by pktiuk** [comment]
It should be fixed by #441   
Change will be included into the next release
