### ISSUE TITLE
Populating with multiple joysticks

### ISSUE THREAD

**Issue by oldtools** [AntiMicroX/antimicrox#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Antimicrox is populating with like 17 joysticks.

### Expected Behavior

i only have one joystick.

### Steps To Reproduce

Not sure how to reproduce this.  here's the log:
🟢INFO	"Using SendInput as the event generator."
❗WARN	File with game controller mappings  "C:/Program Files/AntiMicro/../share/antimicrox/gamecontrollerdb.txt"  does not exist
🟢INFO	Created new GameController:
			Index:            1
			  UniqueID:         030000005e040000130b00001305720011182835
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2835
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            2
			  UniqueID:         030000005e040000130b00001305720011182837
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2837
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            3
			  UniqueID:         030000005e040000130b00001305720011182838
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2838
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            4
			  UniqueID:         030000005e040000130b00001305720011182839
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2839
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            5
			  UniqueID:         030000005e040000130b00001305720011182840
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2840
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            6
			  UniqueID:         030000005e040000130b00001305720011182841
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2841
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            7
			  UniqueID:         030000005e040000130b00001305720011182842
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2842
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            8
			  UniqueID:         030000005e040000130b00001305720011182843
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2843
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            9
			  UniqueID:         030000005e040000130b00001305720011182844
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2844
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            10
			  UniqueID:         030000005e040000130b00001305720011182845
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2845
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            11
			  UniqueID:         030000005e040000130b00001305720011182846
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2846
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            12
			  UniqueID:         030000005e040000130b00001305720011182847
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2847
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            13
			  UniqueID:         030000005e040000130b00001305720011182848
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2848
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            14
			  UniqueID:         030000005e040000130b00001305720011182849
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2849
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            15
			  UniqueID:         030000005e040000130b00001305720011182850
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2850
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            16
			  UniqueID:         030000005e040000130b00001305720011182851
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2851
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Created new GameController:
			Index:            17
			  UniqueID:         030000005e040000130b00001305720011182852
			  GUID:             030000005e040000130b000013057200
			  VendorID:         1118
			  ProductID:        2852
			  Product Version:  1299
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
			
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Loading device settings for:  "Xbox Series X Controller"
🟢INFO	Change joystick  "Xbox Series X Controller"  profile to:  "C:/Users/***/Desktop/testing/profiles/Toziuha Night Draculas Revenge/MediaCenter.gamecontroller.amgp"
⚪VERBOSE	Loading config file: C:/Users/***/Desktop/testing/profiles/Toziuha Night Draculas Revenge/MediaCenter.gamecontroller.amgp succeeded.

### Environment

```markdown
- OS: Windows11
- AntiMicroX version: 3.2.2
```

### Anything else?

Let me know if there's something i can do to help

**Comment by pktiuk** [comment]
Could you also check this gamepad with other apps like `qjoypad` or `jstest-gtx` (to check if gamepad/system config is source of problems)?   
I haven't tested AntiMicroX with Windows yet.

**Comment by pktiuk** [comment]
Closing due to lack of feedback
