### ISSUE TITLE
Doesn't detect controller when launched from an rdp session

### ISSUE THREAD

**Issue by zloyle** [AntiMicroX/antimicrox#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Gamepad is not detected over an rdp connection. Works fine locally and over vnc. xpadder also works as expected over rdp.

### Expected Behavior

Should detect remote and allow mapping as normal.

### Steps To Reproduce

run ds4windows -> run antimicrox -> no gamepads found

### Environment

```markdown
- OS:
- AntiMicroX version:
```

**Comment by pktiuk** [comment]
It seems to be SDL Issue.   
Could you check your config also with app [gamepadtool](https://generalarcade.com/gamepadtool/)?

**Comment by pktiuk** [comment]
Closing due to lack of feedback
