### ISSUE TITLE
[Question] Is "antimicro" profiles is compatible with antimicrox ?

### ISSUE THREAD

**Issue by Nokia808** [AntiMicroX/antimicrox#41]
Dear I'm currently using "antimicro" on my Fedora since many years ago (about 3 or 4 years ago). Soon your program will be available to me. 

Can I import (by copy/past) antimicro's profiles files from it's cache folder to that of antimicrox ? Are such profiles compatible ?

**Comment by pktiuk** [comment]
Yes

**Comment by Nokia808** [comment]
@pktiuk 
@gombosg 
Thank you. Issue is resolved.
