### ISSUE TITLE
Loading a profile opens to OneDrive folder by default

### ISSUE THREAD

**Issue by FabTheZen** [AntiMicroX/antimicrox#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the controller profile selection area, clicking on the "Load" button opens up the default OneDrive folder
![image](https://user-images.githubusercontent.com/2886309/161856621-b099b7f6-b045-4c96-b0af-bfc48b2c1c26.png)
![image](https://user-images.githubusercontent.com/2886309/161859817-5f472010-a63a-465e-973c-c0873b02ec13.png)

### Expected Behavior

Clicking on "Load" should open either the program folder or the last folder opened

### Steps To Reproduce

1. Open AntiMicroX
2. Connect a controller
3. Click on Load

### Environment

```markdown
- OS: Windows 10 version 21H2
- AntiMicroX version: 3.2.2
```

### Anything else?

I opened this issue after asking in the discussions, https://github.com/AntiMicroX/antimicrox/discussions/410

**Comment by pktiuk** [comment]
Could you share your file with settings?

It should be placed in:

`C://Users/YOURNAME/AppData/Local/antimicrox/antimicrox_settings.ini`

**Comment by FabTheZen** [comment]
Sorry for my late reply, here's my settings.ini: https://pastebin.com/HajLHHDS

**Comment by pktiuk** [comment]
Have you tried to change this setting?

![obraz](https://user-images.githubusercontent.com/45544416/163842773-56a249c9-e583-4862-9fc3-a02628d0a4b3.png)

Do you have `L` drive in your system?
`DefaultProfileDir=L:/Users/FabTheZen/Documents` Maybe `L` drive is mapped to OneDrive

**Comment by FabTheZen** [comment]
That profile directory is not the OneDrive folder in my system, that's `L:\Users\FabTheZen\OneDrive`, but changing that setting actually proved to fix my issue, the actual default folder used by the program seems to not be the same as displayed in the settings, but once you change it, it does work. I just didn't think of trying to change the folder, my bad!
Thank you so much for your patience and help.

**Comment by pktiuk** [comment]
I will close it for now.  
I will reopen in case of another report
