### ISSUE TITLE
Please release a Win Installer/.exe

### ISSUE THREAD

**Issue by H8DCarnifeX** [AntiMicroX/antimicrox#42]
Could you please release a Installer or .exe of this beautiful Project?
For now i used Antimicro and just found this new Project, but sadly i cant compile generally.
Antimicro has an .msi Installer & it would be nice, if you could add this Option, too.
Thanks for your Time and Work!
Greetings

**Comment by gombosg** [comment]
Thanks for submitting this issue! Currently we indeed don't have a Windows build, but it's a goal to restore it.

Duplicate of #4, closing.
