### ISSUE TITLE
[Windows?] Auto Profile page not saving any changes at all (not the no-path bug)

### ISSUE THREAD

**Issue by instinctualjealousy** [AntiMicroX/antimicrox#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AntiMicroX's Auto Profile page is currently not saving any information whatsoever upon hitting "OK" (or at all).

### Expected Behavior

Auto Profile to store its configuration upon hitting "OK" (or in realtime, depending on developer intent) including Active setting, default profile and other profiles.

### Steps To Reproduce

1. Go to "Options" -> "Settings"
2. Go to "Auto Profiles" sub menu on left pane
3. Click in the "Active" checkmark and set the default profile to something
4. Optionally add a custom profile with path to executable
5. Hit "OK"
6. Repeat steps 1 and 2
7. The page lost all settings, they were never put into effect

### Environment

```markdown
- OS: Windows 10 21H2
- AntiMicroX version: 3.2.2
```

### Anything else?

I don't believe this is #252 or what #387 was believed to be. I do wonder if the OP of 387 was experiencing my issue but weren't clear enough about their problem so it was getting conflated with 252 by replies. I do not use window titles on my profile mapping- I use executable paths, so I don't believe this is the no-path bug.

This is such an egregious bug that either I'm running into something system specific (not the first time, this is a well lived-in system), or it's probably Windows-specific as it would've definitely been caught in the mainline Linux development this thing's been going through for years. I can confirm the old pre-fork antimicro worked as expected in regard to auto profiles, but I understand this took a ton of work just to get compiling for Windows again.

**Comment by joaoasilva** [comment]
Can confirm this bug.
Same happens to me on Windows

**Comment by lopiv2** [comment]
Same happens to me, Windows too

**Comment by cr1315** [comment]
Same here.

**Comment by sonofevil** [comment]
Same issue.

**Comment by nitz** [comment]
Also having the same behavior. I can even see loaded/saved get associated with controllers in the `%localappdata%\antimicrox\antimicrox_settings.ini` on exit, but upon re-launching the application, those profiles are never loaded (and later blanks will be saved to the ini.)

**Comment by R3TZ3V** [comment]
For me not only the Auto Profile does not save any settings, for example checking option "Key Repeat" does not work for me:
- I check it in options, then OK at the bottom
- when I open options again the "Key Repeat" checkbox is not checked

What is funny, is when I have "Lunch At Windows Startup" option checked and then check the "Key Repeat". After opening options again both are not checked ("Lunch At Windows Startup" and "Key Repeat").
