### ISSUE TITLE
Options -> Game Controller Mapping (CTRL+M) doesn't do anything

### ISSUE THREAD

**Issue by instinctualjealousy** [AntiMicroX/antimicrox#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As of right now, if you use the drop-down menu to get to the SDL2 Controller Mapping page, it doesn't work. The CTRL+M shortcut also does nothing.

You can however get to the controller mapping page successfully with the dedicated "Controller Mapping" button in the lower left corner of an active controller's page, so the actual functionality isn't broken.

### Expected Behavior

Both clicking the option in menu and the keyboard shortcut for it should open the Controller Mapping window for the currently active controller.

### Steps To Reproduce

1. Go to "Options" -> "Game Controller Mapping" and/or invoke CTRL+M with AntiMicroX in focus
2. Nothing happens

### Environment

```markdown
- OS: Windows 10 21H2
- AntiMicroX version: 3.2.2
```

**Comment by pktiuk** [comment]
Shortcut and button you mentioned is broken, but button `Controller Mapping` (with the same functionality) works properly.  

![obraz](https://user-images.githubusercontent.com/45544416/164530911-2f1bf7f9-0afb-4427-9a1b-14e7d3177646.png)

Probably something is not linked properly.  
I will check it out.  
But TBH, I am not sure whether such a redundant button with shortcut is needed.

**Comment by instinctualjealousy** [comment]
I was about going to propose getting rid of the redundancy, but I didn't feel it met the scope of the actual bug report. I figured "removing redundancy" would be a possible conclusion to the report, anyway. Thanks for looking into it!
