### ISSUE TITLE
QList::toSet is deprecated

### ISSUE THREAD

**Issue by mmmaisel** [AntiMicroX/antimicrox#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a compiler warning about deprecation of QList::toSet.

### Expected Behavior

No warnings.

### Steps To Reproduce

Compile from source.

### Environment

```markdown
- OS: Arch Linux (22. April 2022)
- AntiMicroX version: git 85bbc6bf
```

### Anything else?

QList::toSet is deprecated since Qt 5.14 but the suggested alternative
QSet(list.cbegin(), list.cend()) only exists since Qt 5.14.
This causes compilation errors on Ubuntu 20.4 and earlier if fixed.

**Comment by pktiuk** [comment]
Linked with: https://github.com/AntiMicroX/antimicrox/issues/318

**Comment by pktiuk** [comment]
In this case, the only viable solution looks like this

```cpp
#if QT_VERSION >= QT_VERSION_CHECK(5, 14, 0)
                        QSet<AutoProfileInfo *> tempSet(templist.begin(), list.end());
#else
                        QSet<AutoProfileInfo *> tempSet;
                        tempSet = getWindowNameProfileAssignments().value(nowWindowName).toSet();
#endif
```
