### ISSUE TITLE
QFontMetrics::width() is deprecated

### ISSUE THREAD

**Issue by mmmaisel** [AntiMicroX/antimicrox#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a compiler warning about deprecation of QFontMetrics::width.

### Expected Behavior

No warnings.

### Steps To Reproduce

Compile from source.

### Environment

```markdown
- OS: Arch Linux (22. April 2022)
- AntiMicroX version: git 85bbc6bf
```

### Anything else?

QFontMetrics::width() is deprecated since Qt 5.11 but the new function
QFontMetrics::horizontalAdvance() only exists since Qt 5.11.
This causes compilation errors on Ubuntu 18.4 and earlier if fixed.

**Comment by pktiuk** [comment]
Linked with: https://github.com/AntiMicroX/antimicrox/issues/318
