### ISSUE TITLE
Selection "None" Preset does not change button labels

### ISSUE THREAD

**Issue by mmmaisel** [AntiMicroX/antimicrox#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When switching the preset of a stick to "None", the button labels are not changed back to "[NO KEY]".
Clicking on one of the buttons afterwards shows that the assignment is changed to None.

### Expected Behavior

Button labels are switched to "[NO KEY"].

### Steps To Reproduce

1. Start AntimicroX
2. Switch to profile "<new>". Now all buttons are unassigned.
3. Right click on "Stick 1" and select preset "Mouse". Now the buttons change to "Mouse Left/Right/Up/Down". Click on one button to verify the mapping in the dialog.
4. Right click on "Stick 1" and select preset "None". Buttons labels don't change this time. Click on one button to open the mapping dialog. This shows that the button is now mapped to "[NO KEY]".

### Environment

```markdown
- OS: Arch Linux 30. April 2022
- AntiMicroX version: git commit e6bb2e73acae08777a620974ca558de5c7bf073e
```

**Comment by pktiuk** [comment]
I reproduced it.   
It is just a problem with refreshing button labels.

**Comment by pktiuk** [comment]
At first glance it seems that `void JoyButton::clearSlotsEventReset(bool clearSignalEmit)` doesn't work correctly.  
But I am not sure why. It seems that `void FlashButtonWidget::refreshLabel()` which generates new label names.
