### ISSUE TITLE
Nintendo Switch Controllers Recognized but not mapping

### ISSUE THREAD

**Issue by PiKiller** [AntiMicroX/antimicrox#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AntiMicroX recognizes and is connected to the controllers but does not recognize when I use analog or button inputs.

### Steps To Reproduce

1. Connect Nintendo Switch controllers to your computer
2. Press Quick set
3. Your controller inputs will not be recognized

### Environment

```markdown
- OS: Tried on Debian Linux and Windows 10, both get the same results.
- AntiMicroX version: 3.2.3
```

**Comment by mmmaisel** [comment]
On Linux, this should be fixed by adding the following udev rule to /etc/udev/rules.d:

```
KERNEL=="hidraw*", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="2009", MODE="0660", TAG+="uaccess"
```

**Comment by pktiuk** [comment]
@PiKiller   
Did it help in your case? (in case of Linux)

If yes, I will have to add some entries to udev rules.

**Comment by PiKiller** [comment]
I haven’t tried it. Apparently my joy-cons were bricked.
