### ISSUE TITLE
Application is not showing up in the app tray in KDE5 Plasma.

### ISSUE THREAD

**Issue by agameraaron** [AntiMicroX/antimicrox#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/12471157/171740753-1f2e41f9-9089-496e-9732-ab4a9e5d135e.png)

### Expected Behavior

The app tray icon should be visible.

### Steps To Reproduce

1. Open AntiMicroX.
2. Observe that the application is available in the app tray, but is not visible.

### Environment

```markdown
- OS: Manjaro 21.2.6
- AntiMicroX version: 3.2.3
```

### Anything else?

Cool program! Keep up the great work!!

**Comment by pktiuk** [comment]
Do you use flatpak version?

If yes, then we can mark it as a duplicate of https://github.com/flathub/io.github.antimicrox.antimicrox/issues/10

**Comment by agameraaron** [comment]
Indeed, I am. I'll go ahead and close this then.
