### ISSUE TITLE
Not saving controller mapping

### ISSUE THREAD

**Issue by skyth540** [AntiMicroX/antimicrox#457]
Detects Switch Pro controller perfectly, click on "Controller Mapping" in bottom left corner, map buttons just fine, hit save and all options in the main screen read "[NO KEY]"

Update joysticks, nothing.

Also Ctrl+M is broken

**Comment by pktiuk** [comment]
### Please follow our issue templates when reporting bugs or requesting features.

The devs put in hours of effort, and you should show enough respect to put in a few minutes & follow the template.
Following the template also provides us all the information we need, without having to ask for it.
Closing. Please create a new issue following the template if you would like assistance.
