### ISSUE TITLE
[Windows?] Hard-freeze (not responding) on quit program

### ISSUE THREAD

**Issue by instinctualjealousy** [AntiMicroX/antimicrox#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AntiMicroX is freezing up any time you try to attempt to quit the program. It shouldn't be doing this, obviously. I think this is a newer regression, as last time I tested and reported an issue, this wasn't happening.

### Expected Behavior

To close normally.

### Steps To Reproduce

1. Go to App -> Quit and click, or Ctrl+Q
2. Program freezes, and if interacted with further, goes into a Not Responding state

### Environment

```markdown
- OS: Windows 10 21H2
- AntiMicroX version: 3.2.4
```

### Anything else?

This was tested on a completely clean, new install (of AntiMicroX) with no pre-existing configuration and no controllers connected

**Comment by kydex** [comment]
I have the same issue.

**Comment by pktiuk** [comment]
In main.cpp it freezes at:
```cpp
    inputEventThread->quit();
    inputEventThread->wait(); //STUCK HERE 

    delete inputEventThread;
```

This is very similar case to the one we encountered earlier https://github.com/AntiMicroX/antimicrox/pull/416#issuecomment-1140486022

**Comment by pktiuk** [comment]
@avinal Is it possible to force our CI to use older version of SDL2?

**Comment by avinal** [comment]
> @avinal Is it possible to force our CI to use older version of SDL2?

Let me try. I will let you know tomorrow.

**Comment by mmmaisel** [comment]
I used SDL version 2.0.20 in my test builds in #416.

Interestingly, antimicrox-3.2.4-AMD64.exe from the release section works perfectly in wine so this might be a windows bug.

**Comment by pktiuk** [comment]
Wine probably redirects calls to Windows SDL2 to Linux SDL2 version, which doesn't have mentioned bug.  
It is just a translation layer, it doesn't contain many Windows libraries.

**Comment by avinal** [comment]
I checked on how to use an older version of SDL2, but couldn't find one. One way can be manually setting up SDL2 in CI, but that can be very tricky, will try anyway.

**Comment by pktiuk** [comment]
The latest working version was `2.0.20`, `2.0.22` breaks quitting.

**Comment by mmmaisel** [comment]
Executing the following commands instead of installing `mingw-w64-x86_64-SDL2` as dependency should work:
```
curl -o SDL2-2.0.20-1-any.pkg.tar.zst https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-SDL2-2.0.20-1-any.pkg.tar.zst
pacman -U SDL2-2.0.20-1-any.pkg.tar.zst
```

**Comment by pktiuk** [comment]
@mmmaisel 
```
 curl -o SDL2-2.0.20-1-any.pkg.tar.zst https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-SDL2-2.0.18-2-any.pkg.tar.zst
  pacman -U SDL2-2.0.20-1-any.pkg.tar.zst
  shell: D:\a\_temp\setup-msys2\msys2.CMD {0}
  env:
    MSYSTEM: MINGW64
  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
error: missing package metadata in SDL2-2.0.20-1-any.pkg.tar.zst
error: 'SDL2-2.0.20-1-any.pkg.tar.zst': invalid or corrupted package
```
https://github.com/pktiuk/antimicrox/runs/7008500277?check_suite_focus=true

Nothing in Windows is as simple as it should.

**Comment by pktiuk** [comment]
@mmmaisel  
After some minor tweaks your solution works.  
Thanks

**Comment by pktiuk** [comment]
I cherrypicked this commit on 2.2.4 release built it on [my private fork](https://github.com/pktiuk/antimicrox/releases/tag/3.2.4_downgrade_win_SDL). I also replaced executable on release site https://github.com/AntiMicroX/antimicrox/releases/tag/3.2.4

@instinctualjealousy   @kydex   
Just re-download and reinstall AntiMicroX and everything should be fine now. :)
