### ISSUE TITLE
Map gamepad keys to gamepad keys

### ISSUE THREAD

**Issue by sophie-kuehn** [AntiMicroX/antimicrox#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Back on Windows i used DS4Windows to customize my Controller for use in Star Citizen. For this i needed and was able to map for example the left stick to act as the right stick, when i hold R1. Or to map hitting D-Pad left to trigger the Square button. Sadly i can't find a similar possibility on Linux atm.

### Describe the solution you'd like

It would be very nice to be able to not only map a gamepad input to a keyboard or mouse action but also to other gamepad actions.

**Comment by Papermanzero** [comment]
Xinput and Dinput should be mappable

**Comment by pktiuk** [comment]
As mentioned in https://github.com/AntiMicroX/antimicrox/issues/293

> This feature is out of scope of antimicrox.
> 
> > AntiMicroX is a graphical program used to map gamepad keys to keyboard, mouse, scripts and macros.
> 
> Not for another gamepads or virtual devices (at least not for now).

**Comment by pktiuk** [comment]
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/65
