### ISSUE TITLE
Crashes constantly on a fresh win 10 install with Xbox One wireless gamepad

### ISSUE THREAD

**Issue by EyeTeaFiend** [AntiMicroX/antimicrox#468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While playing a game it sometimes crashes every 15 seconds or once an hour with no discernible trigger, although it seemed to start randomly occurring once I started using sets - I can't tell if that's causation or coincidence. If there's anything I can do to help I will. This is a fresh win 10 install with an xbox one wireless controller. Neither the pc or the controller experience any issues outside of this.

### Environment

```markdown
- OS:
- AntiMicroX version:
```

**Comment by pktiuk** [comment]
What application version do you use?   

Could you collect some logs? https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs

**Comment by pktiuk** [comment]
Closing due to lack of feedback
