### ISSUE TITLE
Enabling Key Repeat does not save settings in Windows 10

### ISSUE THREAD

**Issue by dotSpectrum** [AntiMicroX/antimicrox#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Enabling Key Repeat should save the settings in Windows 10

### Steps To Reproduce

1. Goto Options > Settings.
2. Under General find Key Repeat
3. Enable Setting and Press OK.
4. Go back to step 1 and 2, you'll see that Enabled is toggled off.

### Environment

```markdown
- OS:Windows 10
- AntiMicroX version:3.2.4
```

### Anything else?

The purpose of enabling this setting is to hold a certain key for a specific time interval, let go, and then press a different key. However in order to this this, I need key repeat enabled.

**Comment by pktiuk** [comment]
Duplicate: https://github.com/AntiMicroX/antimicrox/issues/115

Key repeat functionality does not work currently. See https://github.com/AntiMicroX/antimicrox/issues/115
