### ISSUE TITLE
Compatibility with QT older than 5.10 broken again

### ISSUE THREAD

**Issue by theofficialgman** [AntiMicroX/antimicrox#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
antimicrox/src/gui/mainwindow.cpp:1726:34: error: no match for ‘operator[]’ (operand types are ‘QJsonDocument’ and ‘const char [9]’)
     QString latest_version = json["tag_name"].toString().split("-")[0]; // remove notes from versions like 3.2.1-debug
```

the same issue occured in this other project and this is what they did to fix it:
https://github.com/pinaraf/Slacken/commit/545dd0fe2b7c9296e0a8c0d29e166eddd8fed7ae

### Expected Behavior

no build errors

### Steps To Reproduce

build antimicrox following build instructions

### Environment

```markdown
- OS: Ubuntu Bionic
- AntiMicroX version: 3.2.5
```

**Comment by pktiuk** [comment]
Thank you for this report (and hint how to fix it). :smile:    
This went under the radar because flag `CHECK_FOR_UPDATES` was disabled in CI
