### ISSUE TITLE
Docker Hub upload - or removing Docker

### ISSUE THREAD

**Issue by gombosg** [AntiMicroX/antimicrox#50]
Currently the docker references are for the old repo. Let's fix this.

- [ ] Create Docker hub org (free for public repos)
- [ ] Upload Docker images
- [ ] Update `BUILDING.md`
- [ ] Make a release reminder checklist for ourselves to know what to do on releasing 
	- update changelog
	- update flatpak
	- update Docker etc.

**Comment by gombosg** [comment]
@pktiuk another option is to let go of Docker images and remove them from the repo. I'm not sure if there is any advantage of Docker images here. We have Flatpak now. Docker images would be good if this was some containerized backend app or whatever.

**Comment by pktiuk** [comment]
I think we should drop docker support, using docker for such a small application is overkill, especially when there is Flatpak and AppImage available.
