### ISSUE TITLE
Spring for the joysticks arent working at all.

### ISSUE THREAD

**Issue by LunarDreams0** [AntiMicroX/antimicrox#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when attempting to use the mouse mode spring in the mouse settings of either left or right joystick settings, the mouse doesn't move at all, but using ANYTHING else works, such as binding numbers and letters. i have tested this with a xbox 360 usb controller and a nintendo switch pro and both do the same thing.

### Steps To Reproduce

1. at the sticks section, select left or right stick button to access the settings.
2. make it so the preset is mouse at the top right.
3. select mouse settings at the bottom.
4. change mouse mode at the top right to spring.
5. attempt to use joystick with spring.
6. doesn't work.

### Environment

```markdown
- OS: windows 8.1
- AntiMicroX version: 3.2.5
```

**Comment by pktiuk** [comment]
This seems to be WIndows-only issue. I am unable to reproduce it on Linux.
