### ISSUE TITLE
Advanced joined keys not working in 3.2.5

### ISSUE THREAD

**Issue by cyberconan** [AntiMicroX/antimicrox#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use the guide button in my Logitech gamepad for send ALT+F4 when the button is pressed 6 seconds. This works great in 3.2.4 but not work in 3.2.5.

### Expected Behavior

Send ALT+F4 combined keys after the delay.

### Steps To Reproduce

Select a button, go to advanced assignments and create a new one with:
  - Delay 6.00
  - ALT_L+F4 (joining both keys)
  - Test the button configured with any window, it must be close after 6 seconds
![Screenshot_20220802_184515](https://user-images.githubusercontent.com/1497109/182429388-7b8bb78e-1f80-4b85-8ce6-6c1af9fc00cd.png)

### Environment

```markdown
- OS: Archlinux
- AntiMicroX version: AUR version 3.2.4 but tested 3.2.5.
```

**Comment by pktiuk** [comment]
@mmmaisel   
Do you suspect any of the changes introduced by you in the latest release?  
If not, I will try to reproduce it and manually bisect commits.

**Comment by cyberconan** [comment]
No sorry, I don't know what commit could be the one than produce the issue and is better than someone can confirm than the problem is reproducible in other computer with the last version. Thanks!!

**Comment by HoJo215** [comment]
This sounds close to my problem using 3.2.5 on ubuntu 22.04.
It seems like it's not auto-updating joysticks when the profile is loaded. 
If I manually hit update joysticks from the tray while on the profile it works.

Also I noticed an error while starting antimicrox from the command line:

ioctl (GFEATURE): Input/output error

**Comment by pktiuk** [comment]
@cyberconan   
I am not able to reproduce this problem.   
Have you tried to test it without this delay or with another shortcut like `Alt+Tab`?

**Comment by cyberconan** [comment]
Hi @pktiuk, sorry not write before, I think the issue is related to Wayland because not happens with Xorg and only with some applications like RPCS3 than not take the focus. I need click with mouse or use a script than take window focus. You can close the issue. Thanks!!!

**Comment by pktiuk** [comment]
Could you test it under Xorg with two event-generation mechanisms?   
`antimicrox --eventgen xtest` and `antimicrox --eventgen uinput`   
Maybe it is caused not by wayland, but by input (xtest does not work with wayland)

**Comment by pktiuk** [comment]
@HoJo215   
I also got error `ioctl (GFEATURE): Input/output error`  
But after investigation function [ioctl](https://man7.org/linux/man-pages/man2/ioctl.2.html#top_of_page) always returned a success value (0).
Moreover I can't find what this warning is about. Idk how it may be related tho this (or any other issue).
