### ISSUE TITLE
The app is not working

### ISSUE THREAD

**Issue by thefallguy08** [AntiMicroX/antimicrox#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to execute the app, but it simply does not budge. I tried everything, pressed every single thing, deleted it and downloaded it again, but it's still not working.

### Environment

```markdown
- OS:Windows 10
- AntiMicroX version:3.2.5
```

**Comment by pktiuk** [comment]
budge?

**Comment by pktiuk** [comment]
Closing due to lack of feedback
