### ISSUE TITLE
Mouse spring mode not working in plasma wayland session [Linux]

### ISSUE THREAD

**Issue by IDeathByte** [AntiMicroX/antimicrox#521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spring mode doesn't works on both modes (binding and manual mouse w/h)
In binding mode, coordinates in mouse status doesn't changes, in manual hasn't effect.

### Steps To Reproduce

1) Set mouse in spring mode
2) See how nothing happens
### Environment

```markdown
- OS: Manjaro
- AntiMicroX version: 3.2.5
```

**Comment by TheOpponent** [comment]
Mouse spring mode is also not working in Windows 10 in version 3.2.5.

**Comment by pktiuk** [comment]
@IDeathByte  
Could you copy more diagnostic info? (text from Help->About->Info)

**Comment by IDeathByte** [comment]
Version 3.3.2
BUild from Nov 27 2022 в 05:14:58
Builded with SDL 2.26.0
Running with SDL 2.26.1
Qt 5.15.7
event handler: uinput
Compositor type: wayland
Host OS: manjaro Version: unknown Architecture: x86_64

**Comment by pktiuk** [comment]
Something is wrong with handling absolute mouse movement in uinput

```cpp
void UInputEventHandler::sendMouseAbsEvent(int xDis, int yDis, int screen)
{
    Q_UNUSED(screen);

    write_uinput_event(springMouseFileHandler, EV_ABS, ABS_X, xDis, false);
    write_uinput_event(springMouseFileHandler, EV_ABS, ABS_Y, yDis);
}


void UInputEventHandler::write_uinput_event(int filehandle, int type, int code, int value, bool syn)
{
    struct input_event ev;
    struct input_event ev2;

    memset(&ev, 0, sizeof(struct input_event));
    gettimeofday(&ev.time, nullptr);
    ev.type = type;
    ev.code = code;
    ev.value = value;

    write(filehandle, &ev, sizeof(struct input_event));
```

Maybe it was not initialized properly. But that part also looks fine. 

```cpp

void UInputEventHandler::setSpringMouseEvents(int filehandle)
{
    ioctl(filehandle, UI_SET_EVBIT, EV_KEY);
    ioctl(filehandle, UI_SET_EVBIT, EV_SYN);

    ioctl(filehandle, UI_SET_KEYBIT, BTN_LEFT);
    ioctl(filehandle, UI_SET_KEYBIT, BTN_RIGHT);
    ioctl(filehandle, UI_SET_KEYBIT, BTN_MIDDLE);
    ioctl(filehandle, UI_SET_KEYBIT, BTN_SIDE);
    ioctl(filehandle, UI_SET_KEYBIT, BTN_EXTRA);

    ioctl(filehandle, UI_SET_EVBIT, EV_ABS);
    ioctl(filehandle, UI_SET_ABSBIT, ABS_X);
    ioctl(filehandle, UI_SET_ABSBIT, ABS_Y);
    ioctl(filehandle, UI_SET_KEYBIT, BTN_TOUCH);

    // BTN_TOOL_PEN is required for the mouse to be seen as an
    // absolute mouse as opposed to a relative mouse.
    ioctl(filehandle, UI_SET_KEYBIT, BTN_TOOL_PEN);
}
```

**Comment by pktiuk** [comment]
@TheOpponent    
In my case spring works flawlessly on Windows 10.  Are you sure you set it up correctly?

**Comment by pktiuk** [comment]
File handler is not initialized properly.

after replacing function `setSpringMouseEvents` with:

```cpp
void UInputEventHandler::setSpringMouseEvents(int fd)
{
    ioctl(fd, UI_SET_EVBIT, EV_KEY);

    ioctl(fd, UI_SET_KEYBIT, BTN_LEFT);
    ioctl(fd, UI_SET_KEYBIT, BTN_RIGHT);

    // ioctl(fd, UI_SET_EVBIT, EV_REL);

    ioctl(fd, UI_SET_EVBIT, EV_ABS);
    ioctl(fd, UI_SET_ABSBIT, ABS_X);
    ioctl(fd, UI_SET_ABSBIT, ABS_Y);
}
```
Absolute mouse started working

**Comment by pktiuk** [comment]
@Ryochan7 Is there any reason why we need the mouse to be seen as an absolute mouse instead of a relative one? (If you remember anything about that, of course)

**Comment by Ryochan7** [comment]
I have not used that functionality much but there are some good uses for the feature. Recently implemented absolute mouse support in my current mapper experiments primarily for use in Torchlight 2. Abs mouse is used to make a circle around the main character with an outer ring binding set to Move (` key IIRC); that would allow character movement with just LS. Another use would be to have a binding activate items in an action hotbar by fake clicking on a specific portion of the screen. There are probably other uses but those are the main ways I have used the feature in the past.

**Comment by pktiuk** [comment]
@Ryochan7    
I know the purpose of that functionality, but I am asking why line:

```cpp
    // BTN_TOOL_PEN is required for the mouse to be seen as an
    // absolute mouse as opposed to a relative mouse.
    ioctl(filehandle, UI_SET_KEYBIT, BTN_TOOL_PEN);
```
Is necessary, because it breaks spring mode functionality.

**Comment by Ryochan7** [comment]
Last I tested, that was the flag to distinguish an absolute mouse pointer from a relative mouse pointer in uinput. It is also the reason two mouse pointers have to be created when using uinput. Without that flag, spring mouse would have to be faked.

**Comment by Ryochan7** [comment]
Just downloaded the current source and tried it out. Something must have changed over the years as I am experiencing the same breakage from the BTN_TOOL_PEN keybit being set. The Abs Mouse Emulation device does not even show up from xinput when that bit is set. Once the line is commented out, spring mouse works when using the uinput event generator. I wonder if MoltenGamepad uses that flag in its event generator system?

**Comment by pktiuk** [comment]
So I will merge https://github.com/AntiMicroX/antimicrox/pull/701. In the worst case, I will revert it.

**Comment by pktiuk** [comment]
Thanks for help with this one.

**Comment by Ryochan7** [comment]
Not sure if it would matter but I guess I should post some info about my current Linux install for future reference.

Distro: Fedora 35
Kernel version: 6.0.12
Xorg server: 1.20.14

I am going to assume that the behavior seen here is most likely dependent on the kernel version and uinput implementation than anything else. I have not used this functionality since around 2018 so there is a big gap as far as when behavior regarding the use of BTN_TOOL_PEN might have changed. I think I was might have been using SteamOS 2.0 and Ubuntu around that time.
