### ISSUE TITLE
Linux: advanced settings dialog freezes when pressing join

### ISSUE THREAD

**Issue by thesourcehim** [AntiMicroX/antimicrox#524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to join two slots, application completely freezes, I have to kill it. Tested it with latest git version. Trying to assign button to a slot also results in freeze. The only way I could configure advanced settings for a button is by editing profile file manually.

### Expected Behavior

Application should not freeze

### Steps To Reproduce

1. Select gamepad button to bind
2. Press 'advanced'
3. Click on an empty slot button or select two slots and press 'join'

### Environment

```markdown
- OS:Linux Fedora 36
- AntiMicroX version: 3.2.5-git1722f6d
```

**Comment by thesourcehim** [comment]
This is printed in the debug log when I press 'join'
❗WARN   QMetaMethod::invoke: Dead lock detected in BlockingQueuedConnection: Receiver is AdvanceButtonDialogHelper(0x1d44018)

**Comment by pktiuk** [comment]
I am not able to reproduce this issue.  
![image](https://user-images.githubusercontent.com/45544416/201416723-c25d5662-195c-4961-80d8-78c9d87fa8a9.png)
I can join slots without any problems
![image](https://user-images.githubusercontent.com/45544416/201416759-3b46ea2b-6ee3-4220-a473-176f4542b99b.png)

**Comment by pktiuk** [comment]
Could you retest with master branch after merging: https://github.com/AntiMicroX/antimicrox/pull/605 ?

If this issue still occurs could you [collect some logs](https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs)?

**Comment by thesourcehim** [comment]
Just tested it, works fine now, no freezes, settings are updated after dialog is closed and saved into config file after I press save. However, it seems settings fail to load correctly after application is restarted. I configured mic button on my DualSense to produce L_CTRL+P combination. Here's how it looks in the file:
```
<button index="16">
    <slots>
        <slot>
            <slots>
                <slot>
                    <code>0x1000021</code>
                    <mode>keyboard</mode>
                </slot>
                <slot>
                    <code>0x50</code>
                    <mode>keyboard</mode>
                </slot>
            </slots>
            <mode>mix</mode>
        </slot>
    </slots>
</button>
```
But when application is restarted it shows that mic button (16) is not assigned.

**Comment by pktiuk** [comment]
This bug is introduced in: https://github.com/AntiMicroX/antimicrox/pull/573

**Comment by pktiuk** [comment]
The fix is available in a new beta release https://github.com/AntiMicroX/antimicrox/releases/tag/3.3.2-rc
