### ISSUE TITLE
Saving Breaks Set Switching

### ISSUE THREAD

**Issue by Redorak** [AntiMicroX/antimicrox#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using a Dualsense controller and am setting it so that when I hold down my right trigger it'll change from set 1 to set 2. 
I am able to do this successfully but when I save the profile the functionality does not work anymore and I'm stuck in set 1. 

### Steps To Reproduce

I set throttle as normal for Right Trigger.
I then set R trigger to Left Shift and then Advanced > Set Selector as "Select Set 2 While Held" 
I press Right Trigger at this point to test and it switches to set 2 when I hold the trigger. 
I then save the profile. (I've tried both save and save as)
I press Right Trigger again but it no longer goes to set 2.

This seems to work with any button, i'm just using Right trigger as an example

### Environment

```markdown
- OS:Windows 10
- AntiMicroX version:
Tested this on the most latest version and 2.1
```

**Comment by pktiuk** [comment]
Fixed by: https://github.com/AntiMicroX/antimicrox/pull/573   
The next release with this fix will be soon available
