### ISSUE TITLE
Add button icons for different controllers

### ISSUE THREAD

**Issue by Simao-Santos** [AntiMicroX/antimicrox#53]
It would be easier to map the buttons when using different controllers than the xbox controller.

Add different icons for the most popular controllers, and if possible detection of the controller to automatically show the respective icons. I.e., square, circle, x, triangle for DS3/4, etc

**Comment by gombosg** [comment]
Questions that pop to my mind:
- What kind of controllers are out there with distinct button schemes? Only PS/XBOX or are there different types?
- How can we detect button scheme/controller type? I guess this has to be hardcoded.
- Would it be sufficient if the user could set the scheme manually? E.g. mark a controller as Playstation or whatever.

My concern here is that setting up a controller DB etc. may be a tremendous amount of work, and this feature only nets us aesthetic improvements.

**Comment by Simao-Santos** [comment]
I coincidentally ran into this issue just now, right when you closed it yesterday :D

Sorry I didn't see @gombosg 's response until now.

I think you're right, it's too much work for just an aesthetic improvement. 
Maybe the best way would be your third suggestion:
- To set manually as in, "mark this controller as Playstation"

Maybe for now just the playstation one, because I would say it's pretty popular.

I can be assigned to it, since I'm the one who brought it up :)
