### ISSUE TITLE
can´t enable key repeat

### ISSUE THREAD

**Issue by chicken999** [AntiMicroX/antimicrox#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

everytime i enable key repeat it is not saved and when i go back to settings the checkbox is unchecked

### Expected Behavior

it should be saved

### Steps To Reproduce

open antimicrox
go to settings
enable key repeat

### Environment

```markdown
- OS: windows 10
- AntiMicroX version: latest version
```

**Comment by Alex997tt** [comment]
Same.  I had key repeat working when I first installed  https://github.com/AntiMicroX/antimicrox/releases/download/3.2.5/antimicrox-3.2.5-AMD64.exe on Windows 10 yesterday, then after some time it seem to break and keys would not repeat.  I tried turning on key repeat as @chicken999 indicates but it does not save.

**Comment by pktiuk** [comment]
Key repeat is not working check: https://github.com/AntiMicroX/antimicrox/issues/115   
IDK why you see this option visible at all.
