### ISSUE TITLE
Map touch inputs for DS4 controller

### ISSUE THREAD

**Issue by gczark** [AntiMicroX/antimicrox#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by pktiuk** [comment]
It doesn't seem to be doable, because touchpad of ds4 is already mapped as a mouse and is not recognizable part of gamepad (afaik)  
This doesn't seem to be doable.  
But you can prove me wrong.

**Comment by gczark** [comment]
Sorry for the late reply.
Exactly I want to use the touch for mouse control, but the app doesn't allow me.

**Comment by TheSandBoxMKG** [comment]
Just coming to chime in something, but lately, at least, on Linux, you can disable the touchpad-as-mouse mapping without losing the input:
[https://wiki.archlinux.org/title/Gamepad#libinput](https://wiki.archlinux.org/title/Gamepad#libinput)
After disabling the mapping of the mouse to the touchpad, the device can still be seen on evtest (`Wireless Controller Touchpad`) and it even returns information.

Not sure if that helps anything.
