### ISSUE TITLE
Is possible install SDL recent versions in Ubuntu 20.04

### ISSUE THREAD

**Issue by Augusto7743** [AntiMicroX/antimicrox#537]
Hello.
Only sharing an information.
In download has the information :
Motion sensor support may not work on older Linux systems where classical packages are used (For example .deb for Ubuntu 20.04) due to older versions of SDL available in repositories.

Yes ... SDL in distro repositories are old.
Is possible install SDL recent versions for Ubuntu 20.04 using software from PPA.
That information help users.
Have an nice day.

**Comment by pktiuk** [comment]
### Please follow our issue templates when reporting bugs or requesting features.

The devs put in hours of effort, and you should show enough respect to put in a few minutes & follow the template.
Following the template also provides us all the information we need, without having to ask for it.
Closing. Please create a new issue following the template if you would like assistance.

**Comment by Augusto7743** [comment]
I had posted only to share information.
