### ISSUE TITLE
Auto Profiles Don't save: Windows 10 21H2

### ISSUE THREAD

**Issue by mdac3564444** [AntiMicroX/antimicrox#539]
After Auto Profile is created and visible in the Auto Profiles screen list, press  "ok" to exit back to the main screen, then reopen setting/Auto Profiles....and the profile is gone. Nothing saved. Tried multiple auto profiles configurations to enable save: Full path to specific application, title specified with and without partial title enabled, entered info from auto detect...nothing worked.

**Comment by pktiuk** [comment]
If you want to report issue then follow template, if you want to ask about something, then use [discussion module](https://github.com/AntiMicroX/antimicrox/discussions)
