### ISSUE TITLE
App suddenly keeps shutting down

### ISSUE THREAD

**Issue by bemtikru** [AntiMicroX/antimicrox#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After working without problems, today the app just shuts down by itself after a minute or two, causing the controller to stop working properly. This has only happened today and it happened 3 times already

### Environment

```markdown
- OS: Windows 10
- AntiMicroX version: 3.2.1
```

**Comment by pktiuk** [comment]
Just update AntiMicroX. 3.2.1 is pretty old version

**Comment by bemtikru** [comment]
> 

will try, thanks

**Comment by pktiuk** [comment]
Closing due to lack of feedback
