### ISSUE TITLE
Arch Linux: IOT instruction (core dumped)  antimicrox

### ISSUE THREAD

**Issue by avahe-kellenberger** [AntiMicroX/antimicrox#550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`IOT instruction (core dumped) antimicrox` is the output when trying to run `antimicrox` from the terminal.
I've tried the build from the AUR, and also built it locally myself with the same outcome.

### Expected Behavior

The program to launch.

### Steps To Reproduce

Follow the build instructions with the latest commit on Arch Linux, then attempt to run the program.

### Environment

```markdown
- OS: 5.19.11-arch1-1
- AntiMicroX version: Latest commit, b0a64725307b94f1acc2967701f346a9dcbddfd1
```

### Anything else?

Nope

**Comment by pktiuk** [comment]
Have you tried to compile it in Debug mode?
```bash
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
```

And run with verbose or debug logs (`antimicrox --log-level debug`)

In this case you should be able to see a stack trace.

My first guess is some kind of regression in SDL2.

**Comment by avahe-kellenberger** [comment]
I'm actually getting the same output
`IOT instruction (core dumped)  ./bin/antimicrox --log-level debug`

I tried `cmake .. -DCMAKE_BUILD_TYPE=Release` and `cmake .. -DCMAKE_BUILD_TYPE=Debug` with the same result

**Comment by pktiuk** [comment]
App crashes very early, even before logger is initialized, interesting.

For now I would recommend you using flatpak package, because there app runs in stable environment

**Comment by pktiuk** [comment]
Does flatpak package work on your machine?

**Comment by avahe-kellenberger** [comment]
Haven't tried it, I don't want to use snap/flatpack/appimages

**Comment by pktiuk** [comment]
Ok, in this case the only solution is finding place where it crashes. :/

**Comment by pktiuk** [comment]
Firstly you have to obtain stack trace and find where exactly app crashed.

**Comment by pktiuk** [comment]
Closing due to lack of feedback.
