### ISSUE TITLE
Two controllers but save same action for each

### ISSUE THREAD

**Issue by davek00997744** [AntiMicroX/antimicrox#552]
Great software, just what i was looking for, however....

I have a flight yoke that consists of two parts - the yoke and the throttle quadrant, they both show up in the controller tabs but if i save an action for button 12 on the yoke it duplicates it for button 12 on the quadrant.

In the tab names it shows as **Velocity Flight Yoke (1)** and **Velocity Flight Yoke (2)**

I now have working screen shot/share button for flight sim but also when i shut the throttle down it also takes a screen shot :) 

It appears it is recognising "Button 12" for both items instead of "Button 12, Velocity Flight Yoke (1)" and "Button 12, Velocity Flight Yoke (2)"

**Comment by pktiuk** [comment]
If you want to report issue then follow template, if you want to ask about something, then use [discussion module](https://github.com/AntiMicroX/antimicrox/discussions)

**Comment by davek00997744** [comment]
What template please?

**Comment by pktiuk** [comment]
For example this https://github.com/AntiMicroX/antimicrox/issues/new?assignees=&labels=bug&template=bug_report.yaml
