### ISSUE TITLE
Saving config breaks turbo

### ISSUE THREAD

**Issue by YogiMatt** [AntiMicroX/antimicrox#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi I've tested this out one three different PC's win10 and win11 with a ps5 controller. When I save my controller setting the turbo no longer works. 

Before I save, turbo settings works fine in a "<New>" profile. 
When saved the turbo stops working on every button, even if I rebind the key or change it to a different key.
Selecting <New> and starting a new profile turbo setting works fine but again when saving it breaks.

I've tried closing antimicroX,  restarting my pc , disconnecting the controller  but there seems to be something up with the saved profile file.

### Expected Behavior

turbo to work

### Steps To Reproduce

Before I save, turbo settings works fine in a "<New>" profile. 
When saved the turbo stops working on every button, even if I rebind the key or change it to a different key.
Selecting <New> and starting a new profile turbo setting works fine but again when saving it breaks.
![image](https://user-images.githubusercontent.com/45500038/195888771-e60bf66f-96f1-4d26-92fe-90dbd13bc123.png)
![image](https://user-images.githubusercontent.com/45500038/195889664-3eb68a7e-e920-4e9a-801c-8534b8c44bbd.png)
![image](https://user-images.githubusercontent.com/45500038/195889684-5abe250c-118e-4197-86f7-b48c4606e95d.png)

### Environment

```markdown
- OS:win10 and win11
- AntiMicroX version:3.2.5
```

### Anything else?

I've tried this on older versions and I'm getting the same result. I don't seem to have this issue with the original antimicro

**Comment by pktiuk** [comment]
Could you retest it with the latest release?

**Comment by pktiuk** [comment]
Afaik this should be fixed now. Closing. In case of further problems I will reopen.
