### ISSUE TITLE
【Function】Move mouse to the specified location？

### ISSUE THREAD

**Issue by yamosin** [AntiMicroX/antimicrox#575]
First thing, thanks for this excellent controller mapping project! 
I'm trying to find the goto coordinates feature, but there doesn't seem to be a way to do it with the existing advanced keys feature
I searched for issues and there doesn't seem to be a similar post
If jump to a specific location immediately when press a key, can click on one button without moving the mouse (e.g. open the map, open a key door).
For games where the button position is constant, this can greatly improve the smoothness and more similar to the native joystick support experience

**Comment by pktiuk** [comment]
### Please follow our issue templates when reporting bugs or requesting features.
