### ISSUE TITLE
Xbox Controller turns off immediately

### ISSUE THREAD

**Issue by ZeptoBST** [AntiMicroX/antimicrox#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While AntiMicroX is running, if I wirelessly connect my Xbox Series X controller (using the Wireless adapter) to my PC, it will immediately disconnect.

If AntiMicroX is not running and I connect it, it will be fine. I can then launch AntiMicroX and it won't disconnect. But then if I manually turn off my controller and turn it back on, it will immediately disconnect again.

Sometimes it'll work fine once or twice before it doesn't.

### Expected Behavior

While it is running, wirelessly connecting my controller should not disconnect it.

### Steps To Reproduce

1. Open AntiMicroX.
2. Connect your Xbox Series X controller using the Xbox Wireless adapter.
3. Turn off your controller.
4. Repeat from 2, it may only work once or twice.

### Environment

```markdown
- OS: Windows 11 22H2
- AntiMicroX version: 3.2.5 - 3.3.1
```

### Anything else?

[out.log](https://github.com/AntiMicroX/antimicrox/files/9855550/out.log)

**Comment by ZeptoBST** [comment]
Ok, so I have tried the same thing on my Steam Deck (running on Windows 11) and I did not have problems. I'll see if it's some software messing with it on my main pc. I'll also try other computers to see the results.

**Comment by ZeptoBST** [comment]
UPDATE: Nvm. One reboot later and it behaves the same on my Deck than on my pc.

**Comment by ZeptoBST** [comment]
UPDATE YET AGAIN: Ok, so the reason why it didn't work after rebooting my Deck was because the SWICD driver had not started (thus did not create the virtual xinput device).

After starting the driver, it worked fine again.


I tried to connect another xbox controller to my pc with a usb cable and then trying again with my main controller.

Bam, no issues anymore. At least, as long as the other controller is plugged in with usb. If unplugged, my main controller will disconnect again.

**Comment by pktiuk** [comment]
I think something may be wrong with controller or adapter (afaik Xbox controllers need to have USB wireless adapter).  
To be 100% sure, you should also test it with other software like `jstest-gtk`, qjoypad or [sdl-jstest](https://github.com/Grumbel/sdl-jstest).

**Comment by ZeptoBST** [comment]
I tried on my Raspberry Pi 400 with the linux version of AntiMicroX (using Xow to use the wireless adapter) and got no issues. Seems like the issue only occurs on Windows.

**Comment by ZeptoBST** [comment]
Also worth pointing out that the issue does not occur with the original AntiMicro on Windows.

**Comment by pktiuk** [comment]
Then problem is with windows driver or with underlying libraries (SDL)

**Comment by ZeptoBST** [comment]
I guess SDL indeed is the issue after all: [https://www.reddit.com/r/sdl/comments/v42pnp/controller_disconnects_after_connecting/](url)

**Comment by pktiuk** [comment]
Probably caused by: https://github.com/libsdl-org/SDL/issues/3468
