### ISSUE TITLE
[Windows?] Auto-profile not functioning (window detection)

### ISSUE THREAD

**Issue by instinctualjealousy** [AntiMicroX/antimicrox#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I focus a window that I listed in auto profile with both a title *and* a full explicit path, it doesn't switch profiles. I've tried it with a few games that worked fine on antimicro 2.23. Full explicit path alone doesn't work, either. Also- tried partial title, no dice. I made sure to use the file selector to avoid human error.

### Expected Behavior

It should switch to the associated profile when a focused window matching the set data is detected.

### Steps To Reproduce

1. Make sure auto profile is on
2. Set an automatic profile up for a game (full path is ideal for matching)
3. Launch game or application and focus it (preferably windowed for ease of testing)
4. It does not switch profiles
5. (I have a default, blank profile set up for when no program is matched- if it works for you with these steps, set up a default profile as well and see if behavior changes)

### Environment

```markdown
- OS: Windows 10 22H2 64-bit
- AntiMicroX version: 3.3.1
```

### Anything else?

I've tried logging- I couldn't get the log to populate in debug mode, and verbose mode is just a bunch of nul chars and numbers? This is true of the later filed issues as well.

**Comment by pktiuk** [comment]
You could test these fixes using this build https://github.com/pktiuk/antimicrox/releases/tag/3.3.1-autoprofile

**Comment by instinctualjealousy** [comment]
Auto-detection appears to be functioning as expected. I click a program in the list, it switches to it, and I click away to something not in the list and it switches back to my default profile.
