### ISSUE TITLE
Auto-profile title box is broken when unchecking "set partial title"

### ISSUE THREAD

**Issue by instinctualjealousy** [AntiMicroX/antimicrox#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![ezgif-2-764c1838c8](https://user-images.githubusercontent.com/13276804/198124869-c5e6eadc-286c-401d-82c0-2d994c4a94a8.gif)
While editing auto profiles, if you check "set partial title" and then uncheck it, the box loses its editable property and grays out. Closing the editing window and reopening it fixes it, of course.

### Expected Behavior

Unchecking partial title mode should have no bearing on the editability of this field.

### Steps To Reproduce

1. Edit or create a new auto-profile
2. Decide you want to use a partial title as a match
3. Be indecisive and change your mind
4. Oh crap, I can't edit the title anymore

### Environment

```markdown
- OS: Windows 10 22H2 64-bit
- AntiMicroX version: 3.3.1
```

**Comment by pktiuk** [comment]
This is strange, but this behavior does not seem to be a bug, but something expected
```c++
void AddEditAutoProfileDialog::on_setPartialCheckBox_stateChanged(int arg1)
{
    if (arg1 == 0)
        ui->winNameLineEdit->setEnabled(false);
    else
        ui->winNameLineEdit->setEnabled(true);
}
```

**Comment by pktiuk** [comment]
Fix is available in a new beta release release https://github.com/AntiMicroX/antimicrox/releases/tag/3.3.2-rc
