### ISSUE TITLE
[Windows?] Auto-profile Select Window function not working

### ISSUE THREAD

**Issue by instinctualjealousy** [AntiMicroX/antimicrox#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Capture](https://user-images.githubusercontent.com/13276804/198127629-9f1e1a17-a410-42f2-939f-3f4615b8ae39.PNG)
This button here if I'm not clear.

![Capture2](https://user-images.githubusercontent.com/13276804/198127630-8c7c1b3a-fe2d-41ec-9927-5c903b7b36eb.PNG)
After I've selected a program with the focus timer (I just used a This PC window of Windows Explorer for an example, but I can confirm this behavior with other games and programs), It correctly gets the window title, and only gets the drive letter of the path (an issue itself) of the executable. This may be related to some characters needing escaped that aren't in the Windows build, or broken slash/backslash handling.

![Capture3](https://user-images.githubusercontent.com/13276804/198127631-c40f45f4-eb18-4461-b1f4-b11085b1c82a.PNG)
After hitting OK, neither field is populated by the detected information.

### Expected Behavior

As in 2.23, the window selector function should pass through its gathered info into the relevant, selected fields.

### Steps To Reproduce

1. Make or create an auto-profile
2. Use the pictured window selector to focus select a window/process
3. Confirm, and notice neither field is filled from the detected info

### Environment

```markdown
- OS: Windows 22H2 64-bit
- AntiMicroX version: 3.3.1
```

**Comment by pktiuk** [comment]
It's a bit strange, because in code it looks like expected behaviour.
```
void AddEditAutoProfileDialog::on_setPartialCheckBox_stateChanged(int arg1)
{
    if (arg1 == 0)
        ui->winNameLineEdit->setEnabled(false);
    else
        ui->winNameLineEdit->setEnabled(true);
}
```
I will have to check it, before removing

**Comment by instinctualjealousy** [comment]
![Capture](https://user-images.githubusercontent.com/13276804/198847080-01f86c14-8abe-429c-9b3f-8b7f704ba7b1.PNG)
It correctly lists the whole path (just let it capture itself this time haha, but tested it with other programs) but it still doesn't populate the Title or Application fields upon hitting OK with the info it detected.

**Comment by pktiuk** [comment]
Ok, I forgot to investigate that part of the bug xD

**Comment by instinctualjealousy** [comment]
![Capture](https://user-images.githubusercontent.com/13276804/199102960-c05df823-0da2-41ee-afed-e8f6dd44eb1e.PNG)
Also, it is worth noting that antimicro(x) on Windows uses forward slashes for some paths in configuration, and escaped backslashes for other paths in the configuration. Only reason I bring this up is your fixed window capture preview uses the correct backslashes, while the actual Application field populates with forward slashes when you use the file selector. The autoprofile code might expect the saved Application path to be formatted in this way. I don't know anything about how this program works, and you do. I bring this up just in case the autofill would fill the application field with backslashes (duplicating the detected data into the field) and then the autoprofile would fail to work because it was expecting forward slashes, haha!

**Comment by pktiuk** [comment]
Legacy AntiMicro handled the paths in the same way and it worked properly, so I think these paths also should be fine.
