### ISSUE TITLE
Auto-profile for fullscreen apps

### ISSUE THREAD

**Issue by sonofevil** [AntiMicroX/antimicrox#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

For example, Steam's Big Picture task is still just called Steam and running through Steam.exe. So there seems to be currently no way for AntiMicroX to distinguish it from the windowed Steam app. But on the windowed app I need mouse control, whereas in Big Picture I don't want AntiMicroX to do anything because Big Picture already supports controllers. 

### Describe the solution you'd like

A way to create an auto-profile that activates on all fullscreen apps.

Most true fullscreen apps (entire screen, taskbar not visible), especially games, have controller support, so this seems like a pretty wide use case. Usually you don't want AntiMicroX to mess up your input in those. For the few exceptions, you could still create overriding specific app auto-profiles.

One thing to consider is that some games are true fullscreen, i.e. they take over the whole display device with priority over everything else, and some use borderless fullscreen, i.e. a borderless window that hides the taskbar. The latter has certain advantages, like faster alt-tabbing, and ideally you'd want AntiMicroX to recognize both as fullscreen, whereas maximized regular windows shouldn't count.

### Describe alternatives you've considered

It is obviously in principle possible to create a profile for every single game you install, but that's a bit tedious. And like I said, this isn't currently feasible for Big Picture.

**Comment by pktiuk** [comment]
I think it is a bit too niche use case to implement it.   
If someone youlf find an elegant way to implement it we could take in his PR, but I don't find it very important feature

**Comment by sonofevil** [comment]
If you personally don't need it that'd be a perfectly good reason to not want to implement it, but how can you think it's niche? I honestly just want to understand because I explained in the original comment why it seems like a very wide use case and this response is puzzling and opaque.

To reiterate, it applies to most modern video games plus the widely used Steam Big Picture mode. Do people who use AntiMicroX not use any of these? Or are you saying they all are happy to create an auto-profile for every single game, when the profile is gonna be the same in 95% of cases anyway (=empty)? Maybe you could argue this if AntiMicroX made this easy by allowing the same auto-profile to apply to multiple apps, but as far as I can tell it doesn't. Or is there some other obvious, external method that I'm overlooking? I'm sure I could write an X11 script on Linux, but I have no idea how to do this sort of thing in Windows.

**Comment by pktiuk** [comment]
As far as I understood this is about differentiating between apps running in a window and full-screen mode.   
In most cases it does not matter because game is still a game, the only use case is the one you described. It is disabling AntiMicroX, when we enter big picture mode.

I think in this case It would be just better to report this to steam, that it would be better to just show different window name for Bit Picture. Moreover AFAIK Valve will soon replace its big picture with its reworked version for steam deck and it may also include this change https://www.windowscentral.com/gaming/pc-gaming/valve-is-finally-replacing-big-picture-mode-on-desktops-with-the-steam-deck-ui

**Comment by pktiuk** [comment]
If you enable this version of steam window is called `SP`

![image](https://user-images.githubusercontent.com/45544416/202855592-18d0612c-77d3-4df7-9b37-9e874a30f8fa.png)
