### ISSUE TITLE
Crash during gameplay of game running in wine via lutris

### ISSUE THREAD

**Issue by Codythedragonrude** [AntiMicroX/antimicrox#60]
![Screenshot_20201005_205319](https://user-images.githubusercontent.com/47878493/95210886-f1159600-07b9-11eb-97b4-bcdd2233a5f7.png)

**Comment by gombosg** [comment]
Hm, looks strange, this is some low-level error log. Why is it complaining about samba and 'net usershare info'?
Please provide more system info if possible.

**Comment by Codythedragonrude** [comment]
when i was testing this i was running manjaro kde with the LTS kernel i have since moved to mxlinux xfce with the liquorix kernel so when i have time i will test the program in this distro and see if i can replicate the issue 
if not then it would probably be a manjaro related issue or an AUR package version issue

**Comment by gombosg** [comment]
Thanks, please reopen if/when you have more info.
