### ISSUE TITLE
Icons overhaul

### ISSUE THREAD

**Issue by pktiuk** [AntiMicroX/antimicrox#61]
During investigating of issues https://github.com/AntiMicroX/antimicrox/issues/56 and https://github.com/AntiMicroX/antimicrox/issues/58 I have found out, there is a pretty big mess in terms of small icons used by AntiMicroX.

Currently, custom icons are both compiled into binary files (but they are broken because of wrong paths in code) and they are added as a part of system theme called `hicolor`.  
To ensure usage of these icons theme used by app is overridden to be `hicolor`, this solution is very not elegant, duplicates loading of the same icons and can be problematic to use with some themes.
```c++
    updateJoy->setIcon(QIcon::fromTheme(QString::fromUtf8("view_refresh"), QIcon(":/icons/hicolor/16x16/actions/view_refresh.png")));
```

I think it would be better to use icons supplied by system-wide theme, because some of our icon look a bit out of place in some cases, and we should use our old icons as a fallback option in case of problems with themed icons.

I think we could also think about updating some of these icons, because some of them look a bit out of date:  
![document_save](https://user-images.githubusercontent.com/45544416/95688808-1f0d3700-0c0d-11eb-8e22-c424e9370af9.png)![edit_clear_list](https://user-images.githubusercontent.com/45544416/95688813-23395480-0c0d-11eb-9497-f83676907c6e.png)![document_revert_small](https://user-images.githubusercontent.com/45544416/95688780-ed946b80-0c0c-11eb-80b1-dc7de9641310.png)...

TL;TR
Things to do:
- [x] use default system-wide icons (https://github.com/AntiMicroX/antimicrox/pull/62 https://github.com/AntiMicroX/antimicrox/pull/71)
- [x] fix fallback links to embedded icons (compiled into binary files of antimicrox) (https://github.com/AntiMicroX/antimicrox/pull/75)
- [x] remove already embedded icons from list of installed elements (https://github.com/AntiMicroX/antimicrox/pull/72)
- [x] add light/dark variants of system tray icon https://github.com/AntiMicroX/antimicrox/issues/66
- [ ] (optional) update default icons

**Comment by gombosg** [comment]
Using system theme icons is a great idea because
- It makes packaging easier (removing [this](https://github.com/flathub/io.github.antimicrox.antimicrox/blob/27a7ce2fa5527750e3d8464c352c3fdc6b6226af/io.github.antimicrox.antimicrox.yml#L21) and [this](https://src.fedoraproject.org/rpms/antimicrox/blob/master/f/antimicrox.spec#_109))
- Also users can choose icons according to their own icon theme.

I think we can remove fallback if we use common icons. The system provides icon theme fallback mechanism anyway.
Like, I'm using the Ubuntu Humanity theme, and the `index.theme` says:
`Inherits=Adwaita,hicolor`
So this fallback mechanism is there for all icon themes.

Let me know if I can help with anything.

**Comment by pktiuk** [comment]
I would leave them, because on Windows and Mac they will be needed, but only as a compiled-in files (without installing them), moreover in case of any problems with some (badly prepared) themes fallback option is needed, because without it our app won't render some interface elements at all.

**Comment by pktiuk** [comment]
There is still problem with custom icons like:

games_config_custom ![16-actions-games_config_custom](https://user-images.githubusercontent.com/45544416/95721400-d4260a80-0c72-11eb-88b1-f5b5b650a3b0.png)

We should decide what to do with them.

**Comment by gombosg** [comment]
Either remove from UI or replace with other items from the theme?

**Comment by pktiuk** [comment]
I will look after similar icons, maybe there are some alternatives. (The most universal tool for this is `gtk3-icon-browser`)

**Comment by Hir-design** [comment]
I don't know if this is the right place, but it seems to be adequate for what I mean (I don't want to duplicate the problem). I mean, some of the icons in the program are missing, e.g. for "Reset", "Load", "Save" or "Save As" button in the main window after all these changes. Even more icons are missing after merging changes from the "icons_cleanup" branch, which is also missing in such windows as "Advanced", window with virtual keyboard and more.

**Comment by OlegPopow** [comment]
@Hir-design 

Out of curiosity, I compiled an unrolled version from the previous repository and there the problem described by you is not there, all icons are in place. Probably one of the commits of the new developers is responsible for this assumption. The question is - is it a bug or is it feauture?

**Comment by pktiuk** [comment]
I ti clearly a bug. Btw branch 'icons_cleanup' is not ready to merge yet.

**Comment by juliagoda** [comment]
I understand, I'm just warning what the changes are aiming at, because there are no part of icons. In the second turn, there would be icons in one place (those that were not) and vice versa, although not necessarily for each icon.

**Comment by OlegPopow** [comment]
It is obvious that it is a bug. Are you able to determine more or less when it could have sneaked in or should I try to take back the latest commites one by one? I'm not hiding that I'm an aesthete and the lack of icons makes my eyes unsatisfied.

**Comment by pktiuk** [comment]
@Hir-design  
Thanks for report, I have identified the source of this problem, I have missed some of names when I was changing custom icon names to more universal ones.

**Comment by pktiuk** [comment]
I think, after this merge we can close it for now.
