### ISSUE TITLE
profiles reset 

### ISSUE THREAD

**Issue by jamilbowey** [AntiMicroX/antimicrox#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

profiles will revert to default settings each boot up

### Expected Behavior

profiles should save ready to go on start but doesn't save at all

### Steps To Reproduce

change and create a profile 
restart computer 
profiles are all default 

### Environment

```markdown
- OS:
- AntiMicroX version:
```

**Comment by pktiuk** [comment]
You forgot to fill your environment

**Comment by jamilbowey** [comment]
How do I do that?

**Comment by pktiuk** [comment]
@jamilbowey   
This part of your raport is empty. 
```
- OS:
- AntiMicroX version:
```

**Comment by jamilbowey** [comment]
windows 11
antimicro 3.3.1

**Comment by pktiuk** [comment]
Then retest with the latest version.

**Comment by pktiuk** [comment]
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/618
