### ISSUE TITLE
[Linux] Motion sensors do not work if controller is connected via bluetooth after application was started

### ISSUE THREAD

**Issue by thesourcehim** [AntiMicroX/antimicrox#617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I connect my DualSense via bluetooth and then start antimicrox, all controls seem to be working fine including accelerometer and gyro. However, if I first start antimicrox and then connect the controller, application does not react to gamepad movements.

### Expected Behavior

Accel and gyro should cause application to react no matter when controller was connected.

### Steps To Reproduce

1. Start antimicrox
2. Connect DualSense via bluetooth
3. Try to move it. Application does not light accel or gyro indicators on its window.

### Environment

```markdown
- OS: Fedora 36
- AntiMicroX version: git4dec902
```

**Comment by pktiuk** [comment]
Could you test it with another application?    
It seems to be the issue with drivers or libraries.

**Comment by pktiuk** [comment]
Could you collect some logs from two cases? https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs

**Comment by thesourcehim** [comment]
Works fine if started after gamepad is connected
[antimicrox_connect_before_start.log](https://github.com/AntiMicroX/antimicrox/files/10047399/antimicrox_connect_before_start.log)

Accel/Gyro reaction not displayed properly if started before gamepad is connected
[antimicrox_connect_after_start.log](https://github.com/AntiMicroX/antimicrox/files/10047403/antimicrox_connect_after_start.log)

**Comment by pktiuk** [comment]
Thanks, I can also reproduce it with PS4 gamepad.
