### ISSUE TITLE
Not reading configs, all inputs show as [NO KEY]

### ISSUE THREAD

**Issue by FoxBlocks** [AntiMicroX/antimicrox#618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The program will almost never read my config files properly. It thinks there are no inputs set, so every entry is set to [NO KEY]. The program reads them correctly sometimes, but seemingly at random. It sometimes helps if I restart my computer first.

### Expected Behavior

The program should read the config files correctly each time.

### Steps To Reproduce

1. Open AntiMicroX
2. Try to load any config with at least one input
3. AntiMicroX will not show any of those inputs unless you're lucky

### Environment

```markdown
- OS: Windows 11 Home Build 22621.819
- AntiMicroX version: 3.3.1
```

### Anything else?

If you need any logs or config files, please let me know.

Thanks so much for keeping AntiMicro alive, and for bringing this excellent program to Windows!

**Comment by pktiuk** [comment]
This issue is already fixed in  https://github.com/AntiMicroX/antimicrox/pull/609 , but not released (yet).

I will close this issue after releasing new release.

**Comment by FoxBlocks** [comment]
Thank you!

**Comment by pktiuk** [comment]
You can test it with new beta release https://github.com/AntiMicroX/antimicrox/releases/tag/3.3.2-rc

**Comment by pktiuk** [comment]
Does everything work now?

**Comment by FoxBlocks** [comment]
Sorry, I haven't seen your messages. I'll try it right away.

**Comment by FoxBlocks** [comment]
Yes, it now works perfectly. Thank you!
