### ISSUE TITLE
Files on 3.3.2-rc assets are 3.3.1 release

### ISSUE THREAD

**Issue by philclifford** [AntiMicroX/antimicrox#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The assets on the 3.3.2-rc release appear to be those from the 3.3.1 release.

![image](https://user-images.githubusercontent.com/8797027/202917573-7c6f9a50-0363-4712-bc36-772764afa85d.png)

confusing for `apt` and humans, especially with the HOTFIX also being 3.3.1

### Expected Behavior

release 3.3.2-rc would be called and self-identify as 3.3.2-rc

### Steps To Reproduce

download the deb and apt install ./<the-deb> over 3.3.1

### Environment

```markdown
- OS:Ubuntu mate 22.10
- AntiMicroX version: 3.3.1
```

### Anything else?

no

**Comment by pktiuk** [comment]
This is because it is not yet 3.3.2 release. It is just a quick pre-release to check whether all of the introduced fixes.   
It is 3.3.1+some fixes.
