### ISSUE TITLE
uinput udev security

### ISSUE THREAD

**Issue by hendursaga** [AntiMicroX/antimicrox#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The [udev rules file](https://raw.githubusercontent.com/AntiMicroX/antimicrox/master/other/60-antimicrox-uinput.rules) looks like it basically opens up a giant security hole by letting the user(s) read all keyboard events without any constraints.

### Expected Behavior

Something more secure, like limiting the permissions to a group that the antimicrox executable is a member of.

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: Linux
- AntiMicroX version: 3.3.2
```

**Comment by pktiuk** [comment]
I don't think it is an issue.

1. There is no way to do it another way for Wayland. If you know one, then let me know.
2. None of the current package maintainers reported it as a security issue
3. Steam also uses these rules to ensure proper support. If you have installed steam, then you probably already have them applied. https://github.com/ValveSoftware/steam-devices
4. If you use X11, then it can be done also with xtest library
5. If you are afraid of the permissions you are giving to your apps, then use flatpak to mitigate this issue. https://github.com/AntiMicroX/antimicrox/wiki/Open-uinput-error
