### ISSUE TITLE
Name mismatch in Set selector drop down list.

### ISSUE THREAD

**Issue by soiamsoNG** [AntiMicroX/antimicrox#655]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Set sets name by Settings,

Open set selector's drop down list in assign key's Advance button

set1's name appear in  set4
set2's name appear in  set3

### Expected Behavior

be match

### Steps To Reproduce

Set several sets name by Settings,

Open set selector's drop down list in assign key 's  Advance button

### Environment

```markdown
Program Version 3.3.2
Compiled from packaging: flatpak
Built Against SDL 2.24.0
Running With SDL 2.24.0
Using Qt 5.15.7
Using Event Handler: XTest
Compositor type: x11
Host OS: org.kde.Platform Version: 5.15-22.08 Architecture: x86_64
```

**Comment by pktiuk** [comment]
Thanks for report, luckily this bug is easy to reproduce. :)
