### ISSUE TITLE
Add dark tray icon

### ISSUE THREAD

**Issue by soredake** [AntiMicroX/antimicrox#66]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/5204968/96367722-3d68ba80-1158-11eb-9ffa-cedb3dd4fe8b.png)
Light tray icon is hard to see in default kde theme.

**Describe the solution you'd like**
Add dark tray icon.

**Describe alternatives you've considered**

**Additional context**

**Comment by pktiuk** [comment]
I will investigate it as a part of https://github.com/AntiMicroX/antimicrox/issues/61

Maybe we could add several variants of tray icon to available themes Linux themes.

@soredake 
What is your icon theme?

**Comment by pktiuk** [comment]
This problem was already mentioned in legacy repository https://github.com/juliagoda/antimicroX/issues/133 opened by @protist

**Comment by soredake** [comment]
> I will investigate it as a part of #61
> 
> Maybe we could add several variants of tray icon to available themes Linux themes.
> 
> @soredake
> What is your icon theme?

Default, "Breeze".

**Comment by OlegPopow** [comment]
> This problem was already mentioned in legacy repository [juliagoda/antimicroX#133](https://github.com/juliagoda/antimicroX/issues/133) opened by @protist

I may be wrong, but what is the point of bouncing the ball and pointing the 'future request' in the old repo? Is this the way you want to point the finger and say "But it wasn't added by the previous maintainer"? What is the logical reason to refer to the old request? It could have been silent and then it wouldn't look so pathetic.

**Comment by pktiuk** [comment]
Nope, it has been already reported, but we have missed this issue during migration.  
Don't overinterpret every mention of old repository.

**Comment by OlegPopow** [comment]
But I will not overinterpret anything. I clearly indicated that I may be wrong. Don't take everything so personally to yourself. We are just people and we make mistakes. This is how it happens. 

As for the icons, it would be good to add something like papyrus folders.

https://github.com/PapirusDevelopmentTeam/papirus-folders

Here everyone could easily change the color - with one command and then load it into the program. This would make it a lot easier and save later submissions like "I'll ask for pink/seledite/grey icons".

**Comment by pktiuk** [comment]
This may be quite useful.  
Thanks.
(I am tired and ill and I don't want to spend time on offtopic discussions)

**Comment by gombosg** [comment]
@OlegPopow 

> What is the logical reason to refer to the old request?

As a maintainer, it's useful to acknowledge that this issue has been present for earlier users, they have reported it, and it's useful to refer back to earlier conversations. (In this case there was not much conversation.)
