### ISSUE TITLE
Some conflict with an GNOME extension Alphabetical App Grid

### ISSUE THREAD

**Issue by Skaamit** [AntiMicroX/antimicrox#666]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

I use «AntiMicroX» and an extension «Alphabetical App Grid» ( [Extensions.Gnome.org](https://extensions.gnome.org/extension/4269/alphabetical-app-grid/) | [Github](https://github.com/stuarthayhurst/alphabetical-grid-extension) ). At first everything was OK but now happening this.

https://i.imgur.com/lKAeWvF.png

«AntiMicroX» itself working fine, but this extension and Grid App are broken.

### Expected Behavior

What it just works.

### Environment

```markdown

- Fedora Linux 37
- GNOME 43.2
- Kernel: 6.0.12-300.fc37.x86_64
- Shell: bash 5.2.9
- LENOVA IdeaPad 5-14ITL05

```

**Comment by pktiuk** [comment]
> «AntiMicroX» itself working fine, but this extension and Grid App are broken.

Why do you report it here? If that extension is broken then report it then.

**Comment by Skaamit** [comment]
@pktiuk I thought it might be useful for you too. Anyway OK. Sorry to disturb you.
