### ISSUE TITLE
Outdated information in the "Credits" tab in the "About" window

### ISSUE THREAD

**Issue by Hir-design** [AntiMicroX/antimicrox#67]
**Describe the bug**
1. Click on "Help"
2. Choose "About"
3. Click on "Credits" tab

**Expected behavior**
You should find up-to-date information about the program being developed

**Configuration**
Version of antimicrox: 3.1.2 (from last commit)
System version: Arch Linux

**Comment by pktiuk** [comment]
That's right, only `About Development` tab was updated.

**Comment by gombosg** [comment]
I can take this, this doesn't require C++ knowledge. 😛
