### ISSUE TITLE
[Windows] XBox One controller failed to map left and right trigger correctly

### ISSUE THREAD

**Issue by noisemaker00** [AntiMicroX/antimicrox#677]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

I have an XBox One controller (1708) connected using wireless adapter.
When I map the controller the left and right triggers have weird behaviour:

- the left one values changes but the range is very limited (from Axis 8: 32767 to Axis 8: 32257)
- the right one seems not recognized at all

### Expected Behavior

Value changing for both left and right triggers when pressed.
I tried with Windows Game Device and both axis works correctly. I also tried with XPadder and it works correctly too.

### Steps To Reproduce

1. connect an XBox Controller
2. open AntMicroX and go to Map Controller
3. go to Left Trigger and press the trigger on controller

### Environment

```markdown
Program Version 3.3.2
Compiled from packaging: GitHub Portable Windows Release
Built Against SDL 2.0.20
Running with SDL 2.0.20
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 7sp1 Architecture: x86_64
```

**Comment by noisemaker00** [comment]
I already tried with suggested tools and both Steam and SDL2 Gamepad Tool recognize my Xbox gamepad correctly included the left and right triggers. This was the reason due to I put the issue here, I though the problem was not related to SDL2 but the way antmicro read the inputs.
If this is not related to AntMicro can you point me out the right way to solve?

**Comment by pktiuk** [comment]
That's interesting.     
Could you test it also with an old version of AntiMicroX for example this: https://github.com/AntiMicroX/antimicrox/releases/tag/3.2.0

**Comment by pktiuk** [comment]
Closing due to lack of feedback
