### ISSUE TITLE
xbox controller wont coonect

### ISSUE THREAD

**Issue by Evanmhjkoifgerhjw** [AntiMicroX/antimicrox#680]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

i am new to using this but i cant get it working? my xbox controller just wont connect to it, sorry if this is a stupid mistake but can anyone help

**Comment by kanedauy** [comment]
Same here, wen I start the connection with the program not running I can connect no problem, but wen AntimicroX is running I cant connect the controller.
The controller is a XBox Series X wireless controller with a Microsoft Wireless adapter.

Name: XBox Series X Controller
GUID: 030000005e040000120b00000000720011182834

**Comment by pktiuk** [comment]
This is problem with Xbox controller/SDL. Probably duplicate of https://github.com/AntiMicroX/antimicrox/issues/663 or https://github.com/AntiMicroX/antimicrox/issues/494
