### ISSUE TITLE
Can antimicrox support "Share" button on the XBox Series X/S controller?

### ISSUE THREAD

**Issue by Petard233** [AntiMicroX/antimicrox#683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

antimicrox似乎并不支持"Share" button on the XBox Series X/S controller

### Describe the solution you'd like

A similar software "JoyToKey" supports "Share" button, its developer said "Share" button is not accessible in the traditional Windows API (such as XInput or DirectInput)

**Comment by pktiuk** [comment]
Duplicate: https://github.com/AntiMicroX/antimicrox/issues/307
