### ISSUE TITLE
Support for Mapping Xbox Elite Controller 2 Back Paddles

### ISSUE THREAD

**Issue by LovecraftianGodsKiller** [AntiMicroX/antimicrox#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Be able to map the back paddles of the Xbox Elite 2 controller.

**Comment by pktiuk** [comment]
According to SDL files.
`SDL2/SDL_gamecontroller.h`   

```cpp
    SDL_CONTROLLER_BUTTON_PADDLE1,  /* Xbox Elite paddle P1 */
    SDL_CONTROLLER_BUTTON_PADDLE2,  /* Xbox Elite paddle P3 */
    SDL_CONTROLLER_BUTTON_PADDLE3,  /* Xbox Elite paddle P2 */
    SDL_CONTROLLER_BUTTON_PADDLE4,  /* Xbox Elite paddle P4 */
    SDL_CONTROLLER_BUTTON_TOUCHPAD, /* PS4/PS5 touchpad button */
    SDL_CONTROLLER_BUTTON_MAX
} SDL_GameControllerButton;
```
Paddles should be shown.
Also touchpad button should be supported.

**Comment by shc261392** [comment]
I'm using Xbox Elite Controller 2 and the latest 3.3.2 release, but the paddles are not shown for me. There is, however, six unknown buttons called `Button 16`, `Button 17`, ..., `Button 21` showed, but I did a little testing and it seems they are not the paddles.

Is there anything I could do to help find out why it is not shown?

**Comment by shc261392** [comment]
Sure, here's the log. I pressed each each paddles once and did it for five times in total.

[xb_elite2_paddles.log](https://github.com/AntiMicroX/antimicrox/files/10355616/xb_elite2_paddles.log)

And thanks for the information about the SDL issue.

**Comment by pktiuk** [comment]
This is clearly an SDL Bug.

```
cat ./xb_elite2_paddles.log | grep -i "Got button with id:
```

Gives us list of logs:

```
[04:54:12.669] 🐞DEBUG	Processing event: SDL_CONTROLLERAXISMOTION From joystick with instance id: 0 Got button with id: 0 is one of the GameControllers: true is one of the joysticks:false (file /src/inputdaemon.cpp:738)
[04:54:12.669] 🐞DEBUG	Processing event: SDL_JOYAXISMOTION From joystick with instance id: 0 Got button with id: 0 is one of the GameControllers: true is one of the joysticks:false (file /src/inputdaemon.cpp:738)
[04:54:12.709] 🐞DEBUG	Processing event: SDL_CONTROLLERAXISMOTION From joystick with instance id: 0 Got button with id: 1 is one of the GameControllers: true is one of the joysticks:false (file /src/inputdaemon.cpp:738)
[04:54:12.709] 🐞DEBUG	Processing event: SDL_JOYAXISMOTION From joystick with instance id: 0 Got button with id: 1 is one of the GameControllers: true is one of the joysticks:false (file /src/inputdaemon.cpp:738)
```
There are no values from range 16-19 (which should describe these buttons. SDL does not report button presses. According to logs your controller reported only motion events and device added events.

**Comment by stefs** [comment]
Is there a corresponding issue in [SDL](https://github.com/libsdl-org/SDL)?
Maybe https://github.com/libsdl-org/SDL/issues/6442 is related?

**Comment by pktiuk** [comment]
> Is there a corresponding issue in [SDL](https://github.com/libsdl-org/SDL)? 

I don't know.

>Maybe [libsdl-org/SDL#6442](https://github.com/libsdl-org/SDL/issues/6442) is related?

I think this issue tackles a different problem.   

You can try to use tool called `gamepadmap` from SDL https://github.com/libsdl-org/SDL/tree/main/test to test your gamepad once more and use data reported by that tool to report this problem to SDL devs.

**Comment by jre21** [comment]
I just tested out an Xbox Elite 2 controller on Arch Linux after having updated to the latest firmware.  (antimicrox version 3.3.2, sdl2 version 2.26.2, Linux kernel 6.1.7-zen1)  Logs from both Antimicrox and SDL report the paddles as follows:

- the upper (small) paddles are buttons 13 (left) and 11 (right)
- the lower (large) paddles are buttons 14 (left) and 12 (right)

However the antimicrox GUI doesn't show buttons for these paddles, instead skipping directly from L Shoulder and R Shoulder to the unmapped buttons 16-21.

Apparently the Linux kernel only started recognizing the paddles in 6.1 ([Phoronix link](https://www.phoronix.com/news/Linux-6.1-XPad)), which may have caused some of the confusion up-thread.  At any rate, when I keyed all the buttons into SDL's controllermap script, it spat out the following:

`030000005e040000000b00000f050000,Xbox One Elite 2 Controller,platform:Linux,crc:085d,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,paddle1:b13,paddle2:b11,paddle3:b14,paddle4:b12,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,`

**Comment by jre21** [comment]
I opened libsdl-org/SDL#7211 based on the above.

**Comment by pvtri96** [comment]
@pktiuk Hi, the issue on SDL seems to be fixed by now. Can you try integrate the latest version https://github.com/libsdl-org/SDL/issues/7211#issuecomment-1800900845 and release another RC?

**Comment by pktiuk** [comment]
@pvtri96   Could you test this release and let me know whether everything is okay?

https://github.com/AntiMicroX/antimicrox/releases/tag/3.4.0-rc1

**Comment by pvtri96** [comment]
@pktiuk I gave it a try, and sadly still not possible. SDL itself doesn't match it.
