### ISSUE TITLE
[Linux] Auto Profiles Support EXE files from Wine & Proton

### ISSUE THREAD

**Issue by trymeouteh** [AntiMicroX/antimicrox#69]
Most games people play on Linux are Window games though Wine or Proton. Please allow us to add EXE files to the auto profiles on Linux and have it know when that EXE files is running in any Wine install or any Proton install.

**Comment by gombosg** [comment]
Hi, let us help with testing a bit here. Have you tried using the auto profile dialog in settings? How did it work for you? E.g. based on window class or title.

**Comment by pktiuk** [comment]
@trymeouteh 
If you use lutris it would be much better and simpler to add AntiMicroX with appropiate flags to list of scripts executed before turning on executable. It should do this job just fine.

**Comment by pktiuk** [comment]
This is issue very similar to https://github.com/AntiMicroX/antimicrox/issues/24
