### ISSUE TITLE
Constantly reverting back to <new> config

### ISSUE THREAD

**Issue by glenviewjeff** [AntiMicroX/antimicrox#696]
For some reason the application (Windows build) keeps reverting back to the empty configuration after some period of use. I haven't yet correlated it to just a period of time, minimizing the application, another application accessing the "joystick"/controller directly or the PC going into idle standby. After the application has reset into the "new" state, I have to re-load my saved mapping.

**Comment by pktiuk** [comment]
### Please follow our issue templates when reporting bugs or requesting features.

The devs put in hours of effort, and you should show enough respect to put in a few minutes & follow the template.
Following the template also provides us all the information we need, without having to ask for it.
Closing. Please create a new issue following the template if you would like assistance.
