### ISSUE TITLE
Program crashes and no longer opens if you have the Mayflash Gamecube Adapter Driver installed and plugged in

### ISSUE THREAD

**Issue by JMartinez9820** [AntiMicroX/antimicrox#697]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

If you have installed the driver for the Mayflash Gamecube Adapter for Switch/Wii U and PC, the program will crash and no longer open until you have removed the device from the computer or uninstalled the driver.

### Expected Behavior

The program should not open even when opening as an administrator if the Mayflash GameCube Adapter driver is installed, along with the device being plugged in.

### Steps To Reproduce

1. Go to the Mayflash Support Website
2. Select W012
3. Download the driver that adds the rumble options (scroll down)
4. After installation, try opening AntiMicroX
5. It should not load up at all

### Environment

```markdown
Program Version 3.3.2
OS: Windows 11
```

**Comment by pktiuk** [comment]
> The program should not open

Why the program should not open?

**Comment by pktiuk** [comment]
Closing due to lack of feedback
