### ISSUE TITLE
Anti Micro is not saving files with controller button mapped to keyboard key

### ISSUE THREAD

**Issue by cadencadet** [AntiMicroX/antimicrox#718]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

I play the binding of isaac on computer. To restart your runs you hold the R key so I bind the R key to my right or left stick. However, I save these files with the r key setting, and yet the program never remembers the file whenever I use my PC again. I try loading that file that I saved the r key bind to, and it just doesn't have the R key setting so I must set up the profile again every time

### Expected Behavior

I expect anti to actually be saving these files. It never saves them and I always have to remake my key binds. 

### Steps To Reproduce

Open antimicrox. Set LS or RS click to R key. Save as whatever file name in this PC>documents. Close anti micro (just the tab not program). Game. Unpair controller from pc. Close laptop for hours. Reopen laptop, reopen antimicrox, and see that the program doesn't have the R key file loaded and when I attempt to load it, nothing happens or the file no longer has my keybinds.

### Environment

```markdown
Program Version 3.3.1
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.0.20
Running With SDL 2.0.20
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment]
Firstly update your AntiMicroX to the latest version, then check if the issue persists.

**Comment by pktiuk** [comment]
Closing due to lack of any feedback
