### ISSUE TITLE
Thrustmaster TWCS many buttons not recognised

### ISSUE THREAD

**Issue by Jassida15** [AntiMicroX/antimicrox#722]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Various buttons aren't recognised. Software seems to think this throttle is an Xbox Controller. Ministick works fine. Xbox controller works fine.

### Expected Behavior

Antimicro works fine. I want AntimicroX to recognise my TWCS correctly like Antimicro does

### Environment

Windows 11. 7700x AM5

**Comment by pktiuk** [comment]
![obraz](https://user-images.githubusercontent.com/45544416/218136449-313d8c1e-0da6-479b-a9fd-b536fdd396cb.png)

**Comment by Jassida15** [comment]
It has randomly started working now anyway
