### ISSUE TITLE
Cannot set default auto profile for specific device

### ISSUE THREAD

**Issue by github2023-blip** [AntiMicroX/antimicrox#727]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

First I want to say I am impressed how well AntiMicroX works already! Plugging the controller in, specifying custom shortcuts and auto switching profiles generally work as expected. Thank you very much!

There is one issue (or maybe I just miss something, if so, please excuse me), it seems I cannot set a default profile for a specific controller. If I understand the default checkbox correctly, it should only work, if no window property is selected (the option to select the profile as default is inactivated when setting a window property - see screenshot). Instead the programm fails to save the default profile due to a non matching window property.

Using the all device profile switching between the custom profile and the default works.
But I intend to use more than one device (not yet tested) and a default for each device would be wonderful.

I did not find any meaningful messages in the log file.

Thank you again and any help is appreciated!

### Expected Behavior

Create a default auto profile for a specific device.

### Steps To Reproduce

- Go to Settings -> Auto Profile
- Add auto profile
- Select/browse profile
- Select device (and acknowledge that this selection will be used instead of the all default profile option)
- Select checkbox "Set as Default for Controller"
- Click "Ok"
- Warning/info message pops up (see screenshot)

### Environment

```markdown
Program Version 3.3.3
Program Compiled on Feb 16 2023 at 17:23:48
Built Against SDL 2.26.3
Running With SDL 2.26.3
Using Qt 5.15.8
Using Event Handler: XTest
Compositor type: x11
Host OS: arch Version: unknown Architecture: x86_64
```

### Anything else?

![2023-02-17_window_prop_excludes_default](https://user-images.githubusercontent.com/125646124/219596722-aea26ba1-0924-4818-87dd-555f803cbe4c.png)

![2023-02-17_default_needs_window_prop](https://user-images.githubusercontent.com/125646124/219596694-53e92bbf-9c65-4e78-8532-995ddba16528.png)

**Comment by pktiuk** [comment]
You are right.   
Selecting option `Set as default for Controller` should disable this warning window.   
I will look into this

**Comment by github2023-blip** [comment]
Thank you for the very quick fix!

**Comment by pktiuk** [comment]
BTW @frealgagu   
Could you start using flag [-DANTIMICROX_PKG_VERSION](https://github.com/AntiMicroX/antimicrox/blob/master/BUILDING.md#build-options-for-cmake) (`aur repo package` or something similar) in arch builds? It would help me to check type and source of package.
