### ISSUE TITLE
Mouse to R stick is not responding correctly in game.

### ISSUE THREAD

**Issue by WildAchiever** [AntiMicroX/antimicrox#731]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Hello, When the mouse (Mouse up, down, left, and right) was linked to the right stick of the controller, it would respond correctly in the home of the computer, but when it was used with a game (Valorant), it would not look around. everything else worked correctly.

### Expected Behavior

The looking function to work.

### Steps To Reproduce

1. Setup the R stick as the mouse.
2. load into a game.

### Environment

```markdown
Program Version 3.3.3
Compiled from packaging: GitHub Portable Windows Release
Built Against SDL 2.0.20
Running With SDL 2.0.20
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment]
Could you test it with another game? Valorant is very problematic one because of used anticheat.

**Comment by pktiuk** [comment]
Closing due to lack of feedback

**Comment by moxze** [comment]
Hello I have the same issue with the same game
