### ISSUE TITLE
ps4 controller not recognized

### ISSUE THREAD

**Issue by GrandmastaL** [AntiMicroX/antimicrox#732]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

The SDl2 gamepad recognizes and maps my ps4 controller and I even tried to run antimicrox in administrator mode (on Windows) but it still says that no joystick was found 

### Expected Behavior

my joystick to be recognized

### Environment

```markdown
Program Version 3.3.3
Compiled from packaging: GitHub Portable Windows Release
Built Against SDL 2.0.20
Running With SDL 2.0.20
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment]
How you connected this controller?    
My PS4 gamepad works well.

**Comment by GrandmastaL** [comment]
Yes I did, but it's fine. I have just moved on with another controller adapter

**Comment by GrandmastaL** [comment]
> How you connected this controller? My PS4 gamepad works well.

Thank you for the quick response though. I'll still recommend this product.
