### ISSUE TITLE
R trigger is clicking everything

### ISSUE THREAD

**Issue by ChipZRR** [AntiMicroX/antimicrox#739]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

When I click R trigger it starts to click almost every possible bind like crazy. (video) On the video I just once pressed R trigger. Nothing else.

### Expected Behavior

I expect to click just R trigger.

### Anything else?

https://www.youtube.com/watch?v=MA6H-KVR000&ab_channel=AdamVan%C3%AD%C4%8Dek

**Comment by pktiuk** [comment]
![image](https://user-images.githubusercontent.com/45544416/222977796-dc4e124e-ed48-4542-9b8d-dc91121287c1.png)

**Comment by ChipZRR** [comment]
> ![image](https://user-images.githubusercontent.com/45544416/222977796-dc4e124e-ed48-4542-9b8d-dc91121287c1.png)

done

**Comment by pktiuk** [comment]
You have faulty controller or wrong/broken driver. This is not caused by AntiMicroX

**Comment by ChipZRR** [comment]
> You have faulty controller or wrong/broken driver. This is not caused by AntiMicroX

thanks
