### ISSUE TITLE
R trigger is clicking every other button.

### ISSUE THREAD

**Issue by ChipZRR** [AntiMicroX/antimicrox#740]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

When I click R trigger it starts to click almost every possible bind like crazy. (video) On the video I just once pressed R trigger. Nothing else.

### Expected Behavior

I expect to click just R trigger.

### Environment

```markdown
Program Version 3.3.3
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.0.20
Running With SDL 2.0.20
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

### Anything else?

https://www.youtube.com/watch?v=MA6H-KVR000&ab_channel=AdamVan%C3%AD%C4%8Dek

**Comment by pktiuk** [comment]
https://github.com/AntiMicroX/antimicrox/issues/740
