### ISSUE TITLE
GPD Win 3 back buttons

### ISSUE THREAD

**Issue by asdf23** [AntiMicroX/antimicrox#743]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

The two buttons on the back of the PC are not supported.

### Expected Behavior

Please recognize these two buttons

### Steps To Reproduce

Use GPD Win 3 with software

### Environment

```markdown
Program Version 3.3.3
Program Compiled on Feb 13 2023 at 00:00:00
Built Against SDL 2.26.2
Running With SDL 2.26.3
Using Qt 5.15.8
Using Event Handler: XTest
Compositor type: x11
Host OS: fedora Version: 36 Architecture: x86_64
```

### Anything else?

Left Button:
Event Handler: XTest
Native Key Value: 0xff1b
Qt Key Value: 0x1000000
antimicro Key Value: 0x1000000

Right Button:
Not recognized at all effect is Ctrl+Alt+Del

**Comment by asdf23** [comment]
![image](https://user-images.githubusercontent.com/4165735/224550382-0870667a-80ba-45f9-9b40-607e5b15c0c8.png)

**Comment by pktiuk** [comment]
You should report this to libsdl because they do map all of these buttons.

**Comment by pktiuk** [comment]
You can check issues https://github.com/AntiMicroX/antimicrox/issues/685 and https://github.com/AntiMicroX/antimicrox/issues/629
