### ISSUE TITLE
DualShock 4 cannot be used outside AntimicroX if connected via USB

### ISSUE THREAD

**Issue by maxigaz** [AntiMicroX/antimicrox#746]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

While my DualShock 4 is connected via USB, AntimicroX grabs the controller so other applications and games can't use it.

### Expected Behavior

All of the following is supposed to work:

- Controlling the system's mouse cursor with the controller's touchpad
- Querying the controller's battery level with `cat /sys/class/power_supply/ps-controller-battery-*/capacity`
- Navigating the menu in RetroArch

### Steps To Reproduce

1. Delete or rename `~/.config/antimicrox/antimicrox_settings.ini`.
2. Launch AntimicroX.
3. Connect the DualShock 4 through a USB cable.
4. Try using the touchpad.

### Environment

```markdown
Program Version 3.3.3
Program Compiled on Feb  2 2023 at 03:05:34
Built Against SDL 2.26.2
Running With SDL 2.26.4
Using Qt 5.15.8
Using Event Handler: XTest
Compositor type: x11
Host OS: arch Version: unknown Architecture: x86_64
```

### Anything else?

When the controller is connected via Bluetooth, everything is working correctly.

**Comment by pktiuk** [comment]
No matter, how, or what kind of controller is connected it is handled by AntiMicroX in the same way, the only difference may be in underlying mechanisms.

This difference may be caused either by SDL library used for handling gamepads, or it could be linked directly with driver of PS4 gamepad in Linux. I am not sure whether can I provide you any other support. (you can try to use [another ps4 driver](https://www.phoronix.com/news/Sony-DualShock4-PlayStation-Drv) )

**Comment by maxigaz** [comment]
> you can try to use [another ps4 driver](https://www.phoronix.com/news/Sony-DualShock4-PlayStation-Drv)

That's what I'm using now (with kernel v6.2.6), and I had the same issue with the old PS4 driver, too.

**Comment by maxigaz** [comment]
I see that the AppImage version of AntimicroX bundles SDL 2.24.2. And sure enough, it's working.

**Comment by pktiuk** [comment]
If it works with 2.24.2, but is broken with 2.26, then you should report it to libsdl repo https://github.com/libsdl-org/SDL/issues
