### ISSUE TITLE
AntimicroX only detects the controller when run as root

### ISSUE THREAD

**Issue by jorgeperezlara** [AntiMicroX/antimicrox#754]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Running in Fedora 37, from the DNF package, AntiMicroX seems unable to read the controller at all. Other tools such as PCSX2 cannot either, but strangely enough Firefox is able to.

I have tried the DNF package and the Flatpak version, even adding manually the udev rule seems to be of no effect here. I'm using a Stadia Controller through bluetooth after unlocking it with Google's official method.

### Expected Behavior

The Gamepad should be detected.

### Steps To Reproduce

1. Connect the Stadia gamepad
2. Open AntimicroX

### Environment

```markdown
Fedora 37
AntimicroX 3.3.3
Stadia Gamepad.
```

**Comment by pktiuk** [comment]
- Firstly `Copy and paste text from Info window (Help->About->Info)`    
- Secondly, do other gamepads work properly? If others controllers work properly,, then it means, that Stadia one is not supported by SDL and you should report it there https://github.com/libsdl-org/SDL
