### ISSUE TITLE
Segmentation Fault when change profile from command line

### ISSUE THREAD

**Issue by cyberconan** [AntiMicroX/antimicrox#76]
**Describe the bug**
When change profile from command line, always return a seg fault.

**To Reproduce**
[karl@CyberPortatil ~]$ antimicrox --profile ~/Software/configs/antimicro/DOS.gamecontroller.amgp
Segmentation fault (core dumped)
[karl@CyberPortatil ~]$ antimicrox --profile ~/Software/configs/antimicro/WIN.gamecontroller.amgp
Segmentation fault (core dumped)

In dmesg I see a lot of lines like (appear always when change antimicrox profile from my .sh files) 
[11887.666820] antimicrox[203273]: segfault at c ip 00007f1867ea08d2 sp 00007fffc38dafc0 error 4 cpu 7 in libQt5Widgets.so.5.15.1[7f1867e64000+3b0000]
[11910.791616] antimicrox[203350]: segfault at c ip 00007f9d0724b8d2 sp 00007ffddbaa71e0 error 4 cpu 6 in libQt5Widgets.so.5.15.1[7f9d0720f000+3b0000]

**Expected behavior**
No errors in console or dmesg.

**Configuration**
I'm using antimicrox 3.1.2 compiled from AUR in Archlinux.

**Additional context**
This is not a critical issue, is only a low problem because antimicrox do well the change from a profile to another one from command line, but always returns the error commented.

**Comment by gombosg** [comment]
I can't repro this on Fedora with the same 3.1.2 version.

- Do you have this issue when you have the file in a different location e.g. home folder?
- Do you have this issue when loading the same profile from the GUI?
- Do you have this issue when building a binary for yourself and trying with that?

**Comment by cyberconan** [comment]
Hi!

- Yes, same error changing profile from /home folder:
- No, no errors changing profile from GUI.
- I recompiled today with 3.1.3 version from [AUR](https://aur.archlinux.org/packages/antimicrox), but same error.

**Comment by gombosg** [comment]
Really strange. @pktiuk or @AriaMoradi , chance of a repro?

**Comment by pktiuk** [comment]
I have reproduced it

```
$ antimicrox --profile ./konfig2.gamecontroller.amgp  --log-level warn
Segmentation fault (core cumped)
```

But as @cyberconan told, it is a low priority issue, because this bug doesn't affect functionality of app.

**Comment by AriaMoradi** [comment]
A seg fualt is usually closes a process. maybe it's a sub-processes that wont make the app crash and burn.

**Comment by jrd** [comment]
I cannot load or unload a profile from command line because of this crash.
I need it to manage antimicrox from scripts.

**Comment by pktiuk** [comment]
This issue seems to be caused by problems with deleting some objects (probably multiple times).
