### ISSUE TITLE
8bitdo Pro 2 Controller P1 / P2 buttons functionality

### ISSUE THREAD

**Issue by ThoseWhoFight** [AntiMicroX/antimicrox#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

There's currently no way for antimicrox to see the two back paddles and thus, are unable to be remapped to keyboard keys. There is software that comes with the controller that allows you to remap the two back paddles/buttons but only to existing buttons on the gamepad (ex: A, B, X, Y). Within Antimicrox they don't see to be recognized at all, so they are unable to be remapped to something such as a keyboard key.

### Describe the solution you'd like

I'd like the ability to remap the back paddles to keyboard commands or keys.

### Describe alternatives you've considered

REWASD, but they seem to have the same issue. It can only recognize the controller as an xbox controller with no extra buttons, thus cannot be remapped.

**Comment by pktiuk** [comment]
Duplicate https://github.com/AntiMicroX/antimicrox/issues/629
