### ISSUE TITLE
the l stick keeps going right on linux

### ISSUE THREAD

**Issue by MariahWest01** [AntiMicroX/antimicrox#780]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

The l stick keeps going right when the joystick isnt being touched. This doesnt happen when antimicrox isnt running. 

### Expected Behavior

The l stick not being stuck

### Steps To Reproduce

I move the l stick

### Environment

```markdown
Program Version 3.3.3
Program Compiled on Feb  4 2023 at 00:08:24
Built Against SDL 2.26.2
Running With SDL 2.26.5
Using Qt 5.15.9
Using Event Handler: XTest
Compositor type: x11
Host OS: arch Version: unknown Architecture: x86_64
```

**Comment by pktiuk** [comment]
Could you provide some info about gamepad and some screenshots from calibration window?

**Comment by pktiuk** [comment]
Closing due to lack of feedback
