### ISSUE TITLE
Cannot map opposite direction inputs from Joystick

### ISSUE THREAD

**Issue by Hartagil** [AntiMicroX/antimicrox#785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

i wish to assign a key for when i push forward on my Joystick: Possible
i wish to assign a key for when i pull backward on my Joystick: Not Possible
>both input is shared by same mapping destination ( pushing forward and pulling back lights up the same button for assignment)

Same with yanking the joystick left and yanking right
Same with rotating joystick clockwise and rotating anticlockwise

### Describe the solution you'd like

i would like each Joystick action to be able to map to a seperate key

### Describe alternatives you've considered

If its possible i could accept all actions to the right to be trigger button plus yank right or trigger button plus rotate clockwise etc
but that would be cumbersome and not an elegant solution

**Comment by pktiuk** [comment]
> i wish to assign a key for when i push forward on my Joystick: Possible
> i wish to assign a key for when i pull backward on my Joystick: Not Possible

I don't understand your request. What do you mean by pullling backward? AntiMicroX supports all 4 (or 8) directions which you can point to with your joystick.

**Comment by pktiuk** [comment]
Closing due to lack of feedback
