### ISSUE TITLE
Assigning Text Entry to button doesn't assign proper string.

### ISSUE THREAD

**Issue by Laulajatar** [AntiMicroX/antimicrox#79]
I open the advanced settings for a button, select Text Entry, enter "Test" and press Insert. 
The button says [Text] Test.
After closing and reopening the advanced window, it says only [Text], the entered text is gone. It also never executes when pressing the controller button.

**Comment by zicklag** [comment]
I'm also getting this issue when using the Flatpak installation on two different Pop!_OS ( Ubuntu ) 20.04 machines.

**Comment by pktiuk** [comment]
We have regression here.  This feature worked earlier.  
I will later try to find out which commit caused this problem.

**Comment by pktiuk** [comment]
It is caused by deb11f2e97c0ff092a620d7f24c9d41f7e741ed7

**Comment by pktiuk** [comment]
@Laulajatar @zicklag   
Thank you for your reports. This fix will be shipped with the next release.

**Comment by zicklag** [comment]
Awesome, thanks for the fix!

**Comment by Laulajatar** [comment]
Thank you very much!
