### ISSUE TITLE
Detects a Game controller that does not exist

### ISSUE THREAD

**Issue by sampctech** [AntiMicroX/antimicrox#792]
I am using a custom created joystick. I was able to open antimocrox before & it would find the same 12 button, 2 axis Generic USB Joystick. Since installing version 3.3.3, I am now getting a G-Shark GS-GP702 (Game Controller 1) as soon as it opens. I have no idea what this is, but it is registering some of the buttons as axis instead. I can't use any of the configs I had setup for Trainz, ATS, ETS, or even JNES. is there a way to add another joystick to antimicro that I am not finding? Or to just create a 12 button mapping with a dual axis arcade stick?
![antimicroerror](https://github.com/AntiMicroX/antimicrox/assets/54453917/45a1595e-a2d1-4e2c-b046-7e8e0840dfe6)

**Comment by pktiuk** [comment]
### Please follow our issue templates when reporting bugs or requesting features.

The devs put in hours of effort, and you should show enough respect to put in a few minutes & follow the template.
Following the template also provides us all the information we need, without having to ask for it.   
Closing. Please create a new issue following the template if you would like assistance.
