### ISSUE TITLE
how do i change the controller

### ISSUE THREAD

**Issue by LhymeFruit** [AntiMicroX/antimicrox#793]
???

**Comment by LhymeFruit** [comment]
really? "not planned" you are lazy

**Comment by LhymeFruit** [comment]
lazy dev alert

**Comment by pktiuk** [comment]
I won't even bother with helping someone who can't properly fill the issue.

![image](https://github.com/AntiMicroX/antimicrox/assets/45544416/450b0fd8-4bb6-471a-8d5f-5912f6c2396d)
