### ISSUE TITLE
Cannot seem to get debug log to debug why execute doesn't seem to be working

### ISSUE THREAD

**Issue by cjwomack** [AntiMicroX/antimicrox#795]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Hi there,

I want a debug log to debug a particular problem or whether I'm making a mistake re execute function...

I'm trying to run an .exe with arguments either python or powershell or even just the .exe

It doesn't appear to be working the execute function but before I wanted to submit a bug report for that or to see if I was doing anything wrong for that I wanted the debug log, I've tried both the gui and command line launching options and it doesn't seem to work.

Using the latest version, the executable x64 for Windows. I am running Windows 10.
Hopefully I've supplied enough information, it's nighttime here so I'm a bit drowsy but I thought I should submit these now because of potential time zone issues

Looked at https://github.com/AntiMicroX/antimicrox/issues/349 and https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs

### Expected Behavior

A debug log
(Potentially Execute working - but that would be new issue, though I'm not sure I'm doing something idiotic because of late hour, hence wanted log)

### Steps To Reproduce

1. Install x64 executable (not zip) for Windows
2. Either try GUI or launch via command line
3. No log

### Environment

```markdown
Program Version 3.3.4
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.26.5
Running With SDL 2.26.5
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment]
Unluckily Windows does not allow GUI apps printing in terminal (it is really annoying when I have to do something on that platform), but you can still get files with logs. Just Go to settings->Advanced and select log level and target log file. You should be also able to specify log file with commandline

**Comment by cjwomack** [comment]
How is your suggestion different from https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs?

I already did both of those steps before submitting this report and they didn't work...
Commandline based
and
GUI based

None of those worked.

I did ls in powershell and looked in the file path that I specified also in Windows Explorer

**Comment by pktiuk** [comment]
Closing due to lack of feedback
