### ISSUE TITLE
mouse

### ISSUE THREAD

**Issue by BlocksOfGold** [AntiMicroX/antimicrox#798]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

mouse up down left and right wont move the mouse just the hitbox

### Expected Behavior

it should move the entire mouse

**Comment by pktiuk** [comment]
![image](https://github.com/AntiMicroX/antimicrox/assets/45544416/d96dc418-ac9b-49ad-93c7-6b8a3579905e)
