### ISSUE TITLE
ARM build failure

### ISSUE THREAD

**Issue by AriaMoradi** [AntiMicroX/antimicrox#80]
**Describe the bug**
Trying to build for raspberry pi 3B+ on raspbian os it fails.

**To Reproduce**
1- be on raspberry pi on raspbian os
2- install build dependencies according to `BULDING.md`
3- proceed to build
4- fail on shared library linking
(I ran make with `-j 4` flag, don't think it affects anything but mentioning it anyway)

**Expected behavior**
build should work

**Screenshots**

**Configuration**
Version of antimicrox: 3.1.2
Used package: N/A
System version:

**Additional context**
build log:
```
[ 98%] Building CXX object CMakeFiles/antilib.dir/src/eventhandlers/uinputeventhandler.cpp.o
[ 98%] Building CXX object CMakeFiles/antilib.dir/qrc_resources.cpp.o
[100%] Linking CXX shared library libantilib.so
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/gamecontrollerdpad.cpp.o:(.data.rel.ro+0x0): multiple definition of `typeinfo for JoyDPadXml<VDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.data.rel.ro+0x5c): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/gamecontrollerdpad.cpp.o:(.data.rel.ro+0xc): multiple definition of `typeinfo for JoyDPadXml<JoyDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.data.rel.ro+0x68): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/gamecontrollerdpad.cpp.o:(.rodata+0x78): multiple definition of `typeinfo name for JoyDPadXml<VDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.rodata+0xe8): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/gamecontrollerdpad.cpp.o:(.rodata+0x90): multiple definition of `typeinfo name for JoyDPadXml<JoyDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.rodata+0x100): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/gamecontrollerset.cpp.o:(.data.rel.ro+0x0): multiple definition of `typeinfo for JoyDPadXml<VDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.data.rel.ro+0x5c): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/gamecontrollerset.cpp.o:(.data.rel.ro+0xc): multiple definition of `typeinfo for JoyDPadXml<JoyDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.data.rel.ro+0x68): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/gamecontrollerset.cpp.o:(.rodata+0x130): multiple definition of `typeinfo name for JoyDPadXml<VDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.rodata+0xe8): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/gamecontrollerset.cpp.o:(.rodata+0x148): multiple definition of `typeinfo name for JoyDPadXml<JoyDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.rodata+0x100): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/xml/gamecontrollerdpadxml.cpp.o:(.data.rel.ro+0x0): multiple definition of `typeinfo for JoyDPadXml<VDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.data.rel.ro+0x5c): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/xml/gamecontrollerdpadxml.cpp.o:(.data.rel.ro+0xc): multiple definition of `typeinfo for JoyDPadXml<JoyDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.data.rel.ro+0x68): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/xml/gamecontrollerdpadxml.cpp.o:(.rodata+0x6c): multiple definition of `typeinfo name for JoyDPadXml<VDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.rodata+0xe8): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/gamecontroller/xml/gamecontrollerdpadxml.cpp.o:(.rodata+0x84): multiple definition of `typeinfo name for JoyDPadXml<JoyDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.rodata+0x100): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/xml/setjoystickxml.cpp.o:(.data.rel.ro+0x0): multiple definition of `typeinfo for JoyDPadXml<VDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.data.rel.ro+0x5c): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/xml/setjoystickxml.cpp.o:(.data.rel.ro+0xc): multiple definition of `typeinfo for JoyDPadXml<JoyDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.data.rel.ro+0x68): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/xml/setjoystickxml.cpp.o:(.rodata+0xa0): multiple definition of `typeinfo name for JoyDPadXml<VDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.rodata+0xe8): first defined here
/usr/bin/ld: CMakeFiles/antilib.dir/src/xml/setjoystickxml.cpp.o:(.rodata+0xb8): multiple definition of `typeinfo name for JoyDPadXml<JoyDPad>'; CMakeFiles/antilib.dir/src/gamecontroller/xml/moc_gamecontrollerdpadxml.cpp.o:(.rodata+0x100): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/antilib.dir/build.make:4329: libantilib.so.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/antilib.dir/all] Error 2
make: *** [Makefile:152: all] Error 2 
```

**Comment by pktiuk** [comment]
There was a very similar issue on legacy repo. https://github.com/juliagoda/antimicroX/issues/111   
It seemed to be caused by lack of package `qtbase5-dev` in raspbian repositories.

I think the simplest solution for now would be installing AntiMicroX using flatpak package.

@AriaMoradi 
Could you check this?

**Comment by AriaMoradi** [comment]
`qtbase5-dev` version `5.11.3+dfsg1-1+rpi1+deb10u` is installed.
Is'nt flatpak made for amd64 too?

**Comment by pktiuk** [comment]
> qtbase5-dev version 5.11.3+dfsg1-1+rpi1+deb10u is installed.  

Interesting. If it is installed, everything should work properly.  
According to terminal output it is a problem with linking, not with compilation itself.  
Maybe a proper solution would be cross-compiling package for arm...  
I will investigate it later.  

> Is'nt flatpak made for amd64 too?

Yes, flatpak is built for x86_64 (called also amd64) and aarch64.
![image](https://user-images.githubusercontent.com/45544416/98439190-6e516500-20f0-11eb-8c9d-e74347f2bc85.png)  
[flatpak repo](https://github.com/flathub/io.github.antimicrox.antimicrox)

**Comment by gombosg** [comment]
AFAIK Raspberry is ARM and not x86 architecture. So this is the same as:

https://bugzilla.redhat.com/show_bug.cgi?id=1849216

Let me know id you find a solution, then I can also fix the Fedora package.

**Comment by pktiuk** [comment]
@gombosg  
Yes, Raspberry Pi is ARM-based, so it should use [aarch64](https://en.wikipedia.org/wiki/AArch64) (name for 64-bit version of arm) package.

**Comment by gombosg** [comment]
Hm, interesting. In Fedora, 64-bit `aarch64` [builds just fine](https://koji.fedoraproject.org/koji/buildinfo?buildID=1618804), but I got the same error (see the bug link above) for 32-bit `armv7l`, which is some older ARM architecture.

@AriaMoradi is it possible that your OS is somehow 32 bit `armv7l` architecture? You can learn easily with `uname -m`.

**Comment by AriaMoradi** [comment]
> @gombosg
> Yes, Raspberry Pi is ARM-based, so it should use [aarch64](https://en.wikipedia.org/wiki/AArch64) (name for 64-bit version of arm) package.

confirmed. aarch64 == ARMv8-A which raspberry pi 3 and 4 are support.

**Comment by AriaMoradi** [comment]
> Hm, interesting. In Fedora, 64-bit `aarch64` [builds just fine](https://koji.fedoraproject.org/koji/buildinfo?buildID=1618804), but I got the same error (see the bug link above) for 32-bit `armv7l`, which is some older ARM architecture.
> 
> @AriaMoradi is it possible that your OS is somehow 32 bit `armv7l` architecture? You can learn easily with `uname`, can you paste `uname -a` output here?

Yes. Although we confirmed it's a aarch64, the kernel is 32bit(aarch32):
```bash
$ uname -a
Linux raspberrypi 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
```
Also Raspbian OS is only available in 32-bit. [link here](https://www.raspberrypi.org/downloads/raspberry-pi-os/)

**Comment by gombosg** [comment]
Thanks! So it _is_ the same `armv7hl` compilation issue after all!
@pktiuk any ideas why this happens only in this specific (32-bit) architecture? And as we see, it happens when compiling in Raspbian and also on Fedora, so it's probably not OS-specific.

Either it's because the architecture or because linking works differently with `ld`?
After some googling I found [this](https://pcem-emulator.co.uk/phpBB3/viewtopic.php?t=3443&p=13522). Looks like an `-fcommon` compilation flag could help. Or maybe some source change is needed?

I made a [Fedora scratch build](https://koji.fedoraproject.org/koji/taskinfo?taskID=55160266) (fails on `armv7hl`) so you can compare logs for various architectures.

**Comment by pktiuk** [comment]
> Also Raspbian OS is only available in 32-bit. official site

There is also [64bit version](https://www.raspberrypi.org/forums/viewtopic.php?p=1668160), but it is still in beta (publishing 8 GB version ob pi4 made it necessary), it is also compatible with pi3.  
If this is caused only by 32 bit architecture we should be able to run it on this beta version.

> After some googling I found this. Looks like an -fcommon compilation flag could help. Or maybe some source change is needed?

This change looks promising, we should check it.  I don't think we should change anything in source code (but I may be wrong).

**Comment by gombosg** [comment]
Let me do a test then with this. Is it `CMAKE_CXX_FLAGS` right?

**Comment by pktiuk** [comment]
Yes

**Comment by AriaMoradi** [comment]
looks like `-fcommon` is related to `C` code and not `C++`. It fixes linker errors which are related to forgetting `extern` when it needs to be there. But it sometimes works in `C++` that i can't find docs for.
Also I'm building with `gcc 8.3.0` and looks like it's a bug introduced when upgrading to `gcc 10`.
[source1](https://gcc.gnu.org/gcc-10/porting_to.html)
[source2](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html)

**Comment by gombosg** [comment]
Yes, `-fcommon` didn't solve it, I [got the same build error](https://koji.fedoraproject.org/koji/taskinfo?taskID=55173409).
We could try some `LFDLAGS` but I have no clue how they work. Also, keep in mind that only `armv7hl` architecture is failing, and only during the linking phase, so the failure is likely due to

- either 32/64 bit differences
- `ld` linker differences, like default flags or other settings.

I checked, in Fedora `LDFLAGS` are the same for `aarch64` and `armv7hl`.

**Comment by AriaMoradi** [comment]
> Yes, `-fcommon` didn't solve it, I [got the same build error](https://koji.fedoraproject.org/koji/taskinfo?taskID=55173409).
> We could try some `LFDLAGS` but I have no clue how they work. Also, keep in mind that only `armv7hl` architecture is failing, and only during the linking phase, so the failure is likely due to
> 
> * either 32/64 bit differences
> * `ld` linker differences, like default flags or other settings.
> 
> I checked, in Fedora `LDFLAGS` are the same for `aarch64` and `armv7hl`.

maybe finding the exact linker error could help? I suspect L6200E(edit5) is not what is happening?

**Comment by gombosg** [comment]
The error I got is the same that you described in the first post.

**Comment by gombosg** [comment]
After some googling/SO'ing around, I tried to fix this from the code side, despite having no clue about C++ :laughing: 
Basically the point is that template functions/classes are tricky in C++, and in this case, somehow the `.cpp` file was included from the `.h` file and not set to compile in the CMakeList. I fixed that. See also here: https://stackoverflow.com/a/115735

Can you try this fix on your Raspberry Pi? https://github.com/AntiMicroX/antimicrox/tree/fix/armv7hl

It builds for me: https://koji.fedoraproject.org/koji/taskinfo?taskID=55178896
