### ISSUE TITLE
Xbox Elite Controller 2 Core keys doesn't detect in AntiMicroX after some time

### ISSUE THREAD

**Issue by codewhizz** [AntiMicroX/antimicrox#810]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

All controller buttons except right and left trigger stops detecting in AntiMicroX after some time. Controller shows but buttons doesn't work. Restarting AntiMicroX doesn't do anything. Only when I restart the PC and start AntiMicroX, then only it detects all buttons again.

![image](https://github.com/AntiMicroX/antimicrox/assets/74320321/5fb593c7-5298-459e-835e-ad5b81744399)

### Expected Behavior

All controller buttons should work properly when using AntiMicroX for long intervals without any problem.

### Steps To Reproduce

1. Turn on PC
2. Connect Controller from bluetooth or wired.
3. Open AntiMicroX
4. Use your desired profile or it will autodetect last used.
5. After some time Controller advanced mappings doesn't work
6. When switched back to AntiMicroX app, AntiMicroX doesn't detect all buttons except right and left trigger.
7. Restart App (Still Same Issue)
8. Gamepad tester detects all keys correctly
9. Restart PC and go to step 2

### Environment

```markdown
Program Version 3.3.4
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.26.5
Running With SDL 2.26.5
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

### Anything else?

I'm using latest Xbox Elite Wireless Controller Series 2 Driver from Xbox Accessories App (Firmware version 5.17.3202.0)

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/810">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/810/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/810/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
1. Could you test it with another version of AntiMicroX (3.3.3)?
2. Could you also [collect some logs](https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs)?
3. > After some time Controller advanced mappings doesn't work

Does it mean, that simple mappings still work?

**Comment by TheoClarkeArt** [comment]
Same issue here. It _sometimes_ works fine, and other times fails to detect anything at all, or only detects the triggers for a few seconds then stops detecting even them. Tried various things to fix but no luck. Would love a solution!

**Comment by pktiuk** [comment]
@TheoClarkeArt  If tou want any solution answer my questions from above.

**Comment by TheoClarkeArt** [comment]
I've resolved it now by restarting my PC - I'll try to get some logs if it reoccurs. Not been able to test it on 3.3.3 because I can't find where to download it. But it also occurs on the final version of AntiMicro (2.24). Neither simple or advanced mapping work.

**Comment by codewhizz** [comment]
Here is the https://drive.google.com/file/d/1pDhf7HwFdE13aQCBEwWVFpvaJoGWGh-Z/view?usp=drive_link

> 1. Could you test it with another version of AntiMicroX (3.3.3)?

> 2. Could you also [collect some logs](https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs)?
> 3. > After some time Controller advanced mappings doesn't work
> 
> Does it mean, that simple mappings still work?

**Comment by codewhizz** [comment]
> 1. Could you test it with another version of AntiMicroX (3.3.3)?

Yes, problem still occurs.

> 2. Could you also [collect some logs](https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs)?

Here is the log data of past week taken in AntiMicroX 3.3.3 in debug mode.
https://drive.google.com/file/d/1pDhf7HwFdE13aQCBEwWVFpvaJoGWGh-Z/view?usp=drive_link


> 3. > After some time Controller advanced mappings doesn't work
> 
> Does it mean, that simple mappings still work?

Controller buttons doesn't detect in AntiMicroX. But controller buttons detect in other apps like gamepad tester.


And, I would like to add that during testing I also launched Xbox Accessories App's test mode. And I noticed the same problem as AntiMicroX, that buttons won't detect in even test mode of Xbox Accessories App. When we restart PC, everything is fine. But after some random time, buttons stop detecting. (in AntiMicroX and Xbox Accessories App, these 2 apps)

**Comment by pktiuk** [comment]
@codewhizz   

Have you reconnected your controller during session?

```
[17:50:05.379] 🟢INFO	Created new GameController:
			Index:            1
			  UniqueID:         030000005e040000220b00001705720011182850
			  GUID:             030000005e040000220b000017057200
			  VendorID:         1118
			  ProductID:        2850
			  Serial:           
			  Product Version:  1303
			  Name:             Xbox One Elite 2 Controller
[00:39:25.872] 🟢INFO	Created new GameController:
			Index:            1
			  UniqueID:         030000005e040000220b00001705720011182850
			  GUID:             030000005e040000220b000017057200
			  VendorID:         1118
			  ProductID:        2850
			  Serial:           
			  Product Version:  1303
			  Name:             Xbox One Elite 2 Controller
```

**Comment by codewhizz** [comment]
> Have you reconnected your controller during session?

Yes, I mostly use wirelessly from bluetooth and sometimes it turns off automatically when inactive. So I have to turn it on and reconnect to PC again.

**Comment by codewhizz** [comment]
Sometimes problem doesn't occur even after long time of usage and multiple reconnects. Sometimes problem occurs on direct restart and first connection (i think this happened but I'm not 100% sure).

**Comment by cappy1310** [comment]
Log of this issue happening for me:
[antimicrox_1.log](https://github.com/AntiMicroX/antimicrox/files/15124261/antimicrox_1.log)

I had this issue happen recently - only the triggers would function when AntiMicroX was open (3.4.0). Tried uninstalling/reinstalling 3.3.4 and the only thing that changed was that the triggers wouldn't work.

While I was debugging a separate issue, I tried disabling Steam Settings > Controller > "Enable Steam Input for Xbox controllers" and restarting my computer. That change actually fixed the issue for me.

When I first installed though, Steam Input was enabled; additionally, after the aforementioned fix, re-enabling Steam Input works fine. After several days with Steam Input enabled, issue hasn't returned. Additional log after the issue resolved (includes controller disconnect/reconnect):
[antimicrox_2.log](https://github.com/AntiMicroX/antimicrox/files/15144085/antimicrox_2.log)

**Comment by pktiuk** [comment]
@codewhizz    
Could you check this fix?

**Comment by codewhizz** [comment]
After few months of reporting this issue, my problem was automatically fixed and haven't faced this issue till date.

I remember, when I had this issue, my controller buttons were not detecting only on two apps - AntiMicroX and Xbox Accessories. Rest my controller buttons were detecting on https://hardwaretester.com/gamepad and games.

I always keep my pc up to date by installing windows updates. So I think it might be one of the bug from Microsoft, that they have fixed it now, ig.

**Comment by pktiuk** [comment]
I guess this was either fix in the driver or in the SDL.

Thank you @codewhizz for your report and answer.
