### ISSUE TITLE
Gamecube controller support with Mayflash adapter in wii u mode?

### ISSUE THREAD

**Issue by MrFreezerburnt** [AntiMicroX/antimicrox#813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I saw a different issue about the Mayflash adapter that was closed but this is not related to that issue. [Here ](https://www.mayflash.com/product/W012.html)is the mayflash in case you are unfamiliar.

The Mayflash adapter has two different "modes" you can toggle: PC mode and Wii U mode. I play Super Smash Brothers Melee on [Slippi](https://slippi.gg/), which runs on the Dolphin emulator that can read Gamecube Controller inputs in Wii U mode. AntiMicroX has no issue detecting a standard Gamecube controller while Mayflash is in PC mode since in that mode, it treats the Gamecube controller like a standard gamepad, however for the best game enjoyment playing with a gamecube controller while in wii u mode is required. Considering you have to download zadig to install the proper drivers to WUP-028 for Windows to even detect the controller in wii u mode in the first place maybe this is possible to detect for AMX as well. 

Below is the driver I install:
![image](https://github.com/AntiMicroX/antimicrox/assets/10689379/9faa6cc5-55b4-4abf-9b4a-5f618032273a)

### Describe the solution you'd like

I was hoping it would be possible for AMX to support gamecube controllers while using the Mayflash adapter in Wii U mode as opposed to PC mode; the former having native inputs and being a much better experience while the latter turns the controller into a sluggish, but operable, mess.

### Describe alternatives you've considered

There is a [program](https://github.com/Struggleton/Delfinovin) which can detect Gamecube controller inputs while using the Mayflash adapter in Wii U mode but it turns the gamecube controller into an XInput gamepad which is either the same or similar to PC mode.

**Comment by pktiuk** [comment]
Support for selected controllers is not implemented by AntiMicroX. It should be implemented in the SDL https://github.com/libsdl-org/SDL/
