### ISSUE TITLE
Seam Deck on Windows Controller Support?

### ISSUE THREAD

**Issue by rayman3003** [AntiMicroX/antimicrox#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

If we have support of Seam Deck Controller in AntiMicroX, It's gonna be awesome. (In windows)

![Windows-11-on-Steam-Deck-1](https://github.com/AntiMicroX/antimicrox/assets/17022701/3e61eee4-3d16-4fdc-9c25-27929732807b)

**Comment by pktiuk** [comment]
What is wrong with current support on the Steam Deck?    
Steam deck is just a Linux PC and AntiMicroX supports (primarly) Linux machines.

**Comment by rayman3003** [comment]
> What is wrong with current support on the Steam Deck?
> Steam deck is just a Linux PC and AntiMicroX supports (primarly) Linux machines.

No. I mean supporting the controllers of Steam Deck in Windows.

The windows version of AntiMicroX doean't support steam deck controllers. (It won't show it at all!)

**Comment by pktiuk** [comment]
If Windows does not support these controllers there is not much I can do about this.    
I use external Library SDL which provides a list of controllers to me if this library doesn't show this controller then AntiMicroX win't support it.

Anyway I don't know why do you want to use Steam Deck with Windows. It is much better experience on Linux, battery lasts longer performance is optimized, power limits work fine and GUI just works.

**Comment by rayman3003** [comment]
> You can open an issue in https://github.com/libsdl-org/SDL

Thank u. I will give it a shot 🤝

**Comment by rayman3003** [comment]
I found an issue about Steam Deck there.

Do u think that soon they are going to add Steam Deck controllers support to SDL?

https://github.com/libsdl-org/SDL/pull/8041

**Comment by pktiuk** [comment]
It is already added, I think it will be a part of the next SDL release.

**Comment by rayman3003** [comment]
> It is already added, I think it will be a part of the next SDL release.

Awesome. I will test it, & report back here, as soon as u add the next SDL release to the next AntiMicroX release.

**Comment by rayman3003** [comment]
New version of SDL released. But I don't see anything related to Steam Deck, in the changelog. What does it mean?

https://github.com/libsdl-org/SDL/releases/tag/release-2.28.2

**Comment by pktiuk** [comment]
I am not an SDL developer, you should ask in original issue.

**Comment by pktiuk** [comment]
I created a pre-release using the latest SDL2 (only AppImage and windows release is bundled with the latest SDL lib). You can test it. And let me know whether everything works now.
https://github.com/AntiMicroX/antimicrox/releases/tag/3.3.4-updated-SDL

**Comment by rayman3003** [comment]
> You can test it. And let me know whether everything works now.

Thank u. I tested it just now.

But no. The AntiMicroX still can't recognize the Steam Deck controller.

**Comment by pktiuk** [comment]
Then SDL developers haven't introduced support for steam deck yet.

**Comment by rayman3003** [comment]
> Then SDL developers haven't introduced support for steam deck yet.

Yeap. Must wait more. 😄
