### ISSUE TITLE
Run on (DE/WM) startup

### ISSUE THREAD

**Issue by AriaMoradi** [AntiMicroX/antimicrox#82]
**Is your feature request related to a problem? Please describe.**
I want to use antimicrox on my raspberry pi which is connected to the tv. it has a keyboard attached, but no mouse available around. I could use my PS3 controllers for this. It would be convenient that antimicrox would run on DE/WM startup pre-configured with a profile for my sixaxis in the tray. 

**Describe the solution you'd like**
Add an applet executable. so I could run in my xinitrc.

**Describe alternatives you've considered**
- A systemd service maybe?  so i could enable and disable when I want.
- there are some DE specific solutions too.

**Additional context**
blueman (blueman-manager) has an applet program(blueman-applet) that it runs when I open bluman-manager. I also could run blueman-applet directly to have access to bluetooth at all times.
networkmanager-applet is also an interface to interact with NetworkManager.

**Comment by gombosg** [comment]
Why is an 'applet' needed? I don't understand. You could just run `/usr/bin/antimicrox` from your xinitrc. GNOME has a startup apps tab in tweak tools, it can be added there too etc.

The only thing I can imagine is a "run on startup" setting in the preferences window.

**Comment by AriaMoradi** [comment]
right. I didn't pay attention to the tray. when i close the app well it closes, but when you click on the tray icon it goes away. also there is the settings' General options. consider this coming my ignorance.
