### ISSUE TITLE
CPU USAGE background service

### ISSUE THREAD

**Issue by Derillo** [AntiMicroX/antimicrox#825]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Hello 👋
In this attached image describes 5 processes that are constantly running in the background and I can't pinpoint the reason.
Antimicro running in the background performs some process that is constantly running.
Cases like Macro Button (VB-AUDIO) does not consume anything in the background and does the same job.
![imagen](https://github.com/AntiMicroX/antimicrox/assets/15325019/0d849fa9-fd97-45e6-8a7a-1f453b73cf92)

### Expected Behavior

Is it a performance problem? Can anyone identify why this is happening? Is it possible to correct it under so many windows library dependencies?
It's just a few questions

### Steps To Reproduce

1. Open Antimicro
2. Task Manager or Process Explorer (for wwww.sysinternals.com)
3. Search this process AntimicroX.exe 
4. See column CPU
5. Variation CPU use

![imagen](https://github.com/AntiMicroX/antimicrox/assets/15325019/e8b52c74-e852-4e08-8c65-ed090ecb1411)

### Environment

```markdown
Versión del programa 3.3.4
Compilado desde el empaquetado: GitHub Windows Release
Construído contra SDL 2.26.5
Ejecutándose con SDL 2.26.5
Usando Qt 5.15.2
Usando gestor de eventos: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment]
I don't understand your request.    
What's the problem? Why seeing multiple processes is a problem?

**Comment by Derillo** [comment]
First of all, I use the translator to write this thread.
The problem is, why does the background service use cpu without me using it? What is he doing while running in the background?
The average constant consumption is 2% of the cpu.
Can this be fixed from programming?

**Comment by pktiuk** [comment]
Every app running in background uses some cpu.   
If you don't want it just close the app.

**Comment by Derillo** [comment]
Hello @pktiuk  I hope you are well and thanks for answering.

1. Do not create this thread with the desire to generate a discussion or any member of the community.

2. Let me correct you. Your statement is not correct.
If each service will use 2% of the cpu (at least 30 running on any system) in idle any computer would use 60% of the cpu.
That is not right. Background services don't constantly run threads for nothing. Programmers seek efficiency.

3. It is true that it might not be an issue to consider improving for this open source software. What I don't think is correct is that you close a disinterested user report and you can't even answer my question.

Question: What piece of software constantly creates these threads? What is their function? Can it be improved?

greetings

**Comment by pktiuk** [comment]
> What piece of software constantly creates these threads?

Are these threads constantly created? How many threads per hour are created?

There are severeal threads used by antimicrox (number of these should not change over time).

As far as I recall there are (there may be some additional threads):

- main QT thread, the one which processes signals, interactions with GUI, etc
- Thread for capturing windows (auto profile functionality)
- Logging thread - it processes logs inside of the app
- SDL worker thread - this one processes events detected any SDL, filters them and in case 

Every of them has its own purpose.

> Background services don't constantly run threads for nothing. Programmers seek efficiency.

I think you can guess now which one is constantly performing actions in the background.

Looking for efficiency is not as straightforward as you may think. There is something called premature optimization.
![](https://miro.medium.com/v2/resize:fit:982/1*WZmVF9vJAyn8tO1g3lVa9w.png)
[pic source](https://medium.com/@bartoszkrajka/principle-of-software-development-principles-f0143d6f405)

I don't have time to properly refactor important code, so any optimizations are not in the scope of this project now.
