### ISSUE TITLE
I can't use AntiMicroX with screen reader software

### ISSUE THREAD

**Issue by SteveMurgaski** [AntiMicroX/antimicrox#831]
As a blind computer user, I need to use screen reader software to read the content of the screen aloud for me. The program I use is JAWS for Windows, but I believe that any of thescreen reader programs for Windows would have similar issues when trying to access AntiMicroX. The Windows screen reader programs all use keyboard commands to operate because mouses don't work well for those of us who can't see where the mouse pointer is.
AntiMicroX seems like it cold help me a lot. If I could assign keyboard commands I use regularly to buttons on a gaming controller, I could make much more intuitive interfaces for all sorts of software.
But, I need to type keyboard commands to do everything, so I can't use that method to select what key to associate with a button on a controller in the AntiMicroX interface. I need a way of using AntiMicroX that doesn't require a mouse at all.
What I was thinking was, if there were a way to import and export controller key associations in a spreadsheet format, I could edit them without having to use the AntiMicroX interface. (I believe the profiles can now be exported as xml, but that's much harder for me to edit manually.)
I'm attaching a very simple example of what I'm thinking, just in case it helps clarify what I mean. I realise the spreadsheet would need to be more complicated to capture all the options for things like joystick controls, but I'm hoping you can see how to make something roughly similar which humans could edit easily. Then the profiles could be imported without using a mouse, either by tabbing to a control within the program or by using a command line option when running it.
This sounds kind of like a request for a new feature, but from my perspective it's a request to make the program so that I can use it independently. If anyone has other ideas about how to accomplish setting controller associations without using a mouse I'd love to hear them.
[Sample controller key associations spreadsheet.xlsx](https://github.com/AntiMicroX/antimicrox/files/12540008/Sample.controller.key.associations.spreadsheet.xlsx)

**Comment by pktiuk** [comment]
Please use proper template.

**Comment by W9JYD** [comment]
> Please use proper template.

@pktiuk BRO. Dude is blind. You are going to close this issue because he can’t see the damn thing?

Ableist behavior. Pathetic.

**Comment by pktiuk** [comment]
@W9JYD  

> You are going to close this issue because he can’t see the damn thing?

No, I closed it, because everyone has to follow templates. All the issues not using them are instantly closed. In case of any problems with templates, he could just ping me.     
Don't be condescending. People with disabilities can talk for themselves.

**Comment by pktiuk** [comment]
Issue is a duplicate of https://github.com/AntiMicroX/antimicrox/issues/832
