### ISSUE TITLE
Mayflash Wii Classic Controller Adapter Buttons are off

### ISSUE THREAD

**Issue by DemonBigj781** [AntiMicroX/antimicrox#843]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

The left are right triggers are not detected
and the left and right bumpers are treated as triggers

### Expected Behavior

there are too many buttons that have been added or missing
the program should of had all of the working like in the old antimacro software

### Steps To Reproduce

plug it in.
press left and right trigger.
press left and right bumper

### Environment

```markdown
Program Version 3.3.4
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.26.5
Running With SDL 2.26.5
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

### Anything else?

2509e803000000000000504944564944,Mayflash Wii Classic Controller,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b8,start:b9,guide:b10,leftshoulder:b6,rightshoulder:b7,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,

this is the mapping it should have

**Comment by DemonBigj781** [comment]
I found the solution.

slap this in gamecontrollerdb.txt

2509e803000000000000504944564944,Mayflash Wii Classic Controller,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b8,start:b9,guide:b10,leftshoulder:b6,rightshoulder:b7,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,

**Comment by DemonBigj781** [comment]
I made the submission to https://github.com/gabomdq/SDL_GameControllerDB

**Comment by pktiuk** [comment]
Remind me when it will be merged. I will update database included into AntiMicroX

**Comment by DemonBigj781** [comment]
they said that was a duplicate entry in the db

**Comment by DemonBigj781** [comment]
the change happened last year
https://github.com/gabomdq/SDL_GameControllerDB/commit/57d4e60793a89560fd77c0524b71f9ebbef9a629

**Comment by pktiuk** [comment]
I mean when the fix will be merged

**Comment by DemonBigj781** [comment]
it is not being merged. they will not update it. it has been in the database for a year.
