### ISSUE TITLE
Xbox series x controller share button

### ISSUE THREAD

**Issue by Carlinho21** [AntiMicroX/antimicrox#845]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

The xbox series x controller share button doesnt seem to be recognised or im missing something. id like to use it to record clips.
Is this a bug or is it not supported?

### Expected Behavior

It does nothing

**Comment by inwardmovement** [comment]
Any news on this?

**Comment by realgooseman** [comment]
Hi @Carlinho21 & @inwardmovement 
Still not fixed in 2024, but there's a workaround that works (use Method 2) : https://github.com/AntiMicroX/antimicrox/discussions/797
