### ISSUE TITLE
Update SDL version and support newer SDL mapping features

### ISSUE THREAD

**Issue by offalynne** [AntiMicroX/antimicrox#860]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

SDL mapping produces invalid GUIDs (and thus invalid mappings), keys added to newer SDL (including touchpad, misc button, paddles) are missing and can not be mapped, CRC field is missing

### Expected Behavior

An up to date SDL version tested for proper interoperation with other software including Steam and myriad modern games

### Steps To Reproduce

Create a gamepad mapping,
observe format is out of date, mapping features are missing, and GUID is likely incorrect (compared to Steam and other apps using SDL)

### Environment

```markdown
Tested with Linux binary (issue is observable in any release/environment)
```

**Comment by pktiuk** [comment]
Closing due to lack of feedback
