### ISSUE TITLE
Migrate DEB packages to antimicrox

### ISSUE THREAD

**Issue by gombosg** [AntiMicroX/antimicrox#87]
The DEB package was [packaged last year](https://evolvis.org/plugins/scmgit/cgi-bin/gitweb.cgi?p=alioth/antimicro.git;a=shortlog;h=refs/heads/master). If possible, migrate users to `antimicrox` as that is the maintained version.

Goal:
- [x] contact [the Debian package maintainer](https://packages.debian.org/sid/antimicro), if possible continue an open discussion here
- [x] learn about DEB requirements

**Comment by gombosg** [comment]
I'm happy to start the conversation, @pktiuk do you have any specific inputs/suggestions before I contact the maintainer?

**Comment by pktiuk** [comment]
Just tell ask him whether does he use github.  
If yes, he could answer us here.

**Comment by gombosg** [comment]
We had an email conversation. The Debian packager will package antimicrox for Debian, replacing antimicro. For this we need config migration ASAP since Debian stable freeze is in about a month.

I'll look into confog migration this week, if the formats themselves are compatible it shouldn't be an issue.

**Comment by mirabilos** [comment]
I’ve begun packaging 3.1.3 and have a few comments already:

- `list(APPEND CMAKE_PREFIX_PATH "/usr/lib/arm-linux-gnueabihf")` is a complete no-go; the packager/builder should be expected to set this correctly. Doing that in the CMakeLists file will cause build errors if building for some platform while having the armhf variants installed.

- please add an option to not build a shared library (i.e. link the executable with the static library and not install the library); otherwise, I’d have to split the package _and_ you’d __have__ to commit to a stable ABI, which I’m sure you don’t want

- hardcoding `LD_LIBRARY_PATH` in the binary is, similarily, a no-go, but I assume that would be a nōn-issue if the shared library is disabled

- there’s a `CHANGELOG.md` and a `HISTORY.md`, can you decide on one of them? They both seem to be changelog-like files, not short NEWS-like ones.

- files have the Unix executable attribute that shouldn’t (such as LGPL licence files); has someone committed from Windows there? `;-)`

I’ll probably find more and report.

**Comment by mirabilos** [comment]
- [`qglobalshortcut`](https://github.com/mitei/qglobalshortcut) is not licenced (showstopper)

**Comment by AriaMoradi** [comment]
> * [`qglobalshortcut`](https://github.com/mitei/qglobalshortcut) is not licenced (showstopper)
> 
> Reported as: [mitei/qglobalshortcut#1](https://github.com/mitei/qglobalshortcut/issues/1)

The original dev doesn't have any activity record for the past 5 years, hope they are actually around.

**Comment by gombosg** [comment]
Thanks @mirabilos!

I created issues and a project to track progress: https://github.com/AntiMicroX/antimicrox/projects/1

@AntiMicroX/members feel free to take issues.
@AriaMoradi #99 becomes high priority. We have to fix the pipeline somehow.

**Comment by pktiuk** [comment]
@mirabilos  
Do I correctly assume we should also deal with all the problems reported by `lintian` for our package?  
Current status
```
E: antimicrox: no-copyright-file
W: antimicrox: desktop-mime-but-no-exec-code usr/share/applications/io.github.antimicrox.antimicrox.desktop
W: antimicrox: extended-description-line-too-long
W: antimicrox: non-standard-dir-perm usr/ 0775 != 0755
W: antimicrox: non-standard-dir-perm usr/bin/ 0775 != 0755
W: antimicrox: non-standard-dir-perm usr/include/ 0775 != 0755
W: antimicrox: non-standard-dir-perm ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: antimicrox: syntax-error-in-debian-changelog line 10 "badly formatted heading line"
W: antimicrox: syntax-error-in-debian-changelog line 102 "badly formatted heading line"
W: antimicrox: syntax-error-in-debian-changelog line 108 "badly formatted heading line"
W: antimicrox: syntax-error-in-debian-changelog ... use --no-tag-display-limit to see all (or pipe to a file/program)
W: antimicrox: wrong-name-for-changelog-of-native-package usr/share/doc/antimicrox/changelog.Debian.gz
```

(but there is already PR with some fixes for this https://github.com/AntiMicroX/antimicrox/pull/117)

**Comment by mirabilos** [comment]
Paweł Kotiuk dixit:

>Do I correctly assume we should also deal with all the problems
>reported by `lintian` for our package?

No, because I’m not going to use anything from your package.

>Current status

Looking at that it’d be harder to fix your package than to
make one anew, which I don’t even need because I already have
antimicro packaging that I can reuse.

In fact, it is preferred if upstreams don’t ship any packaging,
and Debian’s tooling will automatically remove a debian/ subdir
if it exists, as we ship our own packaging.

**Comment by gombosg** [comment]
@mirabilos I think we have fixed the issues you mentioned.
You can check the items at https://github.com/AntiMicroX/antimicrox/projects/1.

Please do a test build on master if possible, and if you find it acceptable we'll make a release for the final package.

**Comment by pktiuk** [comment]
@mirabilos   
Do you have any status updates for us?  
We are thinking about pushing a new release soon, is it okay with your packaging efforts?

**Comment by mirabilos** [comment]
Paweł Kotiuk dixit:

>@mirabilos   
>Do you have any status updates for us?  

Sorry, haven’t yet had any spare time.

>We are thinking about pushing a new release soon, is it okay with your
>packaging efforts?

Just do, I’ll update the packaging as needed.

In fact having things in releases helps.

bye,
//mirabilos
-- 
<igli> exceptions: a truly awful implementation of quite a nice idea.
<igli> just about the worst way you could do something like that, afaic.
<igli> it's like anti-design.  <mirabilos> that too… may I quote you on that?
<igli> sure, tho i doubt anyone will listen ;)

**Comment by mirabilos** [comment]
`CHANGELOG.md` is installed during build:

```
-- Installing: /tmp/buildd/antimicro-3.1.4/debian/antimicro/usr/share/doc/antimicrox/CHANGELOG.md
-- Installing: /tmp/buildd/antimicro-3.1.4/debian/antimicro/usr/share/antimicrox/CHANGELOG.md
```

Twice is bad, once would be better, but since I install it in the _correct_ Debian location using Debian mechanisms *anyway* it doesn’t need to be installed at all (not for Debian anyway), but I can just delete the file after `make install`.

**Comment by mirabilos** [comment]
The headers are also still installed; probably a remnant of the now-removed library. Since no library is installed, nothing can really make use of these headers, so they need not be installed.

**Comment by mirabilos** [comment]
Compiling goes well; there’s one file with warnings:

```
[ 98%] Building CXX object CMakeFiles/antimicrox.dir/src/eventhandlers/uinputeventhandler.cpp.o
/usr/bin/c++ -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DWITH_UINPUT -DWITH_X11 -DWITH_XTEST -I/tmp/buildd/antimicro-3.1.4/obj-x86_64-linux-gnu -I/tmp/buildd/antimicro-3.1.4 -I/tmp/buildd/antimicro-3.1.4/obj-x86_64-linux-gnu/src -I/tmp/buildd/antimicro-3.1.4/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -g -O2 -ffile-prefix-map=/tmp/buildd/antimicro-3.1.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-deprecated-declarations -Wno-deprecated-copy -Wdate-time -D_FORTIFY_SOURCE=2 -DANTIMICROX_PKG_VERSION=\"'3.1.4-1 (Debian sid/amd64)'\" -std=c++11 -fPIE -fPIC -o CMakeFiles/antimicrox.dir/src/eventhandlers/uinputeventhandler.cpp.o -c /tmp/buildd/antimicro-3.1.4/src/eventhandlers/uinputeventhandler.cpp
/tmp/buildd/antimicro-3.1.4/src/eventhandlers/uinputeventhandler.cpp: In member function ‘void UInputEventHandler::createUInputKeyboardDevice(int)’:
/tmp/buildd/antimicro-3.1.4/src/eventhandlers/uinputeventhandler.cpp:398:10: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  398 |     write(filehandle, &uidev, sizeof(uidev));
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/buildd/antimicro-3.1.4/src/eventhandlers/uinputeventhandler.cpp: In member function ‘void UInputEventHandler::createUInputMouseDevice(int)’:
/tmp/buildd/antimicro-3.1.4/src/eventhandlers/uinputeventhandler.cpp:414:10: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  414 |     write(filehandle, &uidev, sizeof(uidev));
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/buildd/antimicro-3.1.4/src/eventhandlers/uinputeventhandler.cpp: In member function ‘void UInputEventHandler::createUInputSpringMouseDevice(int)’:
/tmp/buildd/antimicro-3.1.4/src/eventhandlers/uinputeventhandler.cpp:438:10: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  438 |     write(filehandle, &uidev, sizeof(uidev));
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/buildd/antimicro-3.1.4/src/eventhandlers/uinputeventhandler.cpp: In member function ‘void UInputEventHandler::write_uinput_event(int, int, int, int, bool)’:
/tmp/buildd/antimicro-3.1.4/src/eventhandlers/uinputeventhandler.cpp:459:10: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  459 |     write(filehandle, &ev, sizeof(struct input_event));
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/buildd/antimicro-3.1.4/src/eventhandlers/uinputeventhandler.cpp:469:14: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  469 |         write(filehandle, &ev2, sizeof(struct input_event));
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

While these are very minor, you might want to fix them (e.g. by signalling an error if the write fails, or (if `errno == EINTR` or only a partial block was written) even repeating it.

**Comment by mirabilos** [comment]
I’ve pushed a couple **more** issues (_other_ than these I’ve mentioned here already) in #139, #140, #141, #142 and #143.

**Comment by mirabilos** [comment]
I’ve uploaded a package `antimicro (= 3.1.4-1)` containing AntiMicroX to Debian unstable; it should arrive there and be built for all architectures shortly.

As I do not have any usable joystick, **PLEASE TEST THIS** because I cannot do it beyond starting and testing some dialogues.

This **WILL** migrate to Debian testing, soon to be released as bullseye (11), in ten days, so please test **before** so, if anything should go wrong, we can block and fix it.

Once migrated, I can look at backporting the new version to Debian buster (10, current stable, soon to be oldstable). With this I can then also upload it to [my PPA](https://launchpad.net/~mirabilos/+archive/ubuntu/ppa) for *buntu bionic (18.04 LTS) and focal (20.04 LTS); other versions on request but nōn-LTS versions are best-effort and can only be used for a few months after release. The package should enter the _normal_ *buntu distribution (hirsute, 21.04) a short time after it enters Debian and therefore will also be available there.

In case anyone wants to look at my [packaging repository](https://evolvis.org/plugins/scmgit/cgi-bin/gitweb.cgi?p=alioth/antimicro.git;a=tree), feel free to.

I’d like to thank my employer [⮡ tarent](https://www.tarent.de/) @tarent for sponsoring work on packaging antimicro (a coworker explicitly requested it for a project) for Debian.

**Comment by pktiuk** [comment]
I have merged your changes, everything works properly with them.

**Comment by mirabilos** [comment]
Great, thanks.

Can you (or one of the devs anyway) please test the package as built in Debian, so we know that one’s also good?

**Comment by pktiuk** [comment]
I built it on fresh Debian 10 VM, but I was not able to run it.
For deb package built using cmake I get (this is the same problem I had in case of build for Raspberry Pi https://github.com/AntiMicroX/antimicrox/issues/121):   
```
apt-get install_manifest.txt ./antimicrox-3.1.4-x86_64.deb 
E: Invalid operation install_manifest.txt
```

In case of bare binaries I get:  
```
./bin/antimicrox 
No protocol specified
```

**Comment by mirabilos** [comment]
No, you really must test the binaries as built by Debian; they most likely require Debian unstable, or at least Debian testing (11).

You also did not build the Debian package. The Debian package is called `antimicro`, not `antimicrox`.

    wget https://deb.debian.org/debian/pool/main/a/antimicro/antimicro_3.1.4-1_amd64.deb
    apt-get install "$PWD/antimicro_3.1.4-1_amd64.deb"

… is a quick-and-dirty way to do that.

**Comment by pktiuk** [comment]
Everything works well with this package.

**Comment by mirabilos** [comment]
OK, good to know, thanks! Then I’ll let it migrate to bullseye, buster-backports, *buntu PPA, …

**Comment by pktiuk** [comment]
Thanks for your help with this packaging :D

**Comment by gombosg** [comment]
Thanks for the incredible work you've done here @mirabilos ! :))

**Comment by mirabilos** [comment]
Backports and PPAs are filled with packages ☺ so I consider this finished from my side. A user reported in #89 that the backported package works well on his Raspberry, too.

Take-aways for you are still:
- the things I already opened separate issues for
- `CHANGELOG.md` is installed during build, twice even, but it isn’t needed even once as it’s embedded
- the headers are installed but they are now useless
- some compiler warnings in `src/eventhandlers/uinputeventhandler.cpp`

**Comment by pktiuk** [comment]
I think it can be closed now.

**Comment by mirabilos** [comment]
From reading https://github.com/AntiMicroX/antimicrox/compare/3.1.4...3.1.5 I don’t think the `CHANGELOG.md` is needlessly installed, twice, issue is fixed.

```
-- Installing: /tmp/buildd/antimicro-3.1.4/debian/antimicro/usr/share/doc/antimicrox/CHANGELOG.md
-- Installing: /tmp/buildd/antimicro-3.1.4/debian/antimicro/usr/share/antimicrox/CHANGELOG.md
```

Both these files are (almost certainly) not needed because the file is *also* embedded into the binary as Qt resource, as far as I can tell.

The `-Wunused-result` warnings in `src/eventhandlers/uinputeventhandler.cpp` are probably also still there?

**Comment by pktiuk** [comment]
> From reading [3.1.4...3.1.5](https://github.com/AntiMicroX/antimicrox/compare/3.1.4...3.1.5) I don’t think the `CHANGELOG.md` is needlessly installed, twice, issue is fixed.
> 
> ```
> -- Installing: /tmp/buildd/antimicro-3.1.4/debian/antimicro/usr/share/doc/antimicrox/CHANGELOG.md
> -- Installing: /tmp/buildd/antimicro-3.1.4/debian/antimicro/usr/share/antimicrox/CHANGELOG.md
> ```
> 
> Both these files are (almost certainly) not needed because the file is _also_ embedded into the binary as Qt resource, as far as I can tell.

Yes, one is embedded into the binary, but I am not sure and I don't want to delete it without checking (these two files seem to be source of problems earlier https://github.com/AntiMicroX/antimicrox/commit/8b695c7701d78cc7b06d2359b95950862010c219  https://github.com/AntiMicroX/antimicrox/commit/8b695c7701d78cc7b06d2359b95950862010c219). - I will investigate it later as a part of https://github.com/AntiMicroX/antimicrox/issues/157

> The `-Wunused-result` warnings in `src/eventhandlers/uinputeventhandler.cpp` are probably also still there?

I don't get any warning for uinputeventhandler (but I get others like `-Wold-style-cast` or `-Wswitch`).  
Could you just paste this warning here?

**Comment by mirabilos** [comment]
Paweł Kotiuk dixit:

>Yes, one is embedded into the binary, but I am not sure and I don't
>want to delete it without checking (these two files seem to be source

OK… build without it and test it the dialogue is still correctly shown?

>- I will investigate it later as a part of
>https://github.com/AntiMicroX/antimicrox/issues/157

OK.

>> The `-Wunused-result` warnings in
>> `src/eventhandlers/uinputeventhandler.cpp` are probably also still
>> there?
>
>I don't get any warning for uinputeventhandler (but I get others like `-Wold-style-cast` or `-Wswitch`).  
>Could you just paste this warning here?

I did, see above.

Thanks,
//mirabilos
-- 
> emacs als auch vi zum Kotzen finde (joe rules) und pine für den einzig
> bedienbaren textmode-mailclient halte (und ich hab sie alle ausprobiert). ;)
Hallooooo, ich bin der Holger ("Hallo Holger!"), und ich bin ebenfalls
... pine-User, und das auch noch gewohnheitsmäßig ("Oooooooohhh").  [aus dasr]
