### ISSUE TITLE
I am having issues with key configuration while using the PXN V9 racing wheel

### ISSUE THREAD

**Issue by agnoisa** [AntiMicroX/antimicrox#878]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

When I press the accelerator or brake pedal once, the axis value changes from 0 to a negative value and reaches the end (Image attached). 

![2023-11-26 09_52_21-설정 축 4](https://github.com/AntiMicroX/antimicrox/assets/13349271/da69d353-51c6-4127-925e-370a8284fbb0)

![2023-11-26 09_54_06-설정 축 4](https://github.com/AntiMicroX/antimicrox/assets/13349271/febe3510-5ed8-4503-9671-326aa3d61aec)

However, the clutch pedal maintains a value of 0 even after being pressed. The problem is that the axis value for the accelerator and brake pedals changes to a negative value once pressed, whereas it should remain at 0 before being pressed. I'm not sure what the issue is, but I want to ensure that the axis value stays at 0 normally

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/878">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/878/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/878/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
Could you open `Options ->Properties` window and check whether values in this place are displayed correctly?

**Comment by agnoisa** [comment]
-----Original Message-----

**Comment by pktiuk** [comment]
Sorry, but I cannot see any images.
