### ISSUE TITLE
QT6 port patch

### ISSUE THREAD

**Issue by edpil02** [AntiMicroX/antimicrox#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Additional context

I did a basic port to qt6 from git  today. But since I'm not  a programmer and  even less in QT, I would like to know if someone could review my patch.
THANKS.
![Screenshot_20231127_195805](https://github.com/AntiMicroX/antimicrox/assets/43163048/de8cd719-2776-4bfc-a5b1-d930b596c312)
[Patch.zip](https://github.com/AntiMicroX/antimicrox/files/13479367/Patch.zip)

**Comment by pktiuk** [comment]
You should propose this patch via GitHub Pull Request.
I think you should watch this: https://www.youtube.com/watch?v=jRLGobWwA3Y

The purpose of issues is tracking things to do, bugs and proposed enhancements. And there is already one dedicated to upgrading QT to 6: #446
