### ISSUE TITLE
A couple of problems with AUR

### ISSUE THREAD

**Issue by AriaMoradi** [AntiMicroX/antimicrox#88]
1- The aur release [here](https://aur.archlinux.org/packages/antimicrox/) could be a binary release and [antimicrox-git](https://aur.archlinux.org/packages/antimicrox-git/) stay as a source build.
2- As we fixed ARM builds, it could be added to `arch` inside `PKGBUILD` (with the next release I assume)

**Comment by AriaMoradi** [comment]
As a part of CI we could build for Arch Linux, the aur package could pull the file and jsut install it.
Just mentioning it when the CI discussion is hot.

**Comment by pktiuk** [comment]
It is a good idea, but is it possible to build arch binaries on ubuntu?  
I am asking, because GitLab runners ubuntu is the [only one](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners) available Linux distro there.

**Comment by gombosg** [comment]
Of course you can build for any supported arch, but the builder VM's arch (i.e. it's build chain) needs to be the target arch. It is supported, but I guess not for free. Worth checking out: https://github.com/marketplace/actions/run-on-architecture

**Comment by AriaMoradi** [comment]
lets not confuse Arch Linux and arch(architecture) :D

**Comment by gombosg** [comment]
No problem, my comment above solves another issue here :laughing:

**Comment by OlegPopow** [comment]
> 1- The aur release [here](https://aur.archlinux.org/packages/antimicrox/) could be a binary release and [antimicrox-git](https://aur.archlinux.org/packages/antimicrox-git/) stay as a source build.
> 2- As we fixed ARM builds, it could be added to `arch` inside `PKGBUILD` (with the next release I assume)

You should report this to the AUR, not here. It is doubtful that they would look here often enough to notice such a suggestion.Moreover, according to AUR standards, such a package should be called antimicrox-bin. A package compiled from sources without suffix -bin should not work as you suggest.

**Comment by frealgagu** [comment]
yes, the AUR standards suggest to use the sources for build the package, if a package is built using an already compiled binary it should use -bin suffix to identify it. The idea with -git versions is to have a build with the last sources (even a non-release version) in order to have an early access to the last changes. 
I could add the arm support for arch, however I don't have how to test it, so any issue caused for using other arch need to be solved through comments in order to fix it without affect the x_64 arch.
 
Add me in comments as @frealgagu in order to have a trace and being able to follow the issues in github.

**Comment by pktiuk** [comment]
> 1- The aur release here could be a binary release and antimicrox-git stay as a source build.

I think this one is cleared now

> 2- As we fixed ARM builds, it could be added to arch inside PKGBUILD (with the next release I assume)

This is out of my scope.  
But I am not sure whether is it worth spending time (at least now) for preparing packages for arm.  
According to [flatpak download stats](https://klausenbusk.github.io/flathub-stats/#ref=io.github.antimicrox.antimicrox&interval=infinity&downloadType=installs%2Bupdates) popularity of arm is too small to invest time in them.  
But anyway this decision belongs to package maintainer, not me.
