### ISSUE TITLE
Creating armv7 CI builds for Rasbian/Raspberry OS

### ISSUE THREAD

**Issue by Flaming-crossbow** [AntiMicroX/antimicrox#89]
i tried installing antimicrox-3.1.3-amd64.deb

$ sudo apt-get install gdebi
$ wget https://github.com/AntiMicroX/antimicrox/releases/download/3.1.3/antimicrox-3.1.3-amd64.deb
$ sudo gdebi antimicrox-3.1.3-amd64.deb

Result:
Reading package lists... Done
Building dependency tree        
Reading state information... Done
This package is uninstallable
Wrong architecture 'amd64' -- Run dpkg --add-architecture to add it and update afterwards

Evidently i'm using the wrong package but i have no idea how to find or use the " right" package.
I went for this package because raspbian supposes to be a debian distro?

**Comment by gombosg** [comment]
Hm, probably we'll need to fix this build. In the meantime, can you build for yourself or try the flatpak?

**Comment by Flaming-crossbow** [comment]
> Hm, probably we'll need to fix this build. In the meantime, can you build for yourself or try the flatpak?

Are you sure the error is build related? didnt i just pick the wrong package for Raspberry OS? 

ill give the flat pack a go later.

**Comment by gombosg** [comment]
If it's 32 bit - we just fixed that in the last release, flatpak won't contain it and maybe neither DEB. @pktiuk any info on DEB `armv7hl` and `amd64` arches?

@Flaming-crossbow I suggest building for yourself if you want to get playing fast. It's easy, just follow the steps. :)

**Comment by pktiuk** [comment]
We could try to set up cross-compiler as a part of our CI.

**Comment by AriaMoradi** [comment]
> If it's 32 bit - we just fixed that in the last release, flatpak won't contain it and maybe neither DEB. @pktiuk any info on DEB `armv7hl` and `amd64` arches?

It's 32-bit.
> Are you sure the error is build related? didnt i just pick the wrong package for Raspberry OS? On second thoughs, isnt raspberry OS 32bit?
> ill give the flat pack a go later.

Raspberry pi OS is a 32-bit ARM OS and It won't run either amd64 or x86. In the meantime you could build it yourself.

**Comment by Flaming-crossbow** [comment]
Everybody thanks for the replies. You confirmed that there is no install for Raspberry OS at the moment. I will take a look at "building it" but i am not a coder so i doubt ill get it working. 
Is there a dedicated release for RPI on the planning?
Is there an AntiMicro (non-X) version for Raspberry OS?

**Comment by gombosg** [comment]
Once we get [this](https://github.com/AntiMicroX/antimicrox/issues/88#issuecomment-729252714) running, there should be a usable build.

**Comment by pktiuk** [comment]
> Of course you can build for any supported arch, but the builder VM's arch (i.e. its build chain) needs to be the target arch. It is supported, but maybe not for free. Worth checking out: https://github.com/marketplace/actions/run-on-architecture

Thank to this tool mentioned by @gombosg I could quickly prepare config building `.deb` package for raspberry pi.  
It will be ready soon.

**Comment by pktiuk** [comment]
I have run test build for `armv7`

https://github.com/pktiuk/antimicrox/actions/runs/370820155

Could anyone test it on raspberry pi? (I can't use my, because I have just burned it) :fire:

**Comment by Flaming-crossbow** [comment]
> I have run test build for `armv7` and uploaded binaries here:
> 
> https://github.com/pktiuk/antimicrox/actions/runs/370820155
> 
> Could anyone test it on raspberry pi? (I can't use my, because I have just burned it) 🔥

I will try it today. Can't get to it immediately.

**Comment by Flaming-crossbow** [comment]
> I have run test build for `armv7` and uploaded binaries here:
> 
> https://github.com/pktiuk/antimicrox/actions/runs/370820155
> 
> Could anyone test it on raspberry pi? (I can't use my, because I have just burned it)

I got this error:

root@raspberrypi:/home/pi/Downloads# sudo gdebi antimicrox-3.1.3-amd64.deb
Reading package lists... 0%
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

AntiMicroX is a graphical program used to map gamepad buttons to keyboard, mouse, scripts and macros.
Do you want to install the software package? [y/N]:/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
root@raspberrypi:/home/pi/Downloads# y
-bash: y: command not found
root@raspberrypi:/home/pi/Downloads# sudo gdebi antimicrox-3.1.3-amd64.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

AntiMicroX is a graphical program used to map gamepad buttons to keyboard, mouse, scripts and macros.
Do you want to install the software package? [y/N]:y
/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()
dpkg: error processing archive antimicrox-3.1.3-amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 10:
 field name 'It' must be followed by colon
Errors were encountered while processing:
 antimicrox-3.1.3-amd64.deb
root@raspberrypi:/home/pi/Downloads#

**Comment by AriaMoradi** [comment]
@Flaming-crossbow try installing it with apt
```
# apt install ./antimicrox-3.1.3-amd64.deb
```

**Comment by Flaming-crossbow** [comment]
Go the following error: (think its the same)

root@raspberrypi:/home/pi/Downloads# apt install ./antimicrox-3.1.3-amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'antimicrox' instead of './antimicrox-3.1.3-amd64.deb'
The following packages were automatically installed and are no longer required:
  alsa-base gstreamer0.10-alsa gstreamer0.10-plugins-base libgstreamer-plugins-base0.10-0 libgstreamer0.10-0 libva-drm2 libva-wayland2 libva-x11-2 libva2 libvdpau-va-gl1 libvdpau1 libxfce4util-bin libxfce4util-common
  libxfce4util7 libxfconf-0-2 mesa-va-drivers mesa-vdpau-drivers pimixer point-rpi va-driver-all vdpau-driver-all xfconf
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  antimicrox
0 upgraded, 1 newly installed, 0 to remove and 307 not upgraded.
32 not fully installed or removed.
Need to get 0 B/1,974 kB of archives.
After this operation, 10.1 MB of additional disk space will be used.
Get:1 /home/pi/Downloads/antimicrox-3.1.3-amd64.deb antimicrox armhf 3.1.3 [1,974 kB]
dpkg: error processing archive /home/pi/Downloads/antimicrox-3.1.3-amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 10:
 field name 'It' must be followed by colon
Errors were encountered while processing:
 /home/pi/Downloads/antimicrox-3.1.3-amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by pktiuk** [comment]
@Flaming-crossbow 
According to [this](https://askubuntu.com/questions/157838/why-does-dpkg-give-me-this-parsing-error/528402) topic you could try this command

`sudo dpkg --clear-avail`  
but according to other sources also this could help:  
`sudo dpkg --configure -a`

**Comment by Flaming-crossbow** [comment]
> I have run test build for `armv7` and uploaded binaries here:
> 
> https://github.com/pktiuk/antimicrox/actions/runs/370820155
> 
> Could anyone test it on raspberry pi? (I can't use my, because I have just burned it)

I did a fresh clean rasberry os install and tried it again and got this error:

dpkg: error processing archive /home/pi/Downloads/antimicrox-3.1.3-amd64.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 10:
 field name 'It' must be followed by colon
Errors were encountered while processing:
 /home/pi/Downloads/antimicrox-3.1.3-amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Is there anything else i can try? Is this error caused by the .deb or by my system?

**Comment by pktiuk** [comment]
After reinstalling os we can be certain, it is problem with `deb` package.

Thanks for your help.

**Comment by mirabilos** [comment]
Considering Raspbian has bullseye, I wouldn’t be surprised if the proper Debian package shows up in http://archive.raspbian.org/raspbian/pool/main/a/antimicro/ soon (i.e. once it migrates to Debian bullseye, that is, in 10 days today).

Telling users to use the proper distro package would most likely fix this and #121 both.

**Comment by ibanman555** [comment]
So is there a way to install this on RPi4? I would love to try it, bit I'm having trouble following how to do it. Is there a step by step for a noob?

**Comment by mirabilos** [comment]
ibanman555 dixit:

>So is there a way to install this on RPi4? I would love to try it, bit
>I'm having trouble following how to do it. Is there a step by step for
>a noob?

Depends on your distribution. The package is currently only built
for Debian unstable; this is installable on Raspbian bullseye. I
even asked, specifically to be able to help users like you, the
Raspbian people about installing Debian packages and they told me
that it (usually) works if the CPU is ARMv7, that is, RPi2 or newer.

	wget https://deb.debian.org/debian/pool/main/a/antimicro/antimicro_3.1.4-1_armhf.deb
	sudo apt install "$PWD/antimicro_3.1.4-1_armhf.deb"

If you have buster you’ll need to wait until this hits buster-backports.
It’s not currently elegible for that, it must migrate to testing
(bullseye) first, which is expected to happen… *checks* in 8 days.
Then I need to upload the backport I already prepared, it needs to
be (manually, the first time) accepted, the autobuilders will compile
it, and then I can publish information (basically the same, except
that the path (filename) will differ).

I already received feedback that the package works, so it now is a
matter of, only, time.

bye,
//mirabilos
-- 
<igli> exceptions: a truly awful implementation of quite a nice idea.
<igli> just about the worst way you could do something like that, afaic.
<igli> it's like anti-design.  <mirabilos> that too… may I quote you on that?
<igli> sure, tho i doubt anyone will listen ;)

**Comment by ibanman555** [comment]
I have the most recent Raspberry Pi OS installed, 32 bit I believe.  It is RPi4 ARMv7. This is the result, maybe because of some residual problems I had before, maybe you can help me solve it?

```pi@raspberrypi:~ $ wget https://deb.debian.org/debian/pool/main/a/antimicro/antimicro_3.1.4-1_armhf.deb
--2021-02-02 17:22:26--  https://deb.debian.org/debian/pool/main/a/antimicro/antimicro_3.1.4-1_armhf.deb
Resolving deb.debian.org (deb.debian.org)... 199.232.162.132, 2a04:4e42:68::644
Connecting to deb.debian.org (deb.debian.org)|199.232.162.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 972472 (950K) [application/x-debian-package]
Saving to: ‘antimicro_3.1.4-1_armhf.deb’

antimicro_3.1.4-1_a 100%[===================>] 949.68K  --.-KB/s    in 0.1s    

2021-02-02 17:22:27 (7.16 MB/s) - ‘antimicro_3.1.4-1_armhf.deb’ saved [972472/972472]

pi@raspberrypi:~ $ sudo apt install "$PWD/antimicro_3.1.4-1_armhf.deb"
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'antimicro' instead of '/home/pi/antimicro_3.1.4-1_armhf.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 antimicro : Depends: libc6 (>= 2.29) but 2.28-10+rpi1 is to be installed
             Depends: libgcc-s1 (>= 3.5) but it is not installable
             Depends: libqt5core5a (>= 5.15.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
             Depends: libqt5widgets5 (>= 5.15.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
             Depends: libsdl2-2.0-0 (>= 2.0.12) but 2.0.9+dfsg1-1+rpt1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by mirabilos** [comment]
ibanman555 dixit:

>I have the most recent Raspberry Pi OS installed, 32 bit I believe.  It

Raspbian is only available in a 32-bit version, which is a problem
for various reasons, but not important here.

>The following packages have unmet dependencies:
> antimicro : Depends: libc6 (>= 2.29) but 2.28-10+rpi1 is to be installed

You have installed Raspbian buster, not bullseye, so you’ll
have to wait for the package to end up in buster-backports.

“bullseye” is not yet released, it will become stable in
about two months (which is probably why you don’t have it).

bye,
//mirabilos
-- 
22:59⎜<Vutral> glaub ich termkit is kompliziert | glabe nicht das man
damit schneller arbeitet | reizüberflutung │ wie windows │ alles evil
zuviel bilder │ wie ein spiel | 23:00⎜<Vutral> die meisten raffen auch
nicht mehr von windows | 23:01⎜<Vutral> bilderbücher sind ja auch nich
wirklich verbreitet als erwachsenen literatur	‣ who needs GUIs thus?

**Comment by ibanman555** [comment]
Cool, will wait and try again.

**Comment by mirabilos** [comment]
Hi ibanman555,

[…]
> antimicro : Depends: libc6 (>= 2.29) but 2.28-10+rpi1 is to be installed
[…]

Please try with the backports package:
https://deb.debian.org/debian/pool/main/a/antimicro/antimicro_2.23-2~bpo10+1_armhf.deb

Good luck,
//mirabilos
-- 
Support mksh as /bin/sh and RoQA dash NOW!
‣ src:bash (395 (421) bugs: 0 RC, 269 (288) I&N, 126 (133) M&W, 0 F&P)
‣ src:dash (89 (104) bugs: 0 RC, 48 (52) I&N, 41 (52) M&W, 0 F&P)
‣ src:mksh (1 bug: 0 RC, 0 I&N, 1 M&W, 0 F&P)
dash has two RC bugs they just closed because they don’t care about quality…

**Comment by ibanman555** [comment]
Yes! Excellent! Install went perfect and works great so far! Thank you!

**Comment by mirabilos** [comment]
ibanman555 dixit:

>Yes! Excellent! Install went perfect and works great so far! Thank you!

OK, wonderful.

For “regular” Debian users, after enabling backports (if not yet done),

	sudo apt-get -t buster-backports install antimicro

will do the trick. I’m considering the “package AntiMicroX” task, with
this, finished.

**Comment by Crilum** [comment]
If anyone is interested, for Raspberry Pi, AntiMicroX 3.2.0 is available from [Pi-Apps](https://github.com/Botspot/pi-apps), or you can install these debs: for [armhf](https://github.com/Pi-Apps-Coders/files/blob/main/antimicrox_3.2.0_armhf.deb?raw=true), or [arm64](https://github.com/Pi-Apps-Coders/files/blob/main/antimicrox_3.2.0_arm64.deb?raw=true).
