### ISSUE TITLE
disable stick setting

### ISSUE THREAD

**Issue by ps3120** [AntiMicroX/antimicrox#894]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

can you add a function to disable these settings, it ruins my sensitivity on games

![image](https://github.com/AntiMicroX/antimicrox/assets/32280131/40f6eb01-4daa-457b-98a4-c3bc8d97eaa9)
 

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/894">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/894/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/894/pledge.svg">
</picture>
</a>

**Comment by MrChillings** [comment]
can you explain your issue. its not clear.

**Comment by ps3120** [comment]
you can add a function to disable stick setting

**Comment by pktiuk** [comment]
> ruins my sensitivity on games

How it ruins your sensitivity?

I still don't understand. What do you mean by disabling stick setting?

**Comment by pktiuk** [comment]
Closing due to lack of feedback
