### ISSUE TITLE
Flatpak packaging

### ISSUE THREAD

**Issue by gombosg** [AntiMicroX/antimicrox#9]
- [x] [Review](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) the AppStream metadata files, revise screenshots if needed.
- [x] Create and test a flatpak.
- [ ] [Submit to Flathub](https://github.com/flathub/flathub/wiki/App-Submission) if possible. https://github.com/flathub/flathub/pull/1828
- [ ] If beneficial, [create a Flatpak](https://docs.fedoraproject.org/en-US/flatpak/tutorial/) from the Fedora RPM, submit to Fedora

**Comment by gombosg** [comment]
@pktiuk 
The flatpak functionally works fine, only the icons are missing in the app. Where are those pulled from?
See https://github.com/AntiMicroX/antimicroX/tree/flatpak
![image](https://user-images.githubusercontent.com/23086060/91821223-bb1f4800-ec36-11ea-8714-8622bd774a51.png)

**Comment by pktiuk** [comment]
You can find them here:
`src/icons/icons/16x16/actions/16-actions-edit_clear_list.png`

**Comment by gombosg** [comment]
LOL, icons just loaded after a restart. :man_shrugging:

**Comment by gombosg** [comment]
@pktiuk 
I figured out, but not the root cause.
If I touch anything in that icons folder, like create a file, the icons would load from then on. WTF?!

**Comment by pktiuk** [comment]
I don't have this issue with icons (I don't have any gamepads with me now, so I checked these icons)
![image](https://user-images.githubusercontent.com/45544416/92032147-01c18f00-ed6a-11ea-9585-e98404c9f14c.png)
![image](https://user-images.githubusercontent.com/45544416/92032286-36cde180-ed6a-11ea-896b-110d4b1d38c9.png)

**Comment by gombosg** [comment]
I found out, what you tested already contained the fix. :)
Flatpak sets every file to 0 (1/1/1970) timestamp. The icon cache file contains wrong values. I added a postinstall command to update the icon cache. There is a #flatpak channel on IRC, folks are helpful there! :)

**Comment by gombosg** [comment]
[Pull](https://github.com/flathub/flathub/pull/1828)

After merging, I'll delete the manifest in this repo, it will be maintained over in Flathub.

**Comment by gombosg** [comment]
Gotta fix that build, the icon definition is missing from the appstream XML file. :smirk:

**Comment by gombosg** [comment]
Build fixed, so Flathub people can continue the review.

**Comment by pktiuk** [comment]
What is the purpose of: https://github.com/flathub/io.github.antimicrox.antimicrox ?
Is it just a simple repository used for maintaining flatpak (do we have to update it after every release?)

**Comment by gombosg** [comment]
Yes, the Flathub app is generated from there, we have to update with tag & commit ID with every release. Good reminder to delete the manifest here.
