### ISSUE TITLE
None of my setting save when i exit the program

### ISSUE THREAD

**Issue by Geensy** [AntiMicroX/antimicrox#901]
I am just setting up the program. i have got it working to do what i want as a hot key, but mothing saves when i close the program. i have a profile saved, with my button mapping but i have to manually open it every time.
i tried the tick the auto load box but it was already ticked. i tried to untick it, close the program and reopen to turn it on again to see if that worked but nothing it just loaded up again with it ticked.
its like every time i open the program its like its been opened for the first time.

**Comment by pktiuk** [comment]
Use proper template

**Comment by Geensy** [comment]
Ohhhhh ok. I only first ever signed In to git hub to make this comment. Sorry I didn’t know RegardsAlex VangeenOn 5 Jan 2024, at 2:01 pm, Paweł Kotiuk ***@***.***> wrote:﻿
When you create an issue you should use a proper bug template (in this case BUG Report) instead of creating blank issue missing a lot of details.
image.png (view on web)
