### ISSUE TITLE
AntiMicroX doesn't remember which profile is assigned to which controller after it's been closed

### ISSUE THREAD

**Issue by ZombieGraves** [AntiMicroX/antimicrox#904]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Controllers do not retain the last assigned .gamecontroller profile between app reboots

### Steps To Reproduce

1. Plug in two or more controllers (currently I've got 4)
2. Create mappings for two controllers and save them to .gamecontroller files. I named mine P1 Controller and P2 Controller. 
3. Assign them to their respective controllers using the drop down. 
![image](https://github.com/AntiMicroX/antimicrox/assets/149631854/0be840d5-3960-4379-8490-f41bd07d2c4d)
4. Close and reopen AntiMicroX using the quit menu item.
5. One of the controllers has inherited the other's profile. This means that both now have the same profile, rather than distinct profiles as I last left it. 

### Environment

```markdown
Program Version 3.3.4
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.26.5
Running With SDL 2.26.5
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

### Anything else?

I've got an ultimarc ipac ultimate I/O board (https://www.ultimarc.com/control-interfaces/i-pacs/i-pac-ultimate-i-o/), which creates two distinct dinput controllers through one usb. This may be the root of the problem, since it may think that both controllers are actually the same controller, despite it creating two separate entries in the UI.

**Comment by pktiuk** [comment]
Cloud you [collect some logs](https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs) ?

Maybe there was problem with saved path or with access to that file...

**Comment by pktiuk** [comment]
Closing issue due to lack of feedback.
