### ISSUE TITLE
App doesn't open after minimizing it

### ISSUE THREAD

**Issue by redromnon** [AntiMicroX/antimicrox#91]
**Description**

I don't know whether it's programmed this way or not.
After hitting the minimize button, the app is not shown on the dock but the tray icon gets displayed implying that the app is running in the background. 
The issue is when I try to reopen the app from the applications menu or even the terminal, it fails to open.
I have to manually hit the "Quit" button from the tray icon and then run the app to work again.

**To Reproduce**
1. Open Antimicrox
2. Click the minimize button
(Fails to display the app icon on the dock or bar)
3. Open the app again through the application menu or terminal.

**Configuration**

Version of antimicrox: 3.1.3  
Used package: .deb 
System version: Pop OS 20.10

**Comment by gombosg** [comment]
Hm I can't repro, for me a 2nd instance shows up on Fedora 33. @pktiuk can you repro?

BTW there's a setting "minimize to taskbar" in the settings window if you want that.

**Comment by pktiuk** [comment]
I have reproduced it.

```
antimicrox --log-level debug
Debug: Socket connected 
 ((null):0, (null))
Debug:  Application theme has icon named:  "antimicrox"   false ((null):0, (null))
Debug: Stopped timer for appWatcher ((null):0, (null))
Warning: QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState ((null):0, (null))
Debug: removing main window ((null):0, (null))
Naruszenie ochrony pamięci (zrzut pamięci)
```

We will have to add some way of reopening window of already running instance in case of discovering it.

**Comment by redromnon** [comment]
> Hm I can't repro, for me a 2nd instance shows up on Fedora 33. @pktiuk can you repro?
> 
> BTW there's a setting "minimize to taskbar" in the settings window if you want that.

Thanks for letting me know! Works fine now!
Maybe you can mark "minimize to taskbar" as a default option so that first-time users like me don't come across this issue.

**Comment by redromnon** [comment]
> I have reproduced it.
> 
> ```
> antimicrox --log-level debug
> Debug: Socket connected 
>  ((null):0, (null))
> Debug:  Application theme has icon named:  "antimicrox"   false ((null):0, (null))
> Debug: Stopped timer for appWatcher ((null):0, (null))
> Warning: QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState ((null):0, (null))
> Debug: removing main window ((null):0, (null))
> Naruszenie ochrony pamięci (zrzut pamięci)
> ```
> 
> We will have to add some way of reopening window of already running instance in case of discovering it.

Yeah...
