### ISSUE TITLE
Valorant Not Working

### ISSUE THREAD

**Issue by Dragon81001x** [AntiMicroX/antimicrox#913]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

The problem is that, when I don't have Valorant open, the mouse controls work perfectly and I can move the cursor. Once Valorant opens, the cursor will just stop working, but all the other controls like, W, A, S, and D, and all the keyboard controls work fine in game. I am also not sure if it happens on different games or only in Valorant.

### Expected Behavior

I was expecting the cursor to move and for me to be able to play Valorant.

### Environment

```markdown
Program Version 3.3.4
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.26.5
Running With SDL 2.26.5
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment]
Duplicate: https://github.com/AntiMicroX/antimicrox/issues/406
>  I searched the existing issues and did not find anything similar

You clearly haven't searched
