### ISSUE TITLE
Apex Isnt Working

### ISSUE THREAD

**Issue by sophisticttv** [AntiMicroX/antimicrox#914]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

I have my Anti Micro setup in apex  so that I can Neo and tap strafe. All that is is turboed input of the wasd and in game momentum. How this looks is my Set 1 is : Left shoulder is turbo jump/SET 2 (While Held) and set 2: is an 8 way Joystick that is mapped to wasd ,aw, wd etc and on full turbo. The turbo-ing of the buttons on the joystick are not functioning, they are correctly bound to wasd but they do not rapidly input.

### Expected Behavior

I expected turbo input of the wasd keys on the joystick of my controller and they are not

### Environment

```markdown
Program Version 3.3.4
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.26.5
Running With SDL 2.26.5
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/914">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/914/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/914/pledge.svg">
</picture>
</a>

**Comment by sophisticttv** [comment]
This was all working properly today and the app has stayed closed and running. i have reinstalled and redone my bindings but it will not work

**Comment by pktiuk** [comment]
I guess this may be similar case to Valorant. https://github.com/AntiMicroX/antimicrox/issues/406

It is possible that this issue could be fixed with: https://github.com/AntiMicroX/antimicrox/issues/232

**Comment by mihawk90** [comment]
This was an intentional change by Respawn:

https://twitter.com/Respawn/status/1752851828130341315

Basically when the game detects a change in input (i.e. from detecting your analogue sticks moving to keyboard inputs), it disables lurch mechanics for roughly half a second which kills tap strafing:

https://twitter.com/MagicStrafes/status/1752826430243700804
