### ISSUE TITLE
Purple JoyCon not functioning

### ISSUE THREAD

**Issue by buttonmash147** [AntiMicroX/antimicrox#916]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

I have a pair of Neon Purple (L) / Neon Orange (R) JoyCons. I can only connect the purple on to my computer, and AntiMicroX detects the JoyCon is connected but does not receive the input from it. Running as Admin does not affect the issue.

### Expected Behavior

The input having an effect.

### Steps To Reproduce

1. Connect Purple JoyCon via Bluetooth
2. Open the Tab named "JoyCon (L) (Game Controller _X_ )

### Environment

```markdown
Program Version 3.3.4
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.26.5
Running With SDL 2.26.5
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/916">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/916/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/916/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
Cloud you [collect some logs](https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs)

Connect this JoyCon and press some buttone.

**Comment by pktiuk** [comment]
Closing due to lack of feedback
