### ISSUE TITLE
Thrustmaster t.16000m seen as Gamepad not a Joystick

### ISSUE THREAD

**Issue by Drugut** [AntiMicroX/antimicrox#941]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Joystick seen as a gamepad. Because of it some buttons are missing and some buttons accepted as gamepad sticks.

### Expected Behavior

Logitech Extreme 3d pro works perfectly with the program. T.16000m should work like it with extra 5 buttons.

### Steps To Reproduce

When program recognize the joystick.

### Anything else?

https://ibb.co/K0R8Wkn
Here is a screenshot of the problem

**Comment by pktiuk** [comment]
No info about enviroonment
