### ISSUE TITLE
"Stuck" Key

### ISSUE THREAD

**Issue by CHA0S-KING** [AntiMicroX/antimicrox#947]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Key remains "stuck" or shows as pressed down/highlighted when tapping it. I am forced to reset everytime I

### Expected Behavior

Should perform "go back function" and allow continued functions of other keys

### Steps To Reproduce

L bumper on 8BitDo Zero 2 remote for "Ctrl + Z"

### Anything else?

![20240409_085022](https://github.com/AntiMicroX/antimicrox/assets/159644053/03766200-f6d2-4db1-aff3-ed2943dcca5f)

**Comment by pktiuk** [comment]
```
Copy and paste text from Info window (Help->About->Info)
❗Without this information issue will be instantly closed.❗
```
