### ISSUE TITLE
Wii Nunchuck isn't recognized

### ISSUE THREAD

**Issue by mak448a** [AntiMicroX/antimicrox#968]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Clicking the axes on the joystick doesn't register in the remapping menu.

### Expected Behavior

It registers, just like the normal buttons on the wiimote.

### Steps To Reproduce

Connect a wiimote, open antimicrox, and try to remap.

### Environment

```markdown
Program Version 3.4.0
Compiled from packaging: 3.4.0-x86_64 (AppImage)
Built Against SDL 2.30.1
Running With SDL 2.30.1
Using Qt 5.12.8
Using Event Handler: uinput
Compositor type: wayland
Host OS: fedora Version: 40 Architecture: x86_64
```

**Comment by pktiuk** [comment]
This issue may be linked with: https://github.com/AntiMicroX/antimicrox/issues/199

If a Nunchuck is not recognized, then it is problem with SDL2.
