### ISSUE TITLE
Wiimote IR isn't detected

### ISSUE THREAD

**Issue by mak448a** [AntiMicroX/antimicrox#969]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Using the wii ir doesn't work with auto detection or anything else.

### Environment

```markdown
Program Version 3.4.0
Compiled from packaging: 3.4.0-x86_64 (AppImage)
Built Against SDL 2.30.1
Running With SDL 2.30.1
Using Qt 5.12.8
Using Event Handler: uinput
Compositor type: wayland
Host OS: fedora Version: 40 Architecture: x86_64
```

**Comment by mak448a** [comment]
The label used by joystick test websites says "Wii Remote IR," so that's what I wrote.

**Comment by pktiuk** [comment]
I don't think there is any chance of implementation for this input.
