### ISSUE TITLE
Flatpak update issue with Antimicrox

### ISSUE THREAD

**Issue by Miccio-AN** [AntiMicroX/antimicrox#971]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

During flatpak update:

Info: runtime org.kde.Platform branch 5.15-22.08 is end-of-life, with reason:
   We strongly recommend moving to the latest Qt 5.15-based stable version of the Platform and SDK
Info: applications using this runtime:
   io.github.antimicrox.antimicrox

### Expected Behavior

Smooth update process

### Steps To Reproduce

Install Flatpak
Install Antimicrox using Flatpak
Update flatpak

### Environment

```markdown
Program Version 3.4.0
Compiled from packaging: flatpak
Built Against SDL 2.24.0
Running With SDL 2.24.0
Using Qt 5.15.10
Using Event Handler: XTest
Compositor type: x11
Host OS: org.kde.Platform Version: 5.15-22.08 Architecture: x86_64
```

**Comment by pktiuk** [comment]
Thank you for the report. I will look at this.

**Comment by pktiuk** [comment]
I will update this runtime again after finishing: #446
