### ISSUE TITLE
Wiki "Adding A New Game Controller Mapping under AntiMicroX": don't work url to libsdl-org/SDL

### ISSUE THREAD

**Issue by vladiscripts** [AntiMicroX/antimicrox#983]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

On the page https://github.com/AntiMicroX/antimicrox//wiki/Adding-A-New-Game-Controller-Mapping-under-AntiMicroX  does not work the url http://hg.libsdl.org/SDL/file/tip/src/joystick/SDL_gamecontrollerdb.h.

I found on hg.libsdl.org/SDL a mention of "joystick" and "gamepad" on the page [Migrating to SDL 3.0](https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md). It says something about renaming variables and formats, perhaps this is important for your project. I don't know English well. Hope this helps.

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/983">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/983/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/983/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
Thank you for report, I updated links in the wiki
