### ISSUE TITLE
Add commandline to close the program

### ISSUE THREAD

**Issue by MaLDox77** [AntiMicroX/antimicrox#994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The problem is that there is no way to elegantly quit the program without interacting with the tray icon or the application window.

### Describe the solution you'd like

To add a new commandline parameter that sends the quit instruction to the program so could be possible to close Antimicrox from a script.

**Comment by pktiuk** [comment]
There is already a command called kill.

**Comment by MaLDox77** [comment]
> There is already a command called kill. You can use it for closing any app.

Kill is a system command, not a antimicrox command. It's a workaround and doesn't close the antimicrox icon in system tray. In addition, it causes an unexpected shutdown of the application instead of a controlled one. It doesn't seem like an appropriate recomendation.

**Comment by pktiuk** [comment]
@MaLDox77 kill command can send different types of signals. TERM is one of them and it is handled by AntiMicroX https://github.com/AntiMicroX/antimicrox/blob/5d5d8ba9667a70a229eb5dad9042923828ce434a/src/main.cpp#L76

Sending terminate command is an expected way of closing an app. In case of any problems with handling this signal just open the bug.

**Comment by pktiuk** [comment]
> and doesn't close the antimicrox icon in system tray

Does the icon in the system tray still exist after killing an app? If yes then it really may be a bug.

**Comment by MaLDox77** [comment]
> > and doesn't close the antimicrox icon in system tray
> 
> Does the icon in the system tray still exist after killing an app? If yes then it really may be a bug.

Misunderstanding comes because I use Antimicrox in windows and you're talking about linux ¯\_(ツ)_/¯

**Comment by pktiuk** [comment]
This is a big difference.   
Not many users on windows want (and know how to) use terminal.
